### ISSUE TITLE
Consider using PyTorch 2.0 version of FlashAttention (remove dependency on flash-attn)

### ISSUE THREAD

**Issue by Sciumo** [mosaicml/llm-foundry#103]
Per: https://github.com/HazyResearch/flash-attention/issues/203

> if you're using pytorch 2.0 then FlashAttention is already available through [torch.nn.functional.scaled_dot_product_attention](https://pytorch.org/docs/2.0/generated/torch.nn.functional.scaled_dot_product_attention.html).

The flash-attn project has build problems for many people.
Is it possible to consider using PyTorch 2.0 equivalent Flash Attention?

**Comment by vchiley** [comment]
For MPT we need to be able to use causal=True and we'd need to use attn_mask (aka attn_bias) to have ALiBi.

The variant exposed in [scaled_dot_product_attention docs](https://pytorch.org/docs/2.0/generated/torch.nn.functional.scaled_dot_product_attention.html) does not allow both. From docs:
![Screenshot 2023-05-10 at 9 58 06 PM](https://github.com/mosaicml/llm-foundry/assets/6439018/1def7c27-6518-4bbb-bbf9-03b0bec2bedc)
