### ISSUE TITLE
Can you add the pre-training of dbrx?

### ISSUE THREAD

**Issue by win10ogod** [mosaicml/llm-foundry#1074]
Can you add the pre-training of dbrx?

**Comment by dakinggg** [comment]
Sorry, what exactly are you looking for?

**Comment by win10ogod** [comment]
> Sorry, what exactly are you looking for?

I want to train mini dbrx.

**Comment by dakinggg** [comment]
Here is a starting yaml for training an MoE: https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/pretrain/testing-moe.yaml
And a starting yaml for training DBRX: You can change the `config_overrides` to make the model smaller.
