### ISSUE TITLE
Precision.AMP_BF16 is not supported for CPU training

### ISSUE THREAD

**Issue by wj210** [mosaicml/llm-foundry#109]
Hi,
I am trying to fine-tune the pretrained MPT-7b from HF hub. 
I followed #68 and set the yaml as such
model:
  name: hf_causal_lm
  # device: cpu
  pretrained: true
  pretrained_model_name_or_path: mosaicml/mpt-7b
  init_device: cpu
  d_model: 4096
  n_heads: 32
  n_layers: 32
  expansion_ratio: 4
  max_seq_len: ${max_seq_len}
  vocab_size: 50368
  attn_config:
    attn_impl: triton
   
I am unclear why does it say I am using CPU device, the init_device is confusing as it only allows CPU and meta, while CPU is used if you want to load a pretrained model from HF hub.

in the trainer class, the device is not passed in explicitly, so it is none by default, I tried to pass in GPU as the device and it has another error "ValueError: DeviceGPU cannot be created as torch.cuda is not available."

**Comment by wj210** [comment]
nvm i found out the reason

**Comment by premmotgi** [comment]
@wj210 what was the fix?
