### ISSUE TITLE
Installation issue from habana_alpha branch

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#1090]
<img width="1787" alt="Screenshot 2024-04-04 at 3 54 03 PM" src="https://github.com/mosaicml/llm-foundry/assets/26361028/05bfb5f3-3906-47b1-9d91-e33363eaef36">

**Comment by palash04** [comment]
Removed flash attn dependencies from requirements.txt, and it worked. Should it be installed for gaudi?

**Comment by abhi-mosaic** [comment]
That's right, the `flash-attn` dependenices should not be required for Gaudi. If you'd like to submit a PR to this branch editing the `setup.py` requirements, please go for it!
