### ISSUE TITLE
What are the hardware requirements?

### ISSUE THREAD

**Issue by soloist-tech** [mosaicml/llm-foundry#111]
See title lol

**Comment by hanlint** [comment]
Hi @soloist-tech , we've mainly tested on Ampere GPUs (A100s 40GB specifically) for training and finetuning. For inference, we also primarily use Ampere GPUs (A10s), however the community has gotten it to work with many other hardware. For example, see: https://github.com/ggerganov/ggml/pull/145 from the GGML folks.
