### ISSUE TITLE
Is there a way to figure out what dependencies are installed in the docker image?

### ISSUE THREAD

**Issue by sc-gr** [mosaicml/llm-foundry#1116]
E.g., if I'm using `mosaicml/llm-foundry:2.2.1_cu121_flash2_aws-latest`, is there a way to get the source of this docker image?

**Comment by dakinggg** [comment]
The image is built from the dockerfile (https://github.com/mosaicml/llm-foundry/blob/main/Dockerfile), with the base image coming from Composer (https://github.com/mosaicml/composer/tree/dev/docker). The simplest way to see everything in it would just be to make the container and then `pip list` to see the packages installed.
