### ISSUE TITLE
Finetuning with llm-foundry (composer format)

### ISSUE THREAD

**Issue by xgal** [mosaicml/llm-foundry#124]
Hi, 
Is there any option to convert HF ckpt to composer and FT with the llm-foundry scripts?

Thanks!

**Comment by dakinggg** [comment]
The finetuning example (https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/finetune_example/gpt2-arc-easy.yaml) yaml loads `gpt2` from huggingface and then trains using the llm-foundry. Is that what you are looking for?

**Comment by abhi-mosaic** [comment]
Closing this issue as it's gone stale.

We have HF conversion instructions here: https://github.com/mosaicml/llm-foundry/tree/main/scripts/inference#converting-a-composer-checkpoint-to-an-hf-checkpoint-folder 

And we have two PRs (#229 and #253) adding FasterTransformer support.
