### ISSUE TITLE
How to continue pretrain LLM fp8 with hf_causal_lm

### ISSUE THREAD

**Issue by YixinSong-e** [mosaicml/llm-foundry#1261]
When I continue pretrain HF models with fp8, there is an error:
TypeError: ComposerHFCausalLM.__init__() got an unexpected keyword argument 'fc_type'

**Comment by dakinggg** [comment]
This needs significantly more information to help you. Please provide what you are trying to run, what you modified in the yaml from the examples, and what the output of that is.

That being said, we only have support for fp8 when using ComposerMPTCausalLM at this time.

**Comment by lilakk** [comment]
Any plans to support fp8 for ComposerHFCausalLM?
