### ISSUE TITLE
code example for the onnx model

### ISSUE THREAD

**Issue by therealadityashankar** [mosaicml/llm-foundry#129]
Hi Mosaicml folks,

this is because of a lack of knowledge on my end, and I apologize for this, I'd be extremely greatful if you could give me example code on how to use the onnx model generated by https://github.com/mosaicml/llm-foundry/blob/main/scripts/inference/convert_hf_to_onnx.py

**Comment by hanlint** [comment]
Hello @therealadityashankar , thanks for the question. 

Once in ONNX, there are many options. For example, the [ONNX Runtime](https://github.com/microsoft/onnxruntime) can be used to run inference through the model. 

More specifically, you can take a look at our inference test to see how we load an ONNX model and run input through: https://github.com/mosaicml/composer/blob/2f257c9579d3eb44902f07d9551fdf4c0073f9e3/tests/utils/test_inference.py#L154-L163

**Comment by hanlint** [comment]
I will close this for now, please feel free to re-open if you run into any issues, or direct ONNX-related questions to that project!

**Comment by therealadityashankar** [comment]
Hi @hanlint I'm not able to understand how to use huggingface's tokenizers with this, how do I convert tokenizer input to the onnx model and how do I convert the onnx output to strings, I'd be greatful if you can provide me with an example for that

**Comment by therealadityashankar** [comment]
also I can't reopen this issue, I'll have to create a new issue
