### ISSUE TITLE
Finetune of scripts/train/yamls/finetune/mpt-7b_dolly_sft.yaml with alibi and triton emits sketchy log

### ISSUE THREAD

**Issue by tginart** [mosaicml/llm-foundry#134]
Tried setting max_seq_len to 5k and added alibi to attn config with Triton flash attn. 

Otherwise using: scripts/train/yamls/finetune/mpt-7b_dolly_sft.yaml.

Finetuning seems to be working but it does emit this sketchy log during pretraining. Wondering if anyone has seen this?

```
Map:  12%|█▏        | 1750/15015 [00:01<00:08, 1573.51 examples/s]Token indices sequence length is longer than the specified maximum sequence length for this model (5201 > 5120). Running this sequence through the model will result in indexing errors
```

**Comment by alextrott16** [comment]
You can ignore these specific warnings. The Hugging Face code emits this warning when tokenizing the dataset if it sees a sample that, when tokenized, is longer than the `model_max_length` parameter of the tokenizer.
Our finetuning code handles truncation based on the `max_seq_len` parameter that you set, and it will give you its own messages to announce any truncation that it is going on.
We have not seen any sign of the indexing errors that the HF warning refers to.
