### ISSUE TITLE
"speak with local sql "

### ISSUE THREAD

**Issue by gnosisd** [mosaicml/llm-foundry#135]
so i have this local db with some info and i want to test if this model can actually speak with the database while i drop non technical commands.for example chat gtp does that and very good actually,so i want to test if this even possible.i have found from other models like gpt4all script that can do that but there models are not trained to answer to non technical ways.

so does anyone know how i can do that ? using this local model and a local db to speak with each other and actually execute the commands to the sql db !

thanks for your time

**Comment by abhi-mosaic** [comment]
Hi @gnosisd , we did not specifically train MPT-7B to generate SQL commands so I would not expect it to work out of the box. But if you'd like to collect a finetuning dataset that goes from English->SQL, you can finetune on your data using the [instructions here,](https://github.com/mosaicml/llm-foundry/tree/main/scripts/train#llm-finetuning) and there is a folder with an [end-to-end example here.](https://github.com/mosaicml/llm-foundry/tree/main/scripts/train/finetune_example)
