### ISSUE TITLE
Why Flash Attention do not support attn bias [Alibi]?

### ISSUE THREAD

**Issue by srn-source** [mosaicml/llm-foundry#140]
https://github.com/mosaicml/llm-foundry/blob/6fcc126ea3c2c26d5671b10f9bd79f4206bb68c8/llmfoundry/models/layers/attention.py#LL136C4-L136C4

I am a new beginner of LLM, i wonder that what should i do if i want to use Fash attention and Alibi at the same time?

**Comment by abhi-mosaic** [comment]
Hi @srn-source , to use Flash Attention and ALiBi at the same time, all you have to do is use `attn_impl: triton` and `alibi: True`. See the configuration file [here](https://github.com/mosaicml/llm-foundry/blob/6fcc126ea3c2c26d5671b10f9bd79f4206bb68c8/llmfoundry/models/mpt/configuration_mpt.py#L10).

This will use a Triton-based implementation of FlashAttention that supports an attention mask. And this is the same setting we used to train MPT-7B with ALiBi..

**Comment by souvik0306** [comment]
Can you @abhi-mosaic throw some light on - https://github.com/mosaicml/llm-foundry/issues/196
