### ISSUE TITLE
the error of streaming

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#141]
**I followed the example in the readme file but encountered an error. How can I solve it?**
-------------------------------------------------
(mpt) root@autodl-container-b369119e00-b5dabb5c:~/autodl-tmp/llm-foundry/scripts/train# composer train.py yamls/pretrain/mpt-125m.yaml train_loader.dataset.split=train_small eval_loader.dataset.split=val_small

Initializing model...
cfg.n_params=1.25e+08
Building train loader...
Traceback (most recent call last):
  File "/root/autodl-tmp/llm-foundry/scripts/train/train.py", line 254, in <module>
    main(cfg)
  File "/root/autodl-tmp/llm-foundry/scripts/train/train.py", line 150, in main
    train_loader = build_dataloader(
  File "/root/autodl-tmp/llm-foundry/scripts/train/train.py", line 72, in build_dataloader
    return build_text_dataloader(
  File "/root/autodl-tmp/llm-foundry/llmfoundry/data/text_data.py", line 253, in build_text_dataloader
    dataset = StreamingTextDataset(
  File "/root/autodl-tmp/llm-foundry/llmfoundry/data/text_data.py", line 110, in __init__
    super().__init__(
  File "/root/miniconda3/envs/mpt/lib/python3.10/site-packages/streaming/base/dataset.py", line 325, in __init__
    self._shm_prefix, self._locals_shm = get_shm_prefix(my_locals, world)
  File "/root/miniconda3/envs/mpt/lib/python3.10/site-packages/streaming/base/shared.py", line 340, in get_shm_prefix
    raise ValueError(f'Reused local directory: {sorted(my_locals_set)} vs ' +
ValueError: Reused local directory: ['/root/autodl-tmp/llm-foundry/scripts/train/my-copy-c4/train_small'] vs ['/root/autodl-tmp/llm-foundry/scripts/train/my-copy-c4/train_small']. Provide a different one.
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 7309) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 7309) exited with code 1

**Comment by hanlint** [comment]
Hi @sysusicily , there is an edge case where if a previous job does not close gracefully, the shared memory is not cleaned up properly. Can you kill any stale python processes and then change the `local` folder in the yaml to something else?

**Comment by germanjke** [comment]
hi @hanlint any fixes? Annoying problem for debug. Ony killed python processes & rename train folder could helps :(

**Comment by karan6181** [comment]
Hi @germanjke, pythonic `SharedMemory` resource clean up does not play well when things crash unexpectedly, especially, during multi-process env. Streaming team is working on improving the resource handling and clean up using C++ and will have that change in future releases. Also, after changing `local` folder, do you still see the same issue?

**Comment by abhi-mosaic** [comment]
Closing this due to staleness, but feel free to reopen if you run into further issues.

We will have a v0.5.0 release of `mosaicml-streaming` soon.

**Comment by germanjke** [comment]
no updates here?

**Comment by germanjke** [comment]
any fixes? @abhi-mosaic @hanlint

**Comment by karan6181** [comment]
Hi @germanjke , We have fixed the issue in Streaming `main` branch. If facing a leaked shared memory issue, user can call `streaming.base.util.clean_stale_shared_memory()` method once in their script to clean up the stale shared memory before instantiation of StreamingDataset. We will soon be releasing a new version of streaming with this changes. You are welcome to use streaming from `main` branch.

**Comment by germanjke** [comment]
hi @karan6181 
thank you a lot
can we put it in `pip install streaming`?
I cant import it directly from streaming 0.5.0, only with `git clone` I think

**Comment by karan6181** [comment]
Streaming 0.5.1 is released. Can you try the latest version ? Thanks!
