### ISSUE TITLE
the select for multi-GPU card

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#142]
"How to specify the specific GPU number, such as GPU:3 or GPU:2, in a multi-GPU card setup?"

**Comment by abhi-mosaic** [comment]
Hi @sysusicily, when you launch these scripts like `composer train.py ...`, the Composer launcher script will attempt to run on all available GPUs. There are [some arguments](https://github.com/mosaicml/composer/blob/9824a92d10fba2533d7e57ffa1379e29e3f45ec2/composer/cli/launcher.py#L31) you can use to control this behavior like `composer -n 4 train.py ...` which would limit to using only 4 GPUs. 

But to get fine-grained control, I would recommend setting the environment variable `CUDA_VISIBLE_DEVICES` before running a script to target exactly the GPUs you want.

```bash
# This will run on all available GPUs
composer train.py ...

# This will run on first 4 available GPUs
composer -n 4 train.py ...

# This will run across 4 GPUs but exactly GPUs #2, #3, #4, #5
export CUDA_VISIBLE_DEVICES="2,3,4,5"
composer train.py ...

# This will run on 1 GPU but exactly GPUs #3
export CUDA_VISIBLE_DEVICES="3"
composer train.py ...
```
