### ISSUE TITLE
Explicit composer mention

### ISSUE THREAD

**Issue by StrangeTcy** [mosaicml/llm-foundry#144]
At the moment your readme says: 

> This repository contains code for training, finetuning, evaluating, and deploying LLMs for inference with Composer and the [MosaicML platform](https://forms.mosaicml.com/demo?utm_source=github.com&utm_medium=referral&utm_campaign=llm-foundry).

and doesn't provide a link to composer, and then your training instruction says

```
# Train an MPT-125m model for 10 batches
composer train/train.py \
  train/yamls/pretrain/mpt-125m.yaml \
  data_local=my-copy-c4 \
  train_loader.dataset.split=train_small \
  eval_loader.dataset.split=val_small \
  max_duration=10ba \
  eval_interval=0 \
  save_folder=mpt-125m
```

 like it's the most natural thing in the world. 
I was lucky to guess that composer is [composer](https://github.com/mosaicml/composer) that you have developed,
but that raises more questions: does it come preinstalled in the docker image you recommend? Does installing llm-foundry involve installing composer automatically?
Should one install it manually to be able to use llm-foundry?

Clearing all this up would be greatly appreciated

**Comment by nikaashpuri** [comment]
have tried this, it gets installed after the pip install step and works as expected

**Comment by hanlint** [comment]
Thanks @StrangeTcy, we've made a PR to explain this better! `composer` is indeed part of the `llm-foundry`'s install requirements.
