### ISSUE TITLE
Use the nvidia-supplied nvidia-ml-py instead of pynvml

### ISSUE THREAD

**Issue by mattip** [mosaicml/llm-foundry#154]
This project [depends on pynvml](https://github.com/mosaicml/llm-foundry/blob/93e3290fe2c228a50a67546e6191b71db7171ccb/setup.py#L57), where the nvidia-blessed bindings to nvml are in the [nvidia-ml-py](https://pypi.org/project/nvidia-ml-py/) package instead. This is causing problems for the [gpustat project](https://github.com/wookayin/gpustat/issues/153#issuecomment-1551036105), which needs some internals from nvidia-ml-py to properly support older nvml version. Would it be possible to switch?

**Comment by hanlint** [comment]
Thanks @mattip , the `pynvml` dependency may be extraneous, we are confirming!

**Comment by mattip** [comment]
Thanks!
