### ISSUE TITLE
Not getting a proper response

### ISSUE THREAD

**Issue by gauravkaliadev** [mosaicml/llm-foundry#155]
Hi,

I am exploring how can I provide custom data and fine-tune the model but before I get to that step I wanted to follow the readme and make sure everything is set up correctly.

I am following the link below.
https://github.com/mosaicml/llm-foundry/blob/main/README.md

I have managed to complete the setup but when I run the last command with the prompt I am not getting a proper response.

![image](https://github.com/mosaicml/llm-foundry/assets/123362715/37ff6dc4-2c75-45c9-a065-7d67a7bf18f1)

Please suggest if there is anything I am missing or not doing correctly.

Thanks
Gaurav

**Comment by growlix** [comment]
Hi Gaurav,

Are you using a 125m-parameter model as in the README?

Best,
Matthew

**Comment by gauravkaliadev** [comment]
Hi Matthew,

I am following exactly what we have in the readme.

Apart from facing issues during the environment setup, I have not done anything differently.

Let me know if you have any suggestions.

Thanks
Gaurav

**Comment by abhi-mosaic** [comment]
Hi @gauravkaliadev , the Quickstart section of the README.md is meant to showcase the different LLM Foundry tools end-to-end, but is **not** intended to produce a good model checkpoint. It is just training a 125M model **from scratch** for 10 batches and running `model.generate()`. 

If you would like to finetune our opensourced MPT-7B models that are available on the HF Hub, you'll want to follow the instructions here: https://github.com/mosaicml/llm-foundry/tree/main/scripts/train#llm-finetuning and particularly use this YAML as a guide: https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/finetune/mpt-7b_dolly_sft.yaml

I will close this issue for now, but feel free to reopen if you run into further issues.

**Comment by gauravkaliadev** [comment]
Thanks, @abhi-mosaic .

I will follow the links you have shared.
