### ISSUE TITLE
support for tensorboard

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#158]
Can  add support for Tensorboard in the yaml configuration so that  can visualize the loss trend more intuitively?

**Comment by vchiley** [comment]
We'd need to enable the [composer enabled tensorboard](https://docs.mosaicml.com/projects/composer/en/latest/notes/tensorboard_logger.html#tensorboard-monitoring) logger [here](https://github.com/mosaicml/llm-foundry/blob/93e3290fe2c228a50a67546e6191b71db7171ccb/llmfoundry/utils/builders.py#L67) within our scripts. Its not high priority for us, but we are open to community contributions. Feel free to open a PR.

**Comment by hanlint** [comment]
Hello @sysusicily , I added support in this PR (https://github.com/mosaicml/llm-foundry/pull/166). Can you test that branch (`hanlin/tb`) to see if it works? You'd need to install tensorboard with `pip install llm-foundry .[tensorboard]`

**Comment by hanlint** [comment]
Closing as completed by #166
