### ISSUE TITLE
Inquiry Regarding Benchmark Testing Environment and Parameters

### ISSUE THREAD

**Issue by yhcho87** [mosaicml/llm-foundry#1584]
## ❓ Question

I am writing to request some clarification regarding the benchmark tests shared on GitHub at https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/benchmarking/README.md.

Specifically, I have the following questions:
 
1. Could you please specify the environment in which these benchmark tests were conducted? (e.g., On-premises, OCI, AWS, Azure, etc.)
2. Regarding the H100 80G BF16 benchmark tests, what criteria were used to determine the input sequence length, MicroBatchSize, GradAccum, and GlobalBatchSize parameters?
3. For the same H100 80G BF16 tests, could you explain the rationale behind setting the Activation Checkpointing option to True?
 
I would greatly appreciate any insights you could provide on these matters. Thank you in advance for your time and assistance.

**Comment by dakinggg** [comment]
Hi, that benchmarking hasn't been updated in a while, and I don't recall which cloud it was done on, but it was done with strong interconnect (3200 Gbps). The parameters were chosen subjectively to cover a range of reasonable values. Activation checkpointing was done with both values, depending on what would fit memory wise.
