### ISSUE TITLE
Finetune MPT with transformers

### ISSUE THREAD

**Issue by yangjianxin1** [mosaicml/llm-foundry#160]
hello, thanks to your work.
Can I finetune MPTForCausalLM with transfomers.Trainer?

**Comment by abhi-mosaic** [comment]
Hi @yangjianxin1 , we have not tested finetuning with the HF Trainer, but given that our model is a subclass of the HF `PreTrainedModel` base class, I don't see any blockers. 

Our official supported codepath for finetuning MPT-7B using the [Composer](https://github.com/mosaicml/composer) trainer is here: https://github.com/mosaicml/llm-foundry/tree/main/scripts/train#llm-finetuning

Closing this issue for now but please let us know if you run into any blockers!
