### ISSUE TITLE
ValueError: --out_root=./my-copy-c4 contains ['train_small'] which cannot overlap with the requested splits ['train_small', 'val_small'].

### ISSUE THREAD

**Issue by NishaDeepak** [mosaicml/llm-foundry#162]
I ran the below command to make a copy of C4 as mentioned in the documentation:
python ../llm-foundry-main/scripts/data_prep
/convert_dataset_hf.py --dataset c4 --data_subset en --out_root ./my
-copy-c4 --splits train_small val_small --concat_tokens 2048 --token
izer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'

I receive the below mentioned error: 
ValueError: --out_root=./my-copy-c4 contains ['train_small'] which cannot overlap with the requested splits ['train_small', 'val_small'].

**Comment by hanlint** [comment]
Hello @NishaDeepak , if I understand the code properly, this means that `/my-copy-c4` already has an existing subfolder called `train_small`. Can verify if that is the case, and if so delete that existing folder?

**Comment by roshank123** [comment]
Hello @hanlint @NishaDeepak just chiming in, that response served to the correct that error for me. Just go in and delete the pre-existing "train_small" sub-folder and you should be all good.

**Comment by abhi-mosaic** [comment]
Closing for now, but feel free to reopen if the error persists.
