### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/000001_barrier'

### ISSUE THREAD

**Issue by julianfaraone** [mosaicml/llm-foundry#170]
Trying to run the simple example with mpt-125m.yaml. I.e. when running this code inside the docker:

`# Train an MPT-125m model for 10 batches
composer train/train.py \
  train/yamls/pretrain/mpt-125m.yaml \
  data_local=my-copy-c4 \
  train_loader.dataset.split=train_small \
  eval_loader.dataset.split=val_small \
  max_duration=10ba \
  eval_interval=0 \
  save_folder=mpt-125m`

I get this error: 

`  File "/usr/lib/python3.10/multiprocessing/shared_memory.py", line 104, in __init__
    self._fd = _posixshmem.shm_open(
FileNotFoundError: [Errno 2] No such file or directory: '/000001_barrier'`

**Comment by karan6181** [comment]
@julianfaraone Thanks for trying out MPT. Wondering, do you have the full log ? I am afraid this error message is a by-product of other error message, for example, something might have failed before this.

**Comment by julianfaraone** [comment]
Thanks. It was that I had the 'fp16' precison set incorrectly. However now my error is:

`  File "/llm-foundry/llmfoundry-venv/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 73, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/llm-foundry/llmfoundry-venv/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 63, in _bench
    return do_bench(kernel_call)
  File "/llm-foundry/llmfoundry-venv/lib/python3.10/site-packages/triton/testing.py", line 140, in do_bench
    fn()
  File "/llm-foundry/llmfoundry-venv/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 62, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "/llm-foundry/llmfoundry-venv/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 200, in run
    return self.fn.run(*args, **kwargs)
  File "<string>", line 43, in _bwd_kernel
RuntimeError: Triton Error [CUDA]: invalid argument`

**Comment by abhi-mosaic** [comment]
@julianfaraone what hardware are you running on? And are you using the Docker image listed in the README? This is likely an error due to Triton incompatibility.

If the issue persists, just change `attn_impl: torch` and this will let you fall back to Torch-based attention and bypass the Triton path.

**Comment by julianfaraone** [comment]
Thanks. With the `attn_impl: torch` and `loss_fn : torch_crossentropy` I was able to get the training working.

I'm running this using the Docker image in the README and I'm using 8x "Tesla V100-SXM2". Is it possible to get the Triton path working with these?

**Comment by hanlint** [comment]
Hi @julianfaraone , glad this worked! We've seen issues working with Triton and Volta cards, so this is not recommended. Closing this issue -- please open a new one if you run into additional issues, thanks!
