### ISSUE TITLE
where can I find training code or configs about MPT-7B-StoryWriter

### ISSUE THREAD

**Issue by metacryptom** [mosaicml/llm-foundry#171]

**Comment by vchiley** [comment]
Training code: https://github.com/mosaicml/llm-foundry/tree/main/scripts/train
Fine-tuning examples: https://github.com/mosaicml/llm-foundry/tree/main/scripts/train/finetune_example

re configs, see [this comment](https://github.com/mosaicml/llm-foundry/issues/70#issuecomment-1544830380)
