### ISSUE TITLE
Can I use mpt-7b_dolly_sft.yaml used to train MPT-Instruct model

### ISSUE THREAD

**Issue by NarenZen** [mosaicml/llm-foundry#173]
Hi,

Just saw a couple of scripts have been uploaded to finetune the MPT model.

I need a custom MPT Instruct model.

Two Questions:
1. Can I just finetune the existing MPT Instruct model with some extra domain data? If so, how can I do that
2. Is my understanding correct: 
        - mpt-7b_dolly_sft.yaml is used to fine-tune a base MPT 7B model to work as an instruct model(MPT-Instruct).
        - in mpt-7b_dolly_sft.yaml, if I replace `hf_name: mosaicml/dolly_hhrlhf`  with `hf_name: custom_data`, then this would be a brand new custom instruct model and has relation to MPT-Instruct 7b

@hanlint

**Comment by samhavens** [comment]
1. Yes, change the `model.pretrained_model_name_or_path` [here](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/finetune/mpt-7b_dolly_sft.yaml#L10) to be `mosaicml/mpt-7b-instruct`
2. If you just change the dataset in that YAML, then you would start with the MPT-7B base model. It would be related to MPT-7B-Instruct in that they would share a base model. Alternatively, you could start with MPT-7B-Instruct (question 1) and also change the dataset. This _should_ work better than starting with the base model; but in my experience so far, the best option is to start from both and check downstream performance.
