### ISSUE TITLE
Error while loading converted hf model(from composer checkpoint)

### ISSUE THREAD

**Issue by singhalshikha518** [mosaicml/llm-foundry#176]
I tried converting composer chkpt to HF using the below command:
python convert_composer_to_hf.py --composer_path mpt_finetune/llm-foundry/mpt7b_summary/checkpoints/ep3-ba240-rank0.pt --hf_output_path mpt_finetune/llm-foundry/mpt7b_sum1/ --output_precision fp32

It ran successfully but while loading the model using below code i am getting error:
error:
mpt_finetune/llm-foundry/mpt7b_sum requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option trust_remote_code=True to remove this error.

code:
from transformers import AutoTokenizer, AutoModelForCausalLM,GenerationConfig
import torch

tokenizer = AutoTokenizer.from_pretrained("mpt_finetune/llm-foundry/mpt7b_sum")

model = AutoModelForCausalLM.from_pretrained("mpt_finetune/llm-foundry/mpt7b_sum")

Am i missing anything?

**Comment by singhalshikha518** [comment]
> Hi @singhalshikha518 , yes you need to add `trust_remote_code=True`, e.g.
> 
> ```
> import transformers
> model = transformers.AutoModelForCausalLM.from_pretrained(
>   'mosaicml/mpt-7b',
>   trust_remote_code=True
> )
> ```

I tried adding trust_remote_code = True. But still same error

**Comment by dakinggg** [comment]
You'll need to add it the tokenizer as well, if you didn't already.

**Comment by hanlint** [comment]
@singhalshikha518 -- closing this as stale. Please re-open if adding the `trust_remote_code` to both the model and the tokenizer did not solve the issue. Thanks!
