### ISSUE TITLE
How to adapt to different context size?

### ISSUE THREAD

**Issue by jwatte** [mosaicml/llm-foundry#191]
I have a use case where 2048 context is too short, and 65536 is way too long.
For efficiency, I'd like to adapt this model to a 4096 or perhaps 6144 token context.
What is involved in doing this? Can I do this with transfer learning, or would that be a full re-training pass?
I can't find any good references on this, other than attempting to diff the driver code between the Writer and the Instruct versions, which is tough going.

**Comment by samhavens** [comment]
You can instantiate the model with a max length of 4096:

```python
model = AutoModelForCausalLM.from_pretrained(model_name, trust_remote_code=True, max_seq_len=4096)
```
