### ISSUE TITLE
Inferencing with multigpu

### ISSUE THREAD

**Issue by singhalshikha518** [mosaicml/llm-foundry#195]
How to do inferencing using multigpu as device_map="auto" is not supported.

**Comment by vchiley** [comment]
PR in progress: https://github.com/mosaicml/llm-foundry/pull/225

**Comment by abhi-mosaic** [comment]
This should be supported now that #225 is merged! Closing the issue but @singhalshikha518 please give it a try and let us know if you run into any issues
