### ISSUE TITLE
Kernel Crashes when trying to load model to CUDA

### ISSUE THREAD

**Issue by souvik0306** [mosaicml/llm-foundry#196]
I am trying to use the "mosaicml/mpt-7b-instruct" model for my project. However, when I instantiate the model, I encounter an Error with the message ``` If your model does not use `alibi` or `prefix_lm` we recommend using `attn_impl: flash` otherwise we recommend using `attn_impl: triton`.   warnings.warn('Using `attn_impl: torch`. If your model does not use `alibi` or ' + '`prefix_lm` we recommend using `attn_impl: flash` otherwise ' + 'we recommend using `attn_impl: triton`.')```

After this point the Kernel Crashes or the Terminal gets Killed. 

I am facing this error on running - 
```
generate = pipeline(
    "mosaicml/mpt-7b-instruct",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)
stop_token_ids = generate.tokenizer.convert_tokens_to_ids([""])
```

I am using the latest version of the transformers library and the model checkpoint. I have also ensured that all the dependencies are up to date.

Can anyone help me understand why I am getting this error and how I can resolve it? Is there a specific version of the "mosaicml/mpt-7b-instruct" model that supports the whole execution of loading the model to CUDA?

Any assistance would be greatly appreciated. Thank you!

Note: Make sure to include relevant details about your environment, such as the versions of transformers and PyTorch you are using.

My System Specs -
NVIDIA GeForce RTX 4090
PyTorch Cuda 11.1

Jupyter Notebooks Used - 
1. [First One](https://colab.research.google.com/drive/16D9tjggLukD38Un0hC-Gss3mrehPXng_?usp=sharing#scrollTo=vWCUGLUsgnbA)
2. [Second One](https://colab.research.google.com/github/curtisshipley/llm-info/blob/main/Working_YT_MPT_Instruct_7B.ipynb)

**Comment by vchiley** [comment]
```
warnings.warn('Using `attn_impl: torch`. If your model does not use `alibi` or ' + '`prefix_lm` we recommend using `attn_impl: flash` otherwise ' + 'we recommend using `attn_impl: triton`.')
```
is a warning not an error

what error are you getting?


From the notebook you are using, I see that you use `pip install triton==2.0.0 -U`
That version of triton will NOT work with `attn_imp: triton` ([see here](https://github.com/HazyResearch/flash-attention/issues/171))

Please follow the repo [prereq and install instructions](https://github.com/mosaicml/llm-foundry#prerequisites) (including the package versions)

**Comment by souvik0306** [comment]
@vchiley What is the minimum vRAM GPU requirement - 
As I was able to run the code on A100 with a 40GB RAM not on RTX 4090 with 24 GB Ram

**Comment by souvik0306** [comment]
Can you please answer this - @hanlint @vchiley What is the minimum GPU vRAM or GPU memory requirement -
As I was able to run the code on A100 with 40GB RAM not on RTX 4090 with 24 GB RAM

**Comment by samhavens** [comment]
@souvik0306 the demos are running on 24GB A10s so that's definitely enough

**Comment by souvik0306** [comment]
> @souvik0306 the demos are running on 24GB A10s so that's definitely enough
Anything on this - As I was able to run the code on A100 with 40GB RAM but not on RTX 4090 with 24 GB RAM.

Max_Token_Size = 1024 and float16 quantization

**Comment by abhi-mosaic** [comment]
Hi @souvik0306 , I would expect that 24GB is sufficient to run inference of MPT-7B in 16-bit precision. The model weights take up about 14GB of memory and the KV cache for 1024 tokens should be quite small, <1GB.

Here you can find the code directly from our HF Hub demo of MPT-7B-Instruct: https://huggingface.co/spaces/mosaicml/mpt-7b-instruct/blob/main/quick_pipeline.py#L34-L68 

In this repo you can find an `hf_generate.py` script and [instructions](https://github.com/mosaicml/llm-foundry/tree/main/scripts/inference#interactive-generation-with-hf-models) that you can use like so to test on your machine:
```
python hf_generate.py \
    --name_or_path mosaicml/mpt-7b-instruct \
    --max_new_tokens 256 \
    --prompts \
      "The answer to life, the universe, and happiness is" \
      "MosaicML is an ML training efficiency startup that is known for" \
      "Here's a quick recipe for baking chocolate chip cookies: Start by" \
      "The best 5 cities to visit in Europe are"
```

Some maybe helpful tips:
* make sure you move the model to `bfloat16` directly on GPU, and not as part of a 2-step conversion like CPU -> GPU FP32 -> GPU BF16
* make sure you are using with `torch.no_grad()` to prevent input activations from being saved during inference time


Closing this thread for now but please reopen if you continue to run into issues.
