### ISSUE TITLE
ONNX conversion is too memory expensive  

### ISSUE THREAD

**Issue by makermotion** [mosaicml/llm-foundry#201]
When I try to use "convert_hf_to_onnx.py" it is extremely expensive in terms of DRAM (or VRAM if I try to load the model and input to CUDA device). I am not able to convert to ONNX even with pretty good system resources. Is there any solution to this? Anybody successful convert to ONNX?

**Comment by bhupendrasalesken** [comment]
@makermotion were you able to find the solution , i am facing the same issue?
Thanks

**Comment by makermotion** [comment]
@bhupendrasalesken hey, the solution for me was more memory :) I think this is the nature of ONNX conversion for huge models.

**Comment by zacharyblank** [comment]
@makermotion you closed this? I am on a machine with 720GB of RAM and still hitting OOM trying to convert storywriter with 16k sequence length and batch size of 1.

**Comment by makermotion** [comment]
@zacharyblank I can understand that it might be a problem with longer context lengths but I think no minor changes will solve this.
