### ISSUE TITLE
S3 ckpt saving

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#202]
I would like know how you connect to `s3` bucket?

i'm getting

```
  File "/usr/lib/python3/dist-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

already added export AWS_ACCESS_KEY and AWS_SECRET_KEY in shell file, but it doesn't help

you connect via `boto3` or `aws-cli`? maybe I need to define project name? 

my save folder looks like

`save_folder: s3://s3.blablabla.com/path/to/my/ckpts`

**Comment by germanjke** [comment]
i have typo in `AWS_ACCESS_KEY` `AWS_SECRET_KEY `

exported like this

```
export AWS_SECRET_ACCESS_KEY="XXXXXXXXXXXX"
export AWS_ACCESS_KEY_ID="XXXXXXXXXXX"
```

now error is `Boto3 error: The AWS Access Key Id you provided does not exist in our records`

maybe the problem on my side

**Comment by germanjke** [comment]
export `S3_ENDPOINT_URL` as well solved this problem

**Comment by hanlint** [comment]
Thank you @germanjke !
