### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChiefBlacktail** [mosaicml/llm-foundry#211]
How can I get the model output's last hidden layer? nothing I try seems to work.
Thanks in advance!

**Comment by abhi-mosaic** [comment]
Hi @ChiefBlacktail I believe this is a bug that is being fixed as part of PR #210

**Comment by vchiley** [comment]
In main `final_hidden_state = output.hidden_states[-1]`

**Comment by ChiefBlacktail** [comment]
@abhi-mosaic Thanks, do you know when it will be fixed?
@vchiley Yeah, but it returns a NoneType instead of the tensor. Thanks anyways!
