### ISSUE TITLE
Quickstart pretrain error

### ISSUE THREAD

**Issue by semsevens** [mosaicml/llm-foundry#215]
I use pytorch2 and latest code.

$ composer train/train.py \
>   train/yamls/pretrain/mpt-125m.yaml \
>   data_local=my-copy-c4 \
>   train_loader.dataset.split=train_small \
>   eval_loader.dataset.split=val_small \
>   max_duration=10ba \
>   eval_interval=0 \
>   save_folder=mpt-125m

Initializing model...
cfg.n_params=1.25e+08
Building train loader...
Building eval loader...
Building trainer...
Traceback (most recent call last):
...
RuntimeError: Cannot writeback when the parameter shape changes
Expects torch.Size([1769472]) but got torch.Size([2304, 768])
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.

**Comment by abhi-mosaic** [comment]
Hi @semsevens and @DayOfThePenguin , LLM Foundry and MPT were all built with torch 1.13 and that's still the recommended install version (and the version in our Docker image `mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04`)

We are actively working on torch2 support (and you can see some active PRs :) but it we are still a week or two away from a stable release tag with `torch2` support.

@DayOfThePenguin could you clarify the system on which you had to use torch >=2 ? That is very surprising to me and I would love to know more.

**Comment by vchiley** [comment]
Note: I've only gotten this error when using a single GPU with FSDP.
If you are using one GPU, you shouldn't be using FSDP.

**Comment by abhi-mosaic** [comment]
Closing this issue for now, but @DayOfThePenguin if you can send a repro for this issue we would very much appreciate it!

> I can only run the released MPT models with torch >= 2 because of a similar low-level API difference in the matmul call signature.

**Comment by DayOfThePenguin** [comment]
I was only able to reproduce with the old version of the Triton attention implementation (before it was updated ~10 days ago).  With the changes, I'm able to run all models with torch 1.13.1!
