### ISSUE TITLE
otp is not receiving yet 

### ISSUE THREAD

**Issue by manishvj125** [mosaicml/llm-foundry#216]
![otp-issue](https://github.com/mosaicml/llm-foundry/assets/120380716/459df83d-af57-453d-be53-6b4d5a27321a)

**Comment by hanlint** [comment]
Hello @manishvj125 , thank you for your interest! We are working through our waitlist currently, and will let you know when we can open access. If you are already part of our customer group, please reach out to your customer rep to resolve the login issue!
