### ISSUE TITLE
Question regarding Langchain usage with a transformers "text-generation"  pipeline

### ISSUE THREAD

**Issue by thusithaC** [mosaicml/llm-foundry#220]
Hi I was attempting to use Langchain with a transformers  "text-generation" transformers pipeline as described in the video here (this was in the main readme of this repo, so I guess it is somewhat approved by devs now)

When I initialize the pipeline I get the below warning:

`The model 'MPTForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM',  ...`

Is this safe to ignore?

`
generate_text = transformers.pipeline(
    model=model, tokenizer=tokenizer,
    return_full_text=True,  # langchain expects the full text
    task='text-generation',
    device=device,
    # we pass model parameters here too
    stopping_criteria=stopping_criteria,  # without this model will ramble
    temperature=0.1,  # 'randomness' of outputs, 0.0 is the min and 1.0 the max
    top_p=0.15,  # select from top tokens whose probability add up to 15%
    top_k=0,  # select from top 0 tokens (because zero, relies on top_p)
    max_new_tokens=512,  # mex number of tokens to generate in the output
    repetition_penalty=1.1  # without this output begins repeating
)
    `

Packages were mostly based on the `setup.py`

`install_requires = [
    'composer[nlp,wandb]>=0.14.1,<0.15',
    'mosaicml-streaming>=0.4.1,<0.5',
    'torch==1.13.1',
    'datasets==2.10.1',
    'sentencepiece==0.1.97',
    'einops==0.5.0',
    'omegaconf>=2.2.3,<3',
    'slack-sdk<4',
    'mosaicml-cli>=0.3,<1',
    'onnx==1.13.1',
    'onnxruntime==1.14.1',
    'langchain==0.0.169',
    'bitsandbytes==0.35.0',
    'accelerate==0.18.0',
    'peft==0.2.0',
    'sentence-transformers==2.2.2',
    'accelerate>=0.16.0,<1',
    'einops'
]`

**Comment by abhi-mosaic** [comment]
> The model 'MPTForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM',  ...

Yes, it is safe to ignore this error! This happens because `MPTForCausalLM` is a custom class and not in the `transformers` library but it should work with `model.generate()` and the `text-generation` pipeline just fine.
