### ISSUE TITLE
Why does convert_dataset_json.py only support 'train' for the --split argument?"

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#223]
![image](https://github.com/mosaicml/llm-foundry/assets/133207026/29383cac-49ca-4d78-8317-974413f6d26a)

**Comment by growlix** [comment]
From the trace you posted, it looks like this is an issue with your dataset and/or HuggingFace's `datasets` library—the error is being raised by `datasets/arrow_reader.py`. My hunch is that there's no `val` split for your dataset, though I could be mistaken.
