### ISSUE TITLE
Reproduce Table 3 results from the blog

### ISSUE THREAD

**Issue by eldarkurtic** [mosaicml/llm-foundry#226]
Hi, I would like to reproduce pretraining and finetuning setup from the Table 3 from the blog https://www.mosaicml.com/blog/mpt-7b . Have you open-sourced the recipes for it and the corresponding datasets?

**Comment by vchiley** [comment]
see https://github.com/mosaicml/llm-foundry/issues/171#issuecomment-1564715141
