### ISSUE TITLE
Auto uninstall correct version torch 1.13.1

### ISSUE THREAD

**Issue by ryurobin1990** [mosaicml/llm-foundry#228]
Hi I know the support for torch 2.0.1 is not available because of error when run composer:
```
RuntimeError: Cannot writeback when the parameter shape changes
Expects torch.Size([1769472]) but got torch.Size([2304, 768])
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
```

However when I installed torch with version 1.13.1 and run cmd `pip install -e ".[gpu]"` I found it uninstall torch 1.13.1 for me and install torch 2.0.1 for me. Any suggestions?

[pip_install_wrong_torch_version.txt](https://github.com/mosaicml/llm-foundry/files/11581180/pip_install_wrong_torch_version.txt)

**Comment by vchiley** [comment]
We are starting to integrate / use [torch2](https://github.com/mosaicml/llm-foundry/pull/193#issue-1720978212).
In that PR we allow for [torch2.0.1 installs](https://github.com/mosaicml/llm-foundry/blob/main/setup.py#L52).

From your log, we can see that you already have torch1.13.1 installed
```
Requirement already satisfied: torch<=2.0.1,>=1.13.1 in /home/ran/.local/lib/python3.10/site-packages (from llm-foundry==0.1.0) (1.13.1+cu117)
```
but your pip cache has torch2.0.1 in it
```
Collecting torch<=2.0.1,>=1.13.1 (from llm-foundry==0.1.0)
  Using cached torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)
```
so pip updts the torch version
```
  Attempting uninstall: torch
    Found existing installation: torch 1.13.1+cu117
    Uninstalling torch-1.13.1+cu117:
      Successfully uninstalled torch-1.13.1+cu117
```

You could try
1. clearing your pip cache (delete the cached torch2.0.1 wheel)
1. edit [this line in setup.py](https://github.com/mosaicml/llm-foundry/blob/main/setup.py#L52) to be `'torch==1.13.1',` such that torch1.13.1 is a hard requirement.
1. try getting the torch2.0.1 version working (start with a venv where you already have torch2.0.1 installed). Starting with the [torch2.0.1 composer docker image (mosaicml/pytorch:2.0.1_cu118-python3.10-ubuntu20.04)](https://docs.mosaicml.com/projects/composer/en/latest/getting_started/installation.html#pytorch-images), I haven't had any issues getting it running and the performance is the same. I cannot say I have been able to get the same error you are getting.

**Comment by ryurobin1990** [comment]
Thanks for the answer! @vchiley
