### ISSUE TITLE
hf_causal_lm vs mpt_causal_lm

### ISSUE THREAD

**Issue by eldarkurtic** [mosaicml/llm-foundry#231]
Hi,

I assume the difference between these two models is that `mpt_causal_lm` has ALiBi, FlashAttention and other model arch optimizations, while `hf_causal_lm` stands for standard models from the HF-transformers library.
But what happens when we use `name: hf_causal_lm` and `pretrained_model_name_or_path: mosaicml/mpt-7b`, such as in this yaml config: https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/finetune/mpt-7b_dolly_sft.yaml

**Comment by vchiley** [comment]
`name: hf_causal_lm` enables us to load models (such as `pretrained_model_name_or_path: mosaicml/mpt-7b `) from HFHub ie it will load the model defined [here](https://huggingface.co/mosaicml/mpt-7b/blob/main/modeling_mpt.py) which is a copy of the model defined by `mpt_causal_lm` [here](https://github.com/mosaicml/llm-foundry/blob/main/llmfoundry/models/mpt/modeling_mpt.py).

Its the same model. Only difference is `mpt_causal_lm` loads the model using from llm-foundry codebase (maintained in this repo), `hf_causal_lm` loads the model from the code from [hfhub](https://huggingface.co/mosaicml/mpt-7b/blob/main/modeling_mpt.py)

**Comment by eldarkurtic** [comment]
Got it, thanks a lot for clarification! 
What is expected behaviour when `name: mpt_causal_lm` is used with a checkpoint from HF-hub `pretrained_model_name_or_path: mosaicml/mpt-7b`?

**Comment by abhi-mosaic** [comment]
Hi @eldarkurtic ,

If you use `mpt_causal_lm` it does not allow for reading any weights from HF Hub. Adding kwargs like `pretrained_model_name_or_path: mosaicml/mpt-7b` to the model config will just be a no-op.

You can find the model constructor here which takes in the OmegaConf config `om_model_config`: https://github.com/mosaicml/llm-foundry/blob/1ad53be68a154e8c63a4e9fc0a6b6a602845bb70/llmfoundry/models/mpt/modeling_mpt.py#L616
