### ISSUE TITLE
Fine-tuning MPT-1B as instruct model

### ISSUE THREAD

**Issue by atharvou23** [mosaicml/llm-foundry#239]
Hi,
Can we fine-tune the huggingface model (mosaicml/mpt-1b-redpajama-200b) using './finetune/mpt-7b_dolly_sft.yaml' by tweaking "pretrained_model_name_or_path:" and "tokenizer"?

If not, can we get the composer checkpoint for 'mosaicml/mpt-1b-redpajama-200b' so that we can fine-tune it on the custom data using './finetune/1b_local_data_sft.yaml'?

**Comment by jacobfulano** [comment]
Yes, you should be able to fine-tune the MPT-1B HF model by changing the `pretrained_model_name_or_path` and the `tokenizer`. See #231

**Comment by atharvou23** [comment]
Hi @jacobfulano 
Tried out the following tweaks within the suggested env
```
model:
  name: hf_causal_lm
  pretrained: true
  pretrained_model_name_or_path: mosaicml/mpt-1b-redpajama-200b

```
and
```
tokenizer:
  name: mosaicml/mpt-1b-redpajama-200b
```
getting the following error

`Initializing model...
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/root/llm-foundry/scripts/train/train.py", line 254, in <module>
    main(cfg)
  File "/root/llm-foundry/scripts/train/train.py", line 144, in main
    model = build_composer_model(cfg.model, tokenizer)
  File "/root/llm-foundry/scripts/train/train.py", line 67, in build_composer_model
    return COMPOSER_MODEL_REGISTRY[model_cfg.name](model_cfg, tokenizer)
  File "/root/llm-foundry/llmfoundry/models/hf/hf_causal_lm.py", line 57, in __init__
    raise ValueError(
ValueError: config does not have attribute "attn_config" to override (attn_config: {'attn_impl': 'triton', 'attn_uses_sequence_id': False}).
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 7324) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 7324) exited with code 1`

I tried it with the 'mosaicml/mpt-7b'  I was able to start the training loop within the same env, just getting Cuda OOM for obvious reasons, so its safe to assume that there's nothing wrong with the env or with any library installations.

**Comment by issaca** [comment]
I am encountering the same issue as described by atharvou23 when trying to finetune the mpt-1b-redpajama-200b model. I tried to override (attn_config: {'attn_impl': 'torch', 'attn_uses_sequence_id': False}) but then I am getting the flowing error:
AttributeError: 'ModuleDict' object has no attribute 'get_input_embeddings'
Is there a workaround or a recommended finetuning config?
