### ISSUE TITLE
ERROR: Could not build wheels for flash-attn, triton-pre-mlir, xentropy-cuda-lib, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by ryurobin1990** [mosaicml/llm-foundry#256]
Hi team could you help me on this error? Thanks!

```
docker pull mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04

python -m venv llmfoundry-venv
source llmfoundry-venv/bin/activate

docker run mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04

pip install -U pip

pip install torch==1.13.1
pip install packaging

pip install -e ".[gpu]" 
```

System info:
Python 3.10
cuda 1.17 
torch 1.13.1 
Ubuntu 20.04 
GPU H100

**Comment by vchiley** [comment]
In your System info, you have 
```
GPU H100
CUDA 11.7
torch==1.13.1
```

H100 support was added to CUDA 11.8 and torch==2.0.0 is the first torch to formally support CUDA 11.8
See [GPUs supported section](https://en.wikipedia.org/wiki/CUDA)
your system info is problematic.

**Comment by ryurobin1990** [comment]
Thanks I tried with A100 machine and still not working so I used the answer here and it worked https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory
Later I got issue the same as https://github.com/mosaicml/llm-foundry/issues/62 but work around by adding flag `model.loss_fn=torch_crossentropy`

**Comment by ryurobin1990** [comment]
Ok I think you already answered this question here, because torch 2.0.1 got auto installed https://github.com/mosaicml/llm-foundry/issues/228
