### ISSUE TITLE
any way to log some features in wandb?

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#257]
You are logging something in `wandb`

For example, I want add `grad_norm`

You are using `grad_norm` from `composer.algorithms`, so I must to log this inside `Trainer` something like `wandb.log(self.state.algorithms.grad_clipping.grad_norm`? Looks not really comfortable, maybe you have some options to upgrade your `wandb` by myself just in `cfg`?

**Comment by abhi-mosaic** [comment]
The Composer Trainer has [a Callback system](https://docs.mosaicml.com/projects/composer/en/stable/trainer/callbacks.html) that lets you write custom logging code that operates upon different events (like before optimizer step, or after dataloader, etc.). If you'd like to write your own callback, you can [register it in `builders.py`](https://github.com/mosaicml/llm-foundry/blob/main/llmfoundry/utils/builders.py#L33) or just directly add the callback [in the `train.py` script.](https://github.com/mosaicml/llm-foundry/blob/3c66b1c5df668e0684548fef30d00669df64636c/scripts/train/train.py#L184-L187)

For specifically `grad_norm`, there is an even easier way -- just use our OptimizerMonitor [which is already registered as an option](https://github.com/mosaicml/llm-foundry/blob/3c66b1c5df668e0684548fef30d00669df64636c/llmfoundry/utils/builders.py#L46-L48) in `builders.py`.

In your YAML you can just do:
```
callbacks:
  optimizer_monitor:
    log_optimizer_metrics: true
```

**Comment by germanjke** [comment]
@abhi-mosaic thanks!

```
callbacks:
  optimizer_monitor:
    log_optimizer_metrics: true
```
is great, but sometimes it's so many graphics, for example, how can I put only `l2_norm/grad/global`?
