### ISSUE TITLE
batch size with tokens

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#262]
can we use batch size with number of tokens and not just int?
for example, I want to use batch size 1M tokens, is it possible?
something like `bs=1000000ba`?

**Comment by vchiley** [comment]
[`global_train_batch_size`](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/pretrain/mpt-7b.yaml#L77) sets the training batch size (in samples)
There is no good way to set it using tokens, but if you are using a seq len of 2000, and want 1M token count, you'd set the batch size to be 1e6//2000 = 500
```
global_train_batch_size: 500ba
```

**Comment by germanjke** [comment]
`global_train_batch_size: 256` (without `ba`) means how much tokens with seq len 2000? can you provide formula please

**Comment by vchiley** [comment]
sorry my last comment had `ba` when it shouldn't have
`global_train_batch_size` is the number of samples per batch
In your example if each sample has seq len 2000, then with `global_train_batch_size: 256` (samples) your batch size in tokens is 256 * 2000 = 512,000
