### ISSUE TITLE
125M 2.5B tokens recomendation

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#263]
Do you recommend train mpt125 only with `4800 ba`? After this it's will be overfitting?

If i set up `max_duration` to `2ep`, 1 epoch is ~15000 batches in my dataset (`global batch size 256`), I think 4800 is not enough here?

**Comment by vchiley** [comment]
Using `max_seq_len: 2048` and `global_train_batch_size: 256`, `4800ba` is the [chinchilla](https://arxiv.org/abs/2203.15556) optimal step count.
You should feel free to adjust as you see fit.

Note: Chinchilla paper says 7B model should be trained for about 140B tokens, we trained it for 1T tokens for the MPT-7B release.

**Comment by germanjke** [comment]
yes, chinchilla looks good and I try to train something like this

I want to know difference between `1ep` and `xxx ba`

1) I'm right that if my `1ep` is auto transfers to 15k batches, it means something like 7.5 B tokens?

2) but if I'm using `4800ba` it's means I will train my model only on 1/3 dataset 1 epoch?

**Comment by germanjke** [comment]
do you think after `4800ba` 125m model can do some correct inference and not random words?

**Comment by vchiley** [comment]
🤷‍♂️ 
`125m` is an **extremely** small model.

**Comment by germanjke** [comment]
I have some dramatic conclusions now.

Looks like `gpt-neo-small` gives me really good inferences (after ~3k steps), while `MPT` generates (after ~7k steps) something like random letters. 

I dont know, but I think it's some bugs in `MPT`, i'm pretraining this from zero.

**Comment by germanjke** [comment]
maybe it some problems with `triton attention` which using `MPT`
