### ISSUE TITLE
flash/triton attentions not for mpt models?

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#265]
are you support flash/triton attn for not mpt models (like gpt-neo-small)?

i can launch train with `attn_config: attn_impl: flash (or triton)`

but training time equals to `torch`, `mpt` works much faster

**Comment by vchiley** [comment]
`flash`, `torch`, and `triton` are attention implementations ([integrated here](https://github.com/mosaicml/llm-foundry/blob/main/llmfoundry/models/layers/attention.py))

If you want to use them in models such as gpt-neo-small, you'd need to update the model definition to use these attention implementations.
Modifying code from other repositories is outside of the scope of this repository.

My recommendation: MPT is all you need 😄

**Comment by germanjke** [comment]
so it means if I'm not change something outside of the scope of this repository, all `attn_impl` will same with `torch` in models such as gpt-neo-small?

**Comment by germanjke** [comment]
>My recommendation: MPT is all you need 😄

I would really like to do this, but after so many experiments with my loss exploding, I try another architectures right now haha, will see...
