### ISSUE TITLE
Config for MQA?

### ISSUE THREAD

**Issue by tginart** [mosaicml/llm-foundry#273]
I see there is MQA class: https://github.com/mosaicml/llm-foundry/blob/8f1593524af2b611091dc1f86ed2d2135adaec9f/llmfoundry/models/layers/attention.py#L443

## ❓ Question
Is this live via yaml or is this just there for future work?

**Comment by vchiley** [comment]
You can use this.
Setting `attn_config.attn_type='multiquery_attention` enables MQA.

**Comment by vchiley** [comment]
I have run this code using 125M, 350M, 760M, and 1B models with `attn_impl: triton`

**Comment by vchiley** [comment]
we also test the layer itself [here](https://github.com/mosaicml/llm-foundry/blob/main/tests/test_flash_triton_torch.py#LL20C26-L20C32)
