### ISSUE TITLE
Multi-Query Attention

### ISSUE THREAD

**Issue by bratao** [mosaicml/llm-foundry#287]
## Motivation

The competing LLM model, Falcon, incorporates a feature called Multi-Query Attention that enables better scalability for inference. 
They says here that their prediction speed and memory usage because of that is considerably better than MPT:
https://huggingface.co/blog/falcon

This feature shares keys and value embeddings across attention heads, reducing memory costs and allowing for novel optimizations such as statefulness. Since MPT currently does not have this capability, implementing MQA will enhance the performance and efficiency of the model, making it more competitive with other existing models like Falcon.

**Comment by vchiley** [comment]
The repo implements [MQA here](https://github.com/mosaicml/llm-foundry/blob/main/llmfoundry/models/layers/attention.py#L443).
[when we added it](https://github.com/mosaicml/llm-foundry/commit/39ae5eb64bc43687351bfda9b0ab368c4cca0bc2)

It can be enabled using the following configuration setting:
```
model:
  attn_config:
    attn_type: multiquery_attention
```

Note: MPT was trained using MHA not MQA.

**Comment by bratao** [comment]
Thanks @vchiley for the awesome MPT model, it is a very generous gift for the world. I´m not being a choosing begger here, I just want to get any insight if Mosaic is planning release new models and if so, there is a possibility of a MQA one?

**Comment by vchiley** [comment]
https://github.com/mosaicml/llm-foundry/issues/56#issuecomment-1537035367
