### ISSUE TITLE
Trouble getting output similar to https://huggingface.co/spaces/mosaicml/mpt-7b-instruct

### ISSUE THREAD

**Issue by MBAnslow** [mosaicml/llm-foundry#289]
## ❓ Question
I'm trying to use the mpt-7b-insruct model but I'm getting far inferior results to the demo model on https://huggingface.co/spaces/mosaicml/mpt-7b-instruct. 

I'm writing the same instruction in both interfaces using the structure from the repo:

```
INTRO_BLURB = "Below is an instruction that describes a task. Write a response that appropriately completes the request."
INSTRUCTION_KEY = "### Instruction:"
RESPONSE_KEY = "### Response:"

PROMPT_FOR_GENERATION_FORMAT = """{intro}
{instruction_key}
{instruction}
{response_key}
""".format(
    intro=INTRO_BLURB,
    instruction_key=INSTRUCTION_KEY,
    instruction="{instruction}",
    response_key=RESPONSE_KEY,
)

```

Where I replace the instruction with my instruction. The only difference I can guess at is that I'm using the torch.bfloat16 version of the model.

Am I doing something wrong or is the torch.bfloat16 version much inferior to the normal version of the model?

**Comment by samhavens** [comment]
We also use bfloat16, I do not think it is that. It is likely the kwargs you are (or are not) passing to `.generate`. The defaults are in [this block](https://huggingface.co/spaces/mosaicml/mpt-7b-instruct/blob/main/app.py#L157). You also may want to add [stopping criteria](https://huggingface.co/spaces/mosaicml/mpt-7b-instruct/blob/main/app.py#L100)
