### ISSUE TITLE
Finetuning with LoRA issue "TypeError: forward() got an unexpected keyword argument 'inputs_embeds'"

### ISSUE THREAD

**Issue by UmarJawad** [mosaicml/llm-foundry#304]
Hi!

I am trying to finetune MPT-7B with LoRA configurations.

# Model
model_name = "mosaicml/mpt-7b"
config = transformers.AutoConfig.from_pretrained(
    model_name,
    trust_remote_code=True
)

config.update({"max_seq_len": 4096})

model = AutoModelForCausalLM.from_pretrained(
    model_name, 
    trust_remote_code=True,
    torch_dtype=bfloat16,
    device_map='auto',
    config = config
) 

#Tokenizer
tokenizer = AutoTokenizer.from_pretrained('EleutherAI/gpt-neox-20b')

# Lora Config
config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=['Wqkv'],#["Wq","kv"], # splitting the Wqkv layer into smaller matrices
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM" # for causal text generation
)

model = get_peft_model(model, config)

# Trainer 

import transformers

tokenizer.pad_token = tokenizer.eos_token # add a pad token in the tokenizer

trainer = transformers.Trainer(
    model=model, 
    train_dataset=mapped_qa_dataset["train"],
    args=transformers.TrainingArguments(
        per_device_train_batch_size=4, 
        gradient_accumulation_steps=4,
        warmup_steps=100,
        max_steps=100,
        learning_rate=1e-3, 
        fp16=False, #set to true for float16
        logging_steps=1, 
        output_dir='outputs',
    ),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False)
)
model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
trainer.train()

# Error
But I keep getting this error:

File [~/.local/lib/python3.9/site-packages/peft/peft_model.py:707](https://vscode-remote+ssh-002dremote-002bgenai-002dg5-002c2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/generative-ai/genai/~/.local/lib/python3.9/site-packages/peft/peft_model.py:707), in PeftModelForCausalLM.forward(self, input_ids, attention_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict, **kwargs)
    705 peft_config = self.active_peft_config
    706 if not isinstance(peft_config, PromptLearningConfig):
--> 707     return self.base_model(
    708         input_ids=input_ids,
    709         attention_mask=attention_mask,
    710         inputs_embeds=inputs_embeds,
    711         labels=labels,
    712         output_attentions=output_attentions,
    713         output_hidden_states=output_hidden_states,
    714         return_dict=return_dict,
    715         **kwargs,
    716     )
    718 batch_size = input_ids.shape[0]
    719 if attention_mask is not None:
    720     # concat prompt attention mask

File [~/.local/lib/python3.9/site-packages/torch/nn/modules/module.py:1501](https://vscode-remote+ssh-002dremote-002bgenai-002dg5-002c2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/generative-ai/genai/~/.local/lib/python3.9/site-packages/torch/nn/modules/module.py:1501), in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File [~/.local/lib/python3.9/site-packages/accelerate/hooks.py:165](https://vscode-remote+ssh-002dremote-002bgenai-002dg5-002c2xlarge.vscode-resource.vscode-cdn.net/home/ec2-user/generative-ai/genai/~/.local/lib/python3.9/site-packages/accelerate/hooks.py:165), in add_hook_to_module..new_forward(*args, **kwargs)
    163         output = old_forward(*args, **kwargs)
    164 else:
--> 165     output = old_forward(*args, **kwargs)
    166 return module._hf_hook.post_forward(module, output)

TypeError: forward() got an unexpected keyword argument 'inputs_embeds'

**Comment by fozziethebeat** [comment]
I have LoRA fine tuning working (literally right now) but I'm using the `mosaicml/mpt-7b` tokenizer.  Why are you using the `EleutherAI/gpt-neox-20b` tokenizer?  Can you change that and see if it works? Also, I am naively setting up my LoRA config to use `target_modules=None`.  I can't confirm results with this yet but it's at least training and showing expected loss functions.

**Comment by alextrott16** [comment]
We just added support for peft/lora with mpt models, including adding the `inputs_embeds` argument to the forward method so that this issue doesn't occur. Merged the PR today.

That should solve the immediate problem, so I'll close this issue. Feel free to re-open if you run into new problems or bugs.
