### ISSUE TITLE
Does triton-pre-mlir support cu11.6？

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#305]
**My environment is py3.10+pytorch1.13.1+cu11.6. When installing triton-pre-mlir, I encountered the following error**

![image](https://github.com/mosaicml/llm-foundry/assets/133207026/6dd98d04-d748-4484-b60f-045729938d77)

**Comment by vchiley** [comment]
Not sure. We haven't tested on cu11.6 (setting in [support matrix](https://github.com/mosaicml/llm-foundry#hardware-and-software-requirements) have been tested)
