### ISSUE TITLE
MPT-7B0-Instruct Demo Broken - Out of Memory Error

### ISSUE THREAD

**Issue by MBAnslow** [mosaicml/llm-foundry#315]
The web demo on Hugging Face isn't working. There seems to be an OOM error on loading the model.

## Environment

Web demo on Hugging Face.

## To reproduce

Got to https://huggingface.co/spaces/mosaicml/mpt-7b-instruct

## Expected behavior

Demo should be running as usual.

## Additional context

<img width="1472" alt="Screenshot 2023-06-12 at 10 28 18" src="https://github.com/mosaicml/llm-foundry/assets/33870221/2ab6f178-72ed-4f1b-ba2b-a018d30259c4">

**Comment by abhi-mosaic** [comment]
We are looking into it, thanks for raising!
