### ISSUE TITLE
No demo on Huggingface

### ISSUE THREAD

**Issue by Daniel-Kelvich** [mosaicml/llm-foundry#319]
Could you please provide the code to run inference on MPT models? Huggingface demo links return 404.

**Comment by samhavens** [comment]
We are making some changes to the HF Spaces. In the meantime, this [CLI Inference script](https://github.com/mosaicml/llm-foundry/blob/main/scripts/inference/hf_chat.py) has streaming generation and demonstrates using HuggingFace for inference.

For the instruct model, you'd call it with `--system_prompt "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n" --user_msg_fmt "\n###Instruction\n --assistant_msg_fmt "/n###Response\n"` — though be aware that it was only trained on one turn, so you may need to `clear` the history after each response.

If you are looking to do optimized inference, you can convert to FasterTransformer with [this script](https://github.com/mosaicml/llm-foundry/blob/main/scripts/inference/convert_hf_mpt_to_ft.py)
