### ISSUE TITLE
RuntimeError: expected scalar type BFloat16 but found Float

### ISSUE THREAD

**Issue by benam2** [mosaicml/llm-foundry#333]
I am using this code to fine tune https://colab.research.google.com/drive/1DqKNPOzyMUXmJiJFvJITOahVDxCrA-wA#scrollTo=wShqQoppuv-h

and I get this error, I use the G5 Ec2 instance machine **(A10)**.
In the code above when I change torch.bfloat16 to 32 I get the OOM error.
Is there anyway I can fix this using the same machine? Thanks for your time!

`RuntimeError                              Traceback (most recent call last)
File <command-412498178107004>:1
----> 1 trainer.train()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/transformers/trainer.py:1645, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1640     self.model_wrapped = self.model
   1642 inner_training_loop = find_executable_batch_size(
   1643     self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size
   1644 )
-> 1645 return inner_training_loop(
   1646     args=args,
   1647     resume_from_checkpoint=resume_from_checkpoint,
   1648     trial=trial,
   1649     ignore_keys_for_eval=ignore_keys_for_eval,
   1650 )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/transformers/trainer.py:1938, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1935     self.control = self.callback_handler.on_step_begin(args, self.state, self.control)
   1937 with self.accelerator.accumulate(model):
-> 1938     tr_loss_step = self.training_step(model, inputs)
   1940 if (
   1941     args.logging_nan_inf_filter
   1942     and not is_torch_tpu_available()
   1943     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   1944 ):
   1945     # if loss is nan or inf simply add the average of previous logged losses
   1946     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/transformers/trainer.py:2759, in Trainer.training_step(self, model, inputs)
   2756     return loss_mb.reduce_mean().detach().to(self.args.device)
   2758 with self.compute_loss_context_manager():
-> 2759     loss = self.compute_loss(model, inputs)
   2761 if self.args.n_gpu > 1:
   2762     loss = loss.mean()  # mean() to average on multi-gpu parallel training

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/transformers/trainer.py:2784, in Trainer.compute_loss(self, model, inputs, return_outputs)
   2782 else:
   2783     labels = None
-> 2784 outputs = model(**inputs)
   2785 # Save past state if it exists
   2786 # TODO: this needs to be fixed and made cleaner later.
   2787 if self.args.past_index >= 0:

File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File /databricks/python/lib/python3.10/site-packages/torch/nn/parallel/distributed.py:1040, in DistributedDataParallel.forward(self, *inputs, **kwargs)
   1036 if self._join_config.enable:
   1037     # Notify joined ranks whether they should sync in backwards pass or not.
   1038     self._check_global_requires_backward_grad_sync(is_joined_rank=False)
-> 1040 output = self._run_ddp_forward(*inputs, **kwargs)
   1042 # sync params according to location (before/after forward) user
   1043 # specified as part of hook, if hook was specified.
   1044 if self._check_sync_bufs_post_fwd():

File /databricks/python/lib/python3.10/site-packages/torch/nn/parallel/distributed.py:1000, in DistributedDataParallel._run_ddp_forward(self, *inputs, **kwargs)
    993     inputs, kwargs = _to_kwargs(
    994         inputs,
    995         kwargs,
    996         self.device_ids[0],
    997         self.use_side_stream_for_tensor_copies
    998     )
    999     with self._inside_ddp_forward():
-> 1000         return module_to_run(*inputs[0], **kwargs[0])
   1001 else:
   1002     with self._inside_ddp_forward():

File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File ~/.cache/huggingface/modules/transformers_modules/mosaicml/mpt-7b-instruct/85c1f1c201273bbfee661d4a2f8307c95f8956c9/modeling_mpt.py:255, in MPTForCausalLM.forward(self, input_ids, past_key_values, attention_mask, prefix_mask, sequence_id, labels, return_dict, output_attentions, output_hidden_states, use_cache)
    253 return_dict = return_dict if return_dict is not None else self.config.return_dict
    254 use_cache = use_cache if use_cache is not None else self.config.use_cache
--> 255 outputs = self.transformer(input_ids=input_ids, past_key_values=past_key_values, attention_mask=attention_mask, prefix_mask=prefix_mask, sequence_id=sequence_id, return_dict=return_dict, output_attentions=output_attentions, output_hidden_states=output_hidden_states, use_cache=use_cache)
    256 logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
    257 if self.logit_scale is not None:

File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File ~/.cache/huggingface/modules/transformers_modules/mosaicml/mpt-7b-instruct/85c1f1c201273bbfee661d4a2f8307c95f8956c9/modeling_mpt.py:195, in MPTModel.forward(self, input_ids, past_key_values, attention_mask, prefix_mask, sequence_id, return_dict, output_attentions, output_hidden_states, use_cache)
    193     all_hidden_states = all_hidden_states + (x,)
    194 past_key_value = past_key_values[b_idx] if past_key_values is not None else None
--> 195 (x, attn_weights, past_key_value) = block(x, past_key_value=past_key_value, attn_bias=attn_bias, attention_mask=attention_mask, is_causal=self.is_causal)
    196 if past_key_values is not None:
    197     past_key_values[b_idx] = past_key_value

File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File ~/.cache/huggingface/modules/transformers_modules/mosaicml/mpt-7b-instruct/85c1f1c201273bbfee661d4a2f8307c95f8956c9/blocks.py:36, in MPTBlock.forward(self, x, past_key_value, attn_bias, attention_mask, is_causal)
     34 def forward(self, x: torch.Tensor, past_key_value: Optional[Tuple[torch.Tensor]]=None, attn_bias: Optional[torch.Tensor]=None, attention_mask: Optional[torch.ByteTensor]=None, is_causal: bool=True) -> Tuple[torch.Tensor, Optional[Tuple[torch.Tensor]]]:
     35     a = self.norm_1(x)
---> 36     (b, attn_weights, past_key_value) = self.attn(a, past_key_value=past_key_value, attn_bias=attn_bias, attention_mask=attention_mask, is_causal=is_causal)
     37     x = x + self.resid_attn_dropout(b)
     38     m = self.norm_2(x)

File /databricks/python/lib/python3.10/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File ~/.cache/huggingface/modules/transformers_modules/mosaicml/mpt-7b-instruct/85c1f1c201273bbfee661d4a2f8307c95f8956c9/attention.py:201, in MultiheadAttention.forward(self, x, past_key_value, attn_bias, attention_mask, is_causal, needs_weights)
    199     query = self.q_ln(query).to(dtype)
    200     key = self.k_ln(key).to(dtype)
--> 201 (context, attn_weights, past_key_value) = self.attn_fn(query, key, value, self.n_heads, past_key_value=past_key_value, softmax_scale=self.softmax_scale, attn_bias=attn_bias, key_padding_mask=key_padding_mask, is_causal=is_causal, dropout_p=self.attn_dropout_p, training=self.training, needs_weights=needs_weights)
    202 return (self.out_proj(context), attn_weights, past_key_value)

File ~/.cache/huggingface/modules/transformers_modules/mosaicml/mpt-7b-instruct/85c1f1c201273bbfee661d4a2f8307c95f8956c9/attention.py:58, in scaled_multihead_dot_product_attention(query, key, value, n_heads, past_key_value, softmax_scale, attn_bias, key_padding_mask, is_causal, dropout_p, training, needs_weights, multiquery)
     56 if dropout_p:
     57     attn_weight = torch.nn.functional.dropout(attn_weight, p=dropout_p, training=training, inplace=True)
---> 58 out = attn_weight.matmul(v)
     59 out = rearrange(out, 'b h s d -> b s (h d)')
     60 if needs_weights:

RuntimeError: expected scalar type BFloat16 but found Float`

**Comment by alextrott16** [comment]
Have you managed to resolve this issue? It looks like this could just be an issue of casting to bfloat16 instead of fp32. You could check out the patterns in `llm-foundry/scripts/inference/hf_generate.py` to see examples of using autocast to do this.
