### ISSUE TITLE
Multi Node different rank checkpoints

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#339]
For example, if I'm training on 2 nodes, should I have checkpoints both 0 and 1 rank?

I have `save_filename: ep{epoch}-ba{batch}-rank{rank}.pt`

But checkpoints saving only for node 0 with rank 0, do you know how I should have 1 rank? 

And here same question about inference, how to inference ckpts from multi node training?

**Comment by dakinggg** [comment]
If you are using `fsdp_state_dict_type: full`, you will just have one checkpoint. If you are using `fsdp_state_dict_type: sharded`, you will have multiple. Please reopen if you still have questions.
