### ISSUE TITLE
MosaicML commands with S3

### ISSUE THREAD

**Issue by ashoksmavd** [mosaicml/llm-foundry#340]
I have try to implement MPT-7b-chat based on MosaicML platform. 
I have executed the first step to convert c4 data set to steaming type and store my shards files on s3 path, after that I have executed composer command to train my MPT-7B model with the shards stored under S3.
It's showing some errors.
I have change yaml file to commented the data local path,  - and provide data-remote path to execute its always says index.json file took too long to download, bailing out.

--Any one help me out with this. I need to execute the composer command with my shards on s3

**Comment by codestar12** [comment]
HI ashoksmavd,

Can you provide your yaml so I can have a look?

**Comment by ashoksmavd** [comment]
hi @codestar12 

Here I have attached my yaml file. 

[mpt-7b.txt](https://github.com/mosaicml/llm-foundry/files/11777999/mpt-7b.txt)

**Comment by codestar12** [comment]
Have you double checked the correctness of your s3 path and aws permissions? I was going to take a look at how you formated your s3 path but I assume you kept it generic for privacy reasons.

**Comment by hanlint** [comment]
Closing as stale -- please re-open if you continue to have issues!
