### ISSUE TITLE
install error about trition-pre-mlir 

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#344]
A100+40G

![image](https://github.com/mosaicml/llm-foundry/assets/133207026/398b98df-f027-4dc9-93b4-a0d0375a25e6)

**Comment by vchiley** [comment]
Sorry, I have not seen this error before and do not know how to help.
Are you still having this issue?

**Comment by sysusicily** [comment]
> 

"Yes, I don't know how to solve it. I can only use attn_impl:flash, can't use triton."

**Comment by sysusicily** [comment]
> Sorry, I have not seen this error before and do not know how to help. Are you still having this issue?

"Yes, I don't know how to solve it. I can only use attn_impl:flash, can't use triton."

**Comment by DARK-HARK** [comment]
I also meet this question, and I have given up. But I success with the Docker.I think you can try the Docker

**Comment by hanlint** [comment]
Closing this issue as stale. Install issues with triton, we recommend trying with our docker image, or filing an issue with the triton library.

**Comment by DARK-HARK** [comment]
您好！      您的来信已收到。顺祝：身体健康，一切顺利！
