### ISSUE TITLE
Feature Request: Support for tokenizers requiring `trust_remote_code=True`

### ISSUE THREAD

**Issue by matthiasgeihs** [mosaicml/llm-foundry#355]
## 🚀 Feature Request
Support for custom tokenizers that require `trust_remote_code=True` (e.g., the Replit tokenizer).

## Motivation
 Currently, when using a tokenizer that requires `trust_remote_code=True`, the scripts `train.py` and `convert_composer_to_hf.py` fail (see https://github.com/mosaicml/llm-foundry/issues/163, https://github.com/mosaicml/llm-foundry/issues/176) and manual adaptations are necessary to make them work. It would be nice if these things just worked out of the box and a corresponding `trust_remote_code` option for tokenizers would exist in the config.

**Comment by alextrott16** [comment]
Hi, I believe `train.py` and any other script that uses the `build_tokenizer` builder will provide the opportunity to set `trust_remote_code=True` via the YAML.

For example, you would add this as a kwarg in the `tokenizer` section of the training YAML.
```
tokenizer:
  name: mosaicml/mpt-7b
  kwargs:
    model_max_length: 2048
    trust_remote_code: true
```

Admittedly, I am less sure about whether this will solve any problems related to `convert_composer_to_hf.py`, but the linked issues seemed to suggest that conversion itself was working but the problem occurred when trying to use `AutoTokenizer.from_pretrained(...)` to build from the model that was uploaded to the HF hub when running the conversion script. Building from custom code uploaded to the HF hub requires allowing for remote code: `AutoTokenizer.from_pretrained(..., trust_remote_code=True)`, but that requirement comes from the `transformers` package, so we're forced to follow that convention.

Please let me know if this sounds reasonable or if I've misunderstood your feature request.

**Comment by matthiasgeihs** [comment]
Hey, thanks for the response. I think my issue description and the issue references might have been a bit misleading in relation to the problem that I was actually encountering.

More concretely, my issue was that for finetuning the Replit Code model, there are some manual steps to be taken care of:
- `convert_dataset_hf.py`: Need to manually edit the file to set `trust_remote_code=True` when loading the tokenizer. (See also https://github.com/replit/replitLM#1-convert-and-save-your-dataset.)
- `train.py`: Need to manually edit the file to set `model.tokenizer = None` to avoid an issue with storing checkpoints. (See also https://github.com/replit/replitLM#3-running-training-with-llm-foundry-and-composer.)
- `convert_composer_to_hf.py`: This is basically the same issue as with `convert_dataset_hf.py`. We need to manually edit the file to set `trust_remote_code=True` when loading the tokenizer.

It would be nice if these scripts could be used for training the Replit model without any manual edits.

**Comment by alextrott16** [comment]
Thanks for clarifying the ask! Points 1 and 3 should be pretty straightforward, but addressing point 2 might be trickier.

**Comment by dakinggg** [comment]
I believe this has been resolved for a while. Please feel free to open a new issue if still encountering issues!
