### ISSUE TITLE
Question: Is the HF inference speed the same as MosaicML API inference?

### ISSUE THREAD

**Issue by SinanAkkoyun** [mosaicml/llm-foundry#361]
## ❓ Question

Is the HF inference speed the same as MosaicML API inference? (regarding starter and enterprise inference solutions)

**Comment by abhi-mosaic** [comment]
Hi @SinanAkkoyun , we have recently added some guidance on inference performance under [inference/benchmarking.](https://github.com/mosaicml/llm-foundry/tree/main/scripts/inference/benchmarking) These numbers can help calibrate on generation latency for **the MPT model alone** with fixed batch sizes, seq len, # GPUs etc. But these are **not** the same speed as our commercial inference platform.

The [MosaicML Inference](https://www.mosaicml.com/inference) service is a lot more optimized and we have different benchmarks there such as p90, p99 latency, and throughput in requests/sec under variable load. If you'd like more info or would like to try out our service as a customer, [reach out to us here!](https://www.mosaicml.com/get-started?utm_source=inference&utm_medium=mosaicml.com&utm_campaign=always-on)
