### ISSUE TITLE
HumanEval Benchmark

### ISSUE THREAD

**Issue by L1aoXingyu** [mosaicml/llm-foundry#362]
## 🚀 Feature Request

I found there is only ICL Benchmark in eval folder, but the HumanEval Benchmark is reported in MPT-30B. I want to reproduce the HumanEval results with llm-foundry.

So I just want llm-foundry integrated with HumanEval Benchmark.

**Comment by bmosaicml** [comment]
Hi! We are working on integrating HumanEval into the current coding suite. Thank you for your patience while we do so :)

**Comment by L1aoXingyu** [comment]
@bmosaicml hi, I want to train codeLLM using llm-foundry, any tutorial or docs about it? Thank you so much!

**Comment by dakinggg** [comment]
This has been merged in #587
