### ISSUE TITLE
Bug with s3 ckpt saving to s3

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#363]
```
save_folder: s3://my_bucket/path/to/ckpts/{run_name}
save_filename: ep{epoch}-ba{batch}-rank{rank}.pt
```
with this config my ckpts are saving for my s3 good, but as well they are writing to my local directory to `path/to/ckpts/{run_name}`

I guess its some bug in composer?

**Comment by germanjke** [comment]
@eracah hi thanks, but whole ckpts will be saving to the s3?
i'm using `save_num_checkpoints_to_keep: 1`, will try to 0 this

**Comment by eracah** [comment]
Yes! checkpoints will be saved and then uploaded to S3 every `save_interval` batches

**Comment by germanjke** [comment]
thanks!

**Comment by eracah** [comment]
Ok great closing this! Lmk if you have any further issues!
