### ISSUE TITLE
Inference Speed Benchmark

### ISSUE THREAD

**Issue by RaiAmanRai** [mosaicml/llm-foundry#375]
## ❓ Question

Hi, I am looking for the matric to compare the inference speed of the 7B, 13B and 70B models. More precisely I am looking for something like  "X Tokens/sec" on "M x N Type GPUs".

**Comment by sashaDoubov** [comment]
This has just been added for MPT-7B and 30B. Please see the benchmarking [README](https://github.com/mosaicml/llm-foundry/blob/main/scripts/inference/benchmarking/README.md) for details.

**Comment by float-trip** [comment]
This might explain the poor performance that you found for Falcon: https://news.ycombinator.com/item?id=36377873. Their code on HuggingFace hasn't been updated since that comment, so I'm assuming it's still relevant.

**Comment by sashaDoubov** [comment]
I saw the hacker news thread as well, and tried to see if the mentioned changes account for the slower performance by making a few changes in Falcon's modelling file to see how they affect inference speed:
- removing rotary embeddings
- replacing torch's `scaled_dot_product_attention` with torch ops

While I did see some improvements, it was still significantly slower than both LLAMA and MPT. 

The Falcon-7b uses non-standard linear layer dimensions, but I hesitate to pinpoint a precise reason for the slower performance given that I am not as familiar with their implementation as MPT's. 

If you do find a solution for the inference speed, please let us know!
