### ISSUE TITLE
AssertionError: Different ranks have different values for step.

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#376]
checkpoints continuous training, when re-saving, this error occurs

![image](https://github.com/mosaicml/llm-foundry/assets/133207026/145100da-f40f-4de1-9ffb-c7b8b3ba67ff)

**Comment by alextrott16** [comment]
Could you please add more context about where you're encountering this error?

**Comment by hanlint** [comment]
Please re-open if you have more details on how to reproduce the error, thanks!
