### ISSUE TITLE
Fine tuning on A10 GPUs

### ISSUE THREAD

**Issue by singhalshikha518** [mosaicml/llm-foundry#377]
## ❓ Question
Fine tuning of MPT-7B failing on A10 GPUs... Can you help with a script for the same

**Comment by alextrott16** [comment]
Can you provide some extra information about what is failing? If you're running into memory issues, I recommend lowering `device_train_microbatch_size`.

**Comment by alextrott16** [comment]
We recently added `TUTORIAL.md` to the top-level directory, which includes a FAQ section that has questions about compute requirements and dealing with OOMs.

Feel free to re-open this issue if that doesn't resolve things for you.
