### ISSUE TITLE
convert dataset directly to s3?

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#378]
`scripts/data_prep/convert_hf.py` need `out_root` argument and saves the converted streaming dataset to local machine, can we define s3 remote here to avoid local machine space?

**Comment by codestar12** [comment]
I'm pretty sure you can use an s3 remote for out_root. If it gives feel free to open a new issue.

**Comment by germanjke** [comment]
true its worked with `streaming` >= 0.5.0
