### ISSUE TITLE
ratio of streaming to hf datasets?

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#381]
I'm trying to convert c4 dataset from your `convert_hf` code

[here](https://huggingface.co/datasets/allenai/c4) they say `en` subset is 305 Gb

but if I'm give `c4` and `en` as arguments, it looks like dataset is bigger? already 1.1 TB and it still going, maybe we download `en.noclean: 2.3TB` this version?

**Comment by germanjke** [comment]
converted dataset is 1.3 TB, but i want to know what size is this of not streaming, but hf format

**Comment by germanjke** [comment]
question is streaming dataset == hf dataset by size? or how many times is difference?

**Comment by germanjke** [comment]
so 305 Hugging Face = ~ 1.3 TB streaming
also I have same observe with `c4` `realnewslike`, which is 15 GB at HF and ~65 GB in streaming
does it means that 1 HF Mb = 4 Streamyng Mbs?

**Comment by germanjke** [comment]
@karan6181

**Comment by knighton** [comment]
You can also specify a compression level to zstd (it defaults to 3, but can go up to 22), for example `zstd:10`
