### ISSUE TITLE
MPT-7b and 30B in HF aren't compatible with HF's PEFT because forward function is missing `inputs_embeds` arg

### ISSUE THREAD

**Issue by ibeltagy** [mosaicml/llm-foundry#382]
The HF standard `forward` function expects an `inputs_embeds` argument. 

The PEFT library is using it here https://github.com/huggingface/peft/blob/f5352f08c593503a442f4438e1c7e648377b6a4b/src/peft/peft_model.py#L852

but the MPT implementation here https://huggingface.co/mosaicml/mpt-7b/blob/main/modeling_mpt.py#L262 is missing it, so it crashes with PEFT.

**Comment by codestar12** [comment]
hey @ibeltagy we will address this later today. the code _just_ got merged in and we have to put a PR in to HF.

**Comment by alextrott16** [comment]
Changes have been merged into the HF code, so I'm going to close this issue. Please re-open if needed.

**Comment by sasaadi** [comment]
When I use the HF model and code, I get this error: 

> File "modeling_mpt.py", line 271, in forward
>     logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
> File "anaconda3/envs/peft/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
>     result = forward_call(*input, **kwargs)
> TypeError: forward() takes 2 positional arguments but 3 were given

Does anyone have any ideas? should I change the forward() function arguments in modeling_mpt.py?
Thanks

**Comment by sylee0520** [comment]
> When I use the HF model and code, I get this error:
> 
> > File "modeling_mpt.py", line 271, in forward
> > logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
> > File "anaconda3/envs/peft/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
> > result = forward_call(*input, **kwargs)
> > TypeError: forward() takes 2 positional arguments but 3 were given
> 
> Does anyone have any ideas? should I change the forward() function arguments in modeling_mpt.py? Thanks

I think 'unembed' argument makes trouble. So, fix the 'SharedEmbedding' class in custom_embedding.py.

**Comment by sasaadi** [comment]
> > When I use the HF model and code, I get this error:
> > > File "modeling_mpt.py", line 271, in forward
> > > logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
> > > File "anaconda3/envs/peft/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
> > > result = forward_call(*input, **kwargs)
> > > TypeError: forward() takes 2 positional arguments but 3 were given
> > 
> > 
> > Does anyone have any ideas? should I change the forward() function arguments in modeling_mpt.py? Thanks
> 
> I think 'unembed' argument makes trouble. So, fix the 'SharedEmbedding' class in custom_embedding.py.

Thanks. 
I changed
> def forward(self, input: Tensor, unembed: bool=False) -> Tensor:

to 

> def forward(self, input: Tensor, unembed: bool) -> Tensor:

in my local file custom_embedding.py and my cache files are also updated accordingly. To my suprise, it still gives exactly the same error in this line in modeling_mpt.py:

> logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)

and when I change this line to (given the original SharedEmbedding class):

> logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), unembed=True)

I get this error:

> TypeErrorTypeError: forward() got an unexpected keyword argument 'unembed'

Do you have any ideas why this happens?

**Comment by sylee0520** [comment]
> > > When I use the HF model and code, I get this error:
> > > > File "modeling_mpt.py", line 271, in forward
> > > > logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
> > > > File "anaconda3/envs/peft/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
> > > > result = forward_call(*input, **kwargs)
> > > > TypeError: forward() takes 2 positional arguments but 3 were given
> > > 
> > > 
> > > Does anyone have any ideas? should I change the forward() function arguments in modeling_mpt.py? Thanks
> > 
> > 
> > I think 'unembed' argument makes trouble. So, fix the 'SharedEmbedding' class in custom_embedding.py.
> 
> Thanks. I changed
> 
> > def forward(self, input: Tensor, unembed: bool=False) -> Tensor:
> 
> to
> 
> > def forward(self, input: Tensor, unembed: bool) -> Tensor:
> 
> in my local file custom_embedding.py and my cache files are also updated accordingly. To my suprise, it still gives exactly the same error in this line in modeling_mpt.py:
> 
> > logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
> 
> and when I change this line to (given the original SharedEmbedding class):
> 
> > logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), unembed=True)
> 
> I get this error:
> 
> > TypeErrorTypeError: forward() got an unexpected keyword argument 'unembed'
> 
> Do you have any ideas why this happens?

I newly create class 'SharedEmbedding2' like this, and set the 'self.wte2 = SharedEmbedding2(YOUR_ARGUMENTS)' in class 'MPTModel'.
`class SharedEmbedding2(nn.Embedding):
    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight)`
