### ISSUE TITLE
Config YAML maps syntax

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#386]
In your script, you can use some values in another, like [here](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/pretrain/mpt-125m.yaml#L80)

How I can use value with tabulation?

I want make something like `run_name: ${max_seq_len}_${model.name}`, in this example `max_seq_len`goes fine, but `model.name` is not, some another syntax?

**Comment by alextrott16** [comment]
We're essentially just doing this in our scripts:
```python
from omegaconf import OmegaConf
cfg = OmegaConf.load('/path/to/yaml')
```
So, I recommend going through the OmegaConf docs to see what kind of patterns are supported. 

From [this](https://omegaconf.readthedocs.io/en/2.0_branch/usage.html#config-node-interpolation), it seems like you should be able to do something like you're describing. To test, I made this YAML as `tester.yaml`:
```yaml
max_seq_len: 2048

# Run Name
run_name: ${max_seq_len}_${model.name}

# Model
model:
  name: mpt_causal_lm
```
And from running these lines (printouts included) it seems like you should be getting the behavior you'd expect:
```python
>>> from omegaconf import OmegaConf as om
>>> cfg = om.load('tester.yaml')
>>> cfg
{'max_seq_len': 2048, 'run_name': '${max_seq_len}_${model.name}', 'model': {'name': 'mpt_causal_lm'}}
>>> cfg.run_name
'2048_mpt_causal_lm'
```

Let me know if this does not line up with what you're seeing.

**Comment by germanjke** [comment]
thanks, it's works
