### ISSUE TITLE
Easiest way to add some benchmarks into eval pretrain?

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#390]
Hi, you have good `benchmarks` in `scripts` stage, do we can somehow change config in `pretrain` to add some benchmarks in eval stage? Like winograd. And draw them at W&B

Thanks

**Comment by germanjke** [comment]
@vchiley

**Comment by dakinggg** [comment]
The `icl_tasks` yaml [section](https://github.com/mosaicml/llm-foundry/blob/2f49eb7fa0486acf1d6c09ed90c8856ccdc31b4a/scripts/eval/yamls/mpt_eval.yaml#L36-L43) that configures ICL evaluation can be added to training yamls as well.
