### ISSUE TITLE
Can MPT-7b be loaded with gradient_checkpointing in HF transformers

### ISSUE THREAD

**Issue by aniketb-verneek** [mosaicml/llm-foundry#399]
## ❓ Question
Can `mpt-7b` models be fine-tuned with HuggingFace trainer class using `gradient_checkpointing` set to `True`. Presently, I get the following error if I try to fine-tune `mpt-7b` model with the HuggingFace trainer class with `gradient_checkpointing` set to True.

```
ValueError: MPTForCausalLM does not support gradient checkpointing.
```

If I otherwise try to use `model.gradient_checkpointing_enable()`, I get the same error:

## Additional context
These are the versions of the packages that my environment is using:
```
Torch: 1.13.1
Transformers: 4.26.0
```
I was trying to train the model with 8xA100 GPUs. And, without gradient_checkpointing, I keep getting OOM error for `bf16` precision as well. Let me know if anyone has an idea on how to run MPT-7b in HuggingFace with gradient checkpointing.

**Comment by alextrott16** [comment]
LLM Foundry is built around the Composer trainer, which broadly supports gradient checkpointing via FSDP. If you look at the example YAML configs in `scripts/train/yamls/` (specifically the `fsdp_config` section), you'll see that we also find gradient checkpointing to be required for training models of this scale.

So, `mpt-7b` can be trained with activation checkpointing if you go through this repo, which we encourage you to do :)
But, no, it is not currently set up to do the same with the Huggingface trainer.

Flagging @vchiley and @dakinggg in case they plan to add support for this at some point.

**Comment by dakinggg** [comment]
Closing as we do not plan to resolve this. There are other MPT implementations out there at this point that support gradient checkpoint + the huggingface trainer.
