### ISSUE TITLE
S3 Config to train.py?

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#403]
It's good way in `streaming` that we can define s3 paths to `load_path`, `dataset`, `save_folder` etc

whats about use same in `scripts/train.py` for config file?

like `train.py s3://configs/mpt-125m.yaml`?

I discovered now you don't support this if I'm not wrong

**Comment by alextrott16** [comment]
You are correct that we do not currently support this pattern.

You could modify the script to pull from s3 (or another supported cloud provider) by having it use the `get_file` helper (import via `from composer.utils.file_helpers import get_file`).

Alternatively, you can achieve the same thing via something like:
```bash
pip install awscli
aws s3 cp s3://configs/mpt-125m.yaml local-mpt-125m.yaml
composer train.py local-mpt-125.yaml
```
