### ISSUE TITLE
HF Optimum Inference on MPT-7B ONNX Not working

### ISSUE THREAD

**Issue by zacharyblank** [mosaicml/llm-foundry#415]
Using composer I have fine tuned MPT-7B-storywriter, converted the model to Huggingface then converted that to ONNX.

I'd like to use Optimum to run inference on the ONNX model but the ONNX model that is created is not compatible with what Optimum is expecting.

Alternatively I have tried to use Optimum to convert the model but the "architecture is not yet supported".

Anybody have any converting a composer model to ONNX and using Optimum to run inference?

**Comment by hanlint** [comment]
Hi @zacharyblank , I think this issue is better raised in the optimum library, to ask them to support MPT model architecture?

**Comment by dakinggg** [comment]
Closing this as it is better suited for the optimum library (and I see you opened an issue over there)
