### ISSUE TITLE
Create a chat bot using my own articles

### ISSUE THREAD

**Issue by ashoksmavd** [mosaicml/llm-foundry#418]
Hi Everyone,
I have a news website having more than 1 lkh articles. I wish to create a chat bot that gives answers from my articles.
I'm looking for MPT-7B for achieving this. can anyone provide the road map I want to follow for my goal on this?

**Comment by hanlint** [comment]
Hello @ashoksmavd , if you are looking to fine-tune, I would start with our fine-tune tutorial here: https://github.com/mosaicml/llm-foundry/tree/main/scripts/train
