### ISSUE TITLE
Convert sharded checkpoints to HF checkpoints

### ISSUE THREAD

**Issue by sasaadi** [mosaicml/llm-foundry#419]
## ❓ Question
Hi all, I want to convert a sharded checkpoint of MPT-7B to HF checkpoint.
I have trained the model on 8 x A100 gpus.
When I run the following call:

```
python scripts/inference/convert_composer_to_hf.py \
  --composer_path checkpoints/ep10-ba50000/ep10-ba50000-rank0.pt \
  --hf_output_path hf_checkpoints \
  --output_precision bf16 \
```

 It prints this output:
Downloading checkpoint from checkpoints/ep10-ba50000/ep10-ba50000-rank0.pt -> /tmp/1321198/tmp9dxylpr8/local-composer-checkpoint.pt
Loading checkpoint into CPU RAM...

and then this error:
"RuntimeError: Need to initialize default process group using "init_process_group" before loading ShardedTensor"

I get the same error with composer instead of python.

Do you have any ideas how to convert sharded checkpoints to HF checkpoints?
Thanks

**Comment by eracah** [comment]
Hi @sasaadi, unfortunately you can't convert sharded checkpoints to huggingface checkpoints at the moment; you can only convert monolithic ones. Were you able to get the monolithic checkpoint saver callback to generate a monolithic checkpoint at any point?

**Comment by shunk031** [comment]
Hi, I ran into a similar situation and I realized from @eracah's comment that I should use [`MonolithicCheckpointSaver`](https://github.com/mosaicml/llm-foundry/blob/main/llmfoundry/callbacks/monolithic_ckpt_callback.py). Is this a correct decision?

I have added additional settings to the yaml file based on [finetune/mpt-7b_domain_adapt.yaml](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/finetune/mpt-7b_domain_adapt.yaml) as follows:
```yaml
...

callbacks:
  ...

  mono_ckpt_saver:
    save_folder: /path/to/mono_checkpoints
    batch_interval: 1

...
```

However, under the distributed training environment, the following error occurred:
```
[E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2272, OpType=_ALLGATHER_BASE, Timeout(ms)=600000) ran for 604796 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2272, OpType=_ALLGATHER_BASE, Timeout(ms)=600000) ran for 604796 milliseconds before timing out.

----------End global rank 3 STDERR----------
ERROR:composer.cli.launcher:Global rank 0 (PID 68192) exited with code -6
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 132] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2272, OpType=_ALLGATHER_BASE, Timeout(ms)=600000) ran for 605746 milliseconds before timing out.
```

I would appreciate any advice you can give me.

**Comment by dakinggg** [comment]
Closing as the original question has been answered. @shunk031 please open a new issue if you are still encountering problems.
