### ISSUE TITLE
Lora Fine tuning on two different datasets

### ISSUE THREAD

**Issue by benam2** [mosaicml/llm-foundry#425]
Thanks for the great documentation on how to use this repo. 
I want to Lora fine tune the Mpt-7b-Instruct model on both OpenAssistant dataset (chat conversation) and Alpaca dataset. Fine tuning on alpaca should be fine since it has the format of prompt/response.

How can I handle the conversation here? Appreciate any suggestion.. If I split a conversation to multiple messages it misses the context. I want to have a model that is good on both chat and instruction..

**Comment by benam2** [comment]
any help on this please?

**Comment by divyanshuaggarwal** [comment]
I am interested in this too.

**Comment by tbarton16** [comment]
Hi @benam2 is your question about how to use LoRA or about how to combine 2 datasets? I am on the data team, and for data formatting of conversations for autoregressive language modeling, my suggestion is to split each conversation in half. For example: 
 `Person 1: Hi
Person 2: How are you?
Person 1: I'm fine `
prompt
 `Person 1: Hi
Person 2: How are you?
Person 1:`
response:
`I'm fine`
You can choose a random line to split at. One thing to watch out for is where the space after the first segment gets split. GPT style models have the prompt end with no space, and responses to start with a space.
