### ISSUE TITLE
can we leverage DeepSpeed ZeRO for MPT models?

### ISSUE THREAD

**Issue by guoyejun** [mosaicml/llm-foundry#431]
I see some code about deepspeed in https://github.com/mosaicml/composer, so just wonder how we can leverage DeepSpeed ZeRO  for MPT models?  If yes, is there any doc/code to read? thanks.

For example, I want to train an MPT-125m model (from https://github.com/mosaicml/llm-foundry/tree/main#quickstart, also copy below) with DeepSpeed ZeRO stage 3, what change should I make, the command line parameter, or the content of train.py or something else? thanks.

```
# Train an MPT-125m model for 10 batches
composer train/train.py \
  train/yamls/pretrain/mpt-125m.yaml \
  data_local=my-copy-c4 \
  train_loader.dataset.split=train_small \
  eval_loader.dataset.split=val_small \
  max_duration=10ba \
  eval_interval=0 \
  save_folder=mpt-125m
```

**Comment by vchiley** [comment]
[FSDP](https://pytorch.org/blog/introducing-pytorch-fully-sharded-data-parallel-api/) is the PyTorch native implimintation of the ZeRO algorithm (described [here](https://arxiv.org/abs/1910.02054)).
Our MPT training configs integrate it as can be seen eg [here](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/pretrain/mpt-7b.yaml#L87)

**Comment by guoyejun** [comment]
thanks @vchiley , due to some reasons, I also want to take a look at the DeepSpeed path, instead of FSDP in PyTorch, is there an easy way? thanks.

**Comment by vchiley** [comment]
Similar to how we pass an [FSDP config into Trainer](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/train.py#L288), [Trainer](https://docs.mosaicml.com/projects/composer/en/stable/api_reference/generated/composer.Trainer.html#trainer) also has a  deepspeed_config arg.

You can read about the FSDP config [here](https://docs.mosaicml.com/projects/composer/en/stable/notes/distributed_training.html#fullyshardeddataparallel-fsdp)
You can read about the deepspeed config [here](https://docs.mosaicml.com/projects/composer/en/stable/notes/distributed_training.html#deepspeed) with more detail [here](https://www.deepspeed.ai/docs/config-json/)

If configured correctly, it should work, but this isn't tested nearly as much.

**Comment by guoyejun** [comment]
thanks @vchiley ,  yes, I'm able to run with deepspeed now. Could you please help to take a look if my changes are correct? See https://github.com/guoyejun/llm-foundry/commit/ebdef6923e60fcc7551036b9c8da61ae3a9829ac (also copy below)

and another two questions:
1)  https://docs.mosaicml.com/projects/composer/en/stable/notes/distributed_training.html#deepspeed mentioned that only stage 1 and 2 are supported, is it out of date?
2)  I see the train time in the output, and how can I output the FLOPS for each GPU?

```
commit ebdef6923e60fcc7551036b9c8da61ae3a9829ac (HEAD -> debug, mine/deepspeed)
Author: Guo Yejun <yejun.guo@intel.com>
Date:   Sat Jul 8 20:53:42 2023 -0700

    disable FSDP and enable DeepSpeed ZeRO stage 3

diff --git a/scripts/train/train.py b/scripts/train/train.py
index a333bbe..740186e 100644
--- a/scripts/train/train.py
+++ b/scripts/train/train.py
@@ -160,6 +160,11 @@ def main(cfg):
     # Get batch size info
     cfg = update_batch_size_info(cfg)

+    # Read DeepSpeed Config as a dict
+    deepspeed_config = cfg.get('deepspeed_config', None)
+    deepspeed_config = om.to_container(deepspeed_config,
+                                  resolve=True) if deepspeed_config else None
+
     # Read FSDP Config as a dict
     fsdp_config = cfg.get('fsdp_config', None)
     fsdp_config = om.to_container(fsdp_config,
@@ -286,6 +291,7 @@ def main(cfg):
         device_train_microbatch_size=cfg.get('device_train_microbatch_size',
                                              'auto'),
         fsdp_config=fsdp_config,  # type: ignore
+        deepspeed_config=deepspeed_config,  # type: ignore
         save_folder=cfg.get('save_folder', None),
         save_filename=cfg.get('save_filename',
                               'ep{epoch}-ba{batch}-rank{rank}.pt'),
diff --git a/scripts/train/yamls/pretrain/mpt-125m.yaml b/scripts/train/yamls/pretrain/mpt-125m.yaml
index 1d4c1d9..dd33a9c 100644
--- a/scripts/train/yamls/pretrain/mpt-125m.yaml
+++ b/scripts/train/yamls/pretrain/mpt-125m.yaml
@@ -83,15 +83,15 @@ device_train_microbatch_size: 16
 # device_train_microbatch_size: auto
 precision: amp_bf16

-# FSDP
-fsdp_config:
-  sharding_strategy: FULL_SHARD
-  mixed_precision: PURE
-  activation_checkpointing: false
-  activation_checkpointing_reentrant: false
-  activation_cpu_offload: false
-  limit_all_gathers: true
-  verbose: false
+# DeepSpeed
+deepspeed_config:
+  train_batch_size: 256
+  train_micro_batch_size_per_gpu: 16
+  gradient_accumulation_steps: 2       # 256/16/8 = 2
+  bfloat16:
+    enabled: True
+  zero_optimization:
+    stage: 3

 # Logging
 progress_bar: false

```

**Comment by guoyejun** [comment]
@vchiley could you help to answer the below two questions, thanks.

1)  https://docs.mosaicml.com/projects/composer/en/stable/notes/distributed_training.html#deepspeed mentioned that only stage 1 and 2 are supported, is it out of date? (since I'm able to run with stage 3 now)

2) How can I get the FLOPS for each GPU when running the MPT models?

**Comment by guoyejun** [comment]
looks that FLOPS can be dumped at https://docs.mosaicml.com/projects/composer/en/stable/api_reference/generated/composer.callbacks.SpeedMonitor.html#speedmonitor,  @vchiley  is there any example to config in yaml file? thanks.

**Comment by guoyejun** [comment]
@dakinggg  @mvpatel2000 @nik-mosaic @eracah @dblalock just adding the contributors of speed_monitor.py, sorry for the disturbing, do you happen to know how to output the Training throughput [Tokens/sec/GPU] and floating point performance [TFLOP/sec/GPU] for MPT models? thanks.

**Comment by guoyejun** [comment]
I finally found the answer, just add one option in the yaml file, see below.  
```
--- a/scripts/train/yamls/pretrain/mpt-125m.yaml
+++ b/scripts/train/yamls/pretrain/mpt-125m.yaml
@@ -101,6 +101,7 @@ console_log_interval: 1ba
 callbacks:
   speed_monitor:
     window_size: 10
+    gpu_flops_available: true
   lr_monitor: {}
   memory_monitor: {}
   runtime_estimator: {}
```

And we'll see more output like below:
         Train throughput/batches_per_sec: x
         Train throughput/samples_per_sec: x
         Train throughput/device/batches_per_sec: x
         Train throughput/device/samples_per_sec:x
         Train throughput/tokens_per_sec: x
         **Train throughput/device/tokens_per_sec: x**    # Training throughput [Tokens/sec/GPU] 
         Train throughput/flops_per_sec: x
         **Train throughput/device/flops_per_sec: x**       # floating point performance [TFLOP/sec/GPU] while the real output is [FLOP/sec/GPU]
         Train throughput/device/mfu: x

**Comment by hanlint** [comment]
Thanks @guoyejun , glad you got deepspeed running and was able to measure the performance. Closing this issue for now.

**Comment by guoyejun** [comment]
> Thanks @guoyejun , glad you got deepspeed running and was able to measure the performance. Closing this issue for now.

looks that DeepSpeed ZeRO stage 3 is not well supported at least at model load time, there's OOM when the model is a bit larger, while no OOM for the same model with FSDP.
