### ISSUE TITLE
Tensor/Pipeline Parallel support

### ISSUE THREAD

**Issue by shunk031** [mosaicml/llm-foundry#437]
Thank you very much for publishing MPT models and its code base.

## 🚀 Feature Request
Do you have plans to support parallelization such as tensor parallel or pipeline parallel in the future?

## Motivation

I am currently trying to train/fine-tune MPT-30B on a V100 with 16 GB GPU RAM in a multi-GPU, multi-node situation. In this situation, I can start to fine-tune the MPT-7B model. The language capabilities of MPT-30B are very attractive and I would like to fine-tune them somehow.

I am considering the parallelization techniques as moving MPT-30B to the V100 GPU is usually difficult. There seems to be an attempt on tensor parallel in the PR (ref. #192). Will state-of-the-art parallelization techniques be introduced into this library in the future?

## [Optional] Implementation

N/A

## Additional context

Additional question: Is there a good way to train MPT-30B on some V100s with 16GB GPU RAM?

**Comment by abhi-mosaic** [comment]
Hi @shunk031 , the main form of parallelism we support is FSDP, which should allow your model + optimizer state to be sharded across the entire cluster.

To be specific, if finetuning MPT-30B with Lion, this would take about 4 (weights) + 4 (grads) + 4 (lion momentum) = 12 bytes/param  = 360GB total for model + optimizer state. So you can train this on >= 24 x V100-16GB, I would recommend maybe 32xV100-16GB or so b/c you still need some memory for the saved activations. 

If you are running into OOMs, you can reduce `device_train_microbatch_size` down to `1` which will reduce activation memory without changing the math being done.

Pipeline and Tensor parallelism will not change the system requirements as the model + optimizer state still has to live somewhere in GPU memory. We are investigating TP as you mentioned for the purposes of **performance improvement** but it will not change the memory requirements.

Hope this helps!

**Comment by shunk031** [comment]
Hi, @abhi-mosaic

Thank you for the reply. I am new to distributed training and did not know that I could train only with the FSDP. Based on your advice, I tried to train the model on 32 V100 GPUs (16 GB GPU RAM). However, even with `device_train_microbatch_size = 1`, a CUDA out of memory error occurred as follows:

```
│ /home/shunk031/llm-foundry/.venv/lib/python │
│ 3.10/site-packages/torch/autograd/__init__.py:200 in backward                │
│                                                                              │
│   197 │   # The reason we repeat same the comment below is that              │
│   198 │   # some Python versions print out the first line of a multi-line fu │
│   199 │   # calls in the traceback and some print out the last line          │
│ ❱ 200 │   Variable._execution_engine.run_backward(  # Calls into the C++ eng │
│   201 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,    │
│   202 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into th │
│   203                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 3;
15.77 GiB total capacity; 10.92 GiB already allocated; 965.38 MiB free; 13.78
GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try
setting max_split_size_mb to avoid fragmentation.  See documentation for Memory
Management and PYTORCH_CUDA_ALLOC_CONF```
```

Fortunately, the forward calculation is possible, and the backward calculation appears to be giving an error. Any ideas on how to resolve this?

**Comment by shunk031** [comment]
By increasing the number of nodes to 34 with 4 V100 per node  (34 node * 4 GPU * 16 GB = 2,176 GB), I was able to avoid the above error and start training. GPU is all we need 😂 

Again, thank you for publishing this awesome library and the pre-trained models!
