### ISSUE TITLE
Evaluation using composer format is broken

### ISSUE THREAD

**Issue by olaf-beh** [mosaicml/llm-foundry#438]
## Environment

* From `composer_collect_env`:
  ```
  PyTorch information
  -------------------
  PyTorch version: 2.0.1+cu118
  Is debug build: False
  CUDA used to build PyTorch: 11.8
  ROCM used to build PyTorch: N/A

  OS: Debian GNU/Linux 11 (bullseye) (x86_64)
  GCC version: (Debian 10.2.1-6) 10.2.1 20210110
  Clang version: 11.0.1-2
  CMake version: version 3.25.0
  Libc version: glibc-2.31

  Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
  Python platform: Linux-5.16.0-0.bpo.4-amd64-x86_64-with-glibc2.31
  Is CUDA available: True
  CUDA runtime version: Could not collect
  CUDA_MODULE_LOADING set to: LAZY
  GPU models and configuration: 
  GPU 0: NVIDIA A100-SXM4-80GB

  Versions of relevant libraries:
  [pip3] numpy==1.24.3
  [pip3] pytorch-ranger==0.1.1
  [pip3] torch==2.0.1+cu118
  [pip3] torch-optimizer==0.3.0
  [pip3] torchaudio==2.0.2+cu118
  [pip3] torchdata==0.6.1
  [pip3] torchmetrics==0.11.3
  [pip3] torchtext==0.15.2
  [pip3] torchvision==0.15.2+cu118
  [conda] Could not collect

  Composer information
  --------------------
  Composer version: 0.15.0
  Composer commit hash: ccb47290eb5de45ca74f3f7bbe5278b532c0e813
  ```
* llm-foundry git HEAD `55da325 2023-06-21 updt composer to 0.15.0`

### Description and how to reproduce

* It seems that there is an issue when performing evaluation using composer format `*.pt`: Benchmarks lambada and jeopardy are totally off, hellaswag, triviaqa and mmlu show significant different values (3).
* Evaluation on HF formated self-trained model is in line with benchmark results when using the `mosaicml/mpt-7b-instruct` HF model (compare 2 and 4). Thats good.
               
|  #  | model           | comment      | lambada_openai | hellaswag | piqa  | arc_easy | arc_challenge | boolq     | copa  | winograd | winogrande | triviaqa   | jeopardy  |  mmlu     |
| --- | --------------- | ------------ | -------------- | --------- | ----- | -------- | ------------- | --------- | ----- | -------- | ---------- | ---------- | --------- | --------- |
|   1 | mpt-7b          | HF           |        0.686   |   0.761   | 0.799 |    0.677 |         0.394 |   0.741   | 0.800 |    0.850 |      0.681 |    0.336   |   0.276   |   0.291   |
|   2 | mpt-7b-instruct | HF           |        0.680   |   0.768   | 0.801 |    0.686 |         0.432 |   0.739   | 0.830 |    0.846 |      0.676 |    0.328   |   0.301   |   0.342   |
|   3 | mpt-7b-instruct | self, 3ep PT |      **0.018** | **0.388** | 0.766 |    0.631 |         0.349 |   0.400   | 0.800 |    0.821 |      0.672 |  **0.264** | **0.086** | **0.239** |
|   4 | mpt-7b-instruct | self, 3ep HF |        0.664   |   0.777   | 0.793 |    0.689 |         0.444 |   0.739   | 0.840 |    0.850 |      0.679 |    0.310   |   0.282   |   0.333   |

* 1: `mosaicml/mpt-7b` HF model own evaluation (just for reference) using 
  ```
  composer eval/eval.py eval/yamls/hf_eval.yaml icl_tasks=eval/yamls/tasks-0-shot.yaml \
  model_name_or_path=mosaicml/mpt-7b
  ```
* 2: `mosaicml/mpt-7b-instruct` HF model own evaluation using
  ```
  composer eval/eval.py eval/yamls/hf_eval.yaml icl_tasks=eval/yamls/tasks-0-shot.yaml \
  model_name_or_path=mosaicml/mpt-7b-instruct
  ```
* 3: `mosaicml/mpt-7b` model self trained on `mosaicml/dolly_hhrlhf` 3ep using evaluation on composer format checkpoint
  ```
  composer eval/eval.py eval/yamls/hf_eval.yaml icl_tasks=eval/yamls/tasks-0-shot.yaml \
  load_path=mpt7b_dolly_sft/checkpoints/latest-rank0.pt
  ```
* 4: `mosaicml/mpt-7b` model self trained on `mosaicml/dolly_hhrlhf` 3ep (same as 3) using evaluation of model **converted to HF format**
  ```
  composer eval/eval.py eval/yamls/hf_eval.yaml icl_tasks=eval/yamls/tasks-0-shot.yaml \
  model_name_or_path=mpt7b_dolly_sft_hf
  ```
  Command for conversion: 
  ```
  python inference/convert_composer_to_hf.py --composer_path mpt7b_dolly_sft/checkpoints/latest-rank0.pt \
  --hf_output_path mpt7b_dolly_sft_hf --output_precision bf16
  ```

## Expected behavior

Evaluation using composer format `*.pt` should give correct benchmark results and should be consistent with results from same model but converted to HF format.

## Additional context

See also #383

**Comment by bmosaicml** [comment]
Hi @olaf-beh I am investigating this now. I am guessing either there is a bug in the checkpoint loading logic and the weights aren't actually being loaded (which would cause behavior to be random), or there is something about the fine tuning that is causing the issue. I am going to verify internally with the *pt checkpoints we used to create the HF models and get back to you!

**Comment by hanlint** [comment]
Hello @bmosaicml is there an update here?

**Comment by dakinggg** [comment]
Hey @olaf-beh, I believe this is an issue of the command line override of `load_path` not being at the right indentation level. Since `models` is expected to be a list of model configs, the load_path needs to be specified on the particular list item. Let us know if using a yaml instead of the command line overrides resolves your issue!
