### ISSUE TITLE
`List index out of range` when response is empty

### ISSUE THREAD

**Issue by matthiasgeihs** [mosaicml/llm-foundry#445]
## Problem

Getting error `List index out of range` when finetuning on a dataset that has an item with an empty response (i.e., `"response": ""`).

## To reproduce

1. Create a JSON finetuning dataset with an item that has an empty response. `"response": ""`
2. Run finetuning on the dataset.

See MosaicML-Community Slack Thread for more details:
https://mosaicml-community.slack.com/archives/C02H7NGT4T1/p1688543592492389

## Expected behavior

Either throw a clear error message that a finetuning dataset cannot have an item with an empty response.
Or somehow handle such items without throwing an error (e.g., just ignore these items).

## Environment
---------------------------------
System Environment Report        
Created: 2023-07-09 20:21:22 UTC
---------------------------------

PyTorch information
-------------------
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.19.0-1027-gcp-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB

Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.13.1+cu117
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==0.11.3
[pip3] torchtext==0.14.1
[pip3] torchvision==0.14.1+cu117
[conda] Could not collect

Composer information
--------------------
Composer version: 0.15.1
Composer commit hash: None
Host processor model name: Intel(R) Xeon(R) CPU @ 2.20GHz
Host processor core count: 12
Number of nodes: 1
Accelerator model name: NVIDIA A100-SXM4-40GB
Accelerators per node: 1
CUDA Device Count: 2

**Comment by L1aoXingyu** [comment]
maybe just remove the data with empty response when preprocessing, that's what I did.

**Comment by matthiasgeihs** [comment]
> maybe just remove the data with empty response when preprocessing, that's what I did.

Yes, that works. However, it wasn't clear from the error that this was the issue. @dakinggg helped me resolve it and asked me to topen an issue here. It would be nicer if a clear error message was thrown, helping the uninformed user resolve it quickly without having to go through the Slack support like me ;)

**Comment by dakinggg** [comment]
Yeah, I asked @matthiasgeihs to file an issue we could handle this case better in our code, even though preprocessing the data to remove empty entries does solve the problem :)

**Comment by dakinggg** [comment]
Fixed by https://github.com/mosaicml/llm-foundry/pull/576
