### ISSUE TITLE
Multi-Node Training on AWS SageMaker

### ISSUE THREAD

**Issue by geodra** [mosaicml/llm-foundry#453]
## Environment
PyTorch 2.0.0
git clone https://github.com/mosaicml/llm-foundry.git
cd llm-foundry
pip install -e ".[gpu]"

## To reproduce

I have set up a mulit-node training using 2 node with 8 A100 40GB each. More specifically I use the AWS SageMaker provided GPU instances named  "ml.p4d.24xlarge"

For each node I run the following command as clearly documented here -> https://github.com/mosaicml/llm-foundry/tree/main/scripts/train#howmandygpus

Node1: 
SM_NUM_GPUS: 8
CURRENT_HOST: algo-1
WORLD_SIZE: 16
NODE_RANK: 0
BASE_RANK: 0
MASTER_PORT: 7777
MASTER_ADDR: algo-1

Node1: 
SM_NUM_GPUS: 8
CURRENT_HOST: algo-2
WORLD_SIZE: 16
NODE_RANK: 1
BASE_RANK: 8
MASTER_PORT: 7777
MASTER_ADDR: algo-1

composer --world_size $WORLD_SIZE --node_rank $NODE_RANK \
--base_rank $BASE_RANK -n $SM_NUM_GPUS \
--master_addr $MASTER_ADDR --master_port $MASTER_PORT \
train/train.py \
train/yamls/pretrain/mpt-13b.yaml \
data_local=my-copy-c4 \
train_loader.dataset.split=train_small \
eval_loader.dataset.split=val_small \
max_duration=10ba \
eval_interval=30ba \
save_folder=mpt-13b \
max_seq_len=2048 \
global_train_batch_size=160 \
device_train_microbatch_size=10

The above command run at a node level with the only difference the parameters passed to: -world_size $WORLD_SIZE --node_rank $NODE_RANK \
--base_rank $BASE_RANK -n $SM_NUM_GPUS \
--master_addr $MASTER_ADDR --master_port $MASTER_PORT \

## Expected behavior

The training is falling with the below error:
RuntimeError: Forward order differs across ranks: rank 0 is all-gathering 1 parameters while rank 1 is all-gathering 0 parameters

I also get the bellow warning but composer continue & try to train the model.

![image](https://github.com/mosaicml/llm-foundry/assets/42205330/ee0255fe-a160-46cc-b58a-1704cffb09a7)

Similar StackOverflow question: https://stackoverflow.com/questions/74910942/runtimeerror-forward-order-differs-across-ranks-rank-0-is-all-gathering-1-para

**Comment by hanlint** [comment]
Hello @geodra, unfortunately we don't have a lot of experience with AWS SageMaker. You might want to file this question with the SageMaker team.
