### ISSUE TITLE
WandB not logging all GPUs

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#454]
Currently i'm launching my setup on 4x 8x A100, so n_gpus=32, why only 8 gpus logging to WandB?
<img width="537" alt="image" src="https://github.com/mosaicml/llm-foundry/assets/43114292/3e2b1539-0c84-4d27-a4fe-882f583d64cc">

**Comment by hanlint** [comment]
By default, the `WandBLogger` only logs the rank zero node. This is to avoid creating so many multi-node groups in wandb. To enable logging on all GPUs, you can set `rank_zero_only=False` in the logger.

For more information see: 

https://github.com/mosaicml/composer/blob/ff59e862b92a7a1e62f72b57e36f528eb2c4bdfa/composer/loggers/wandb_logger.py#L44-L49
```
        rank_zero_only (bool, optional): Whether to log only on the rank-zero process.
            When logging `artifacts <https://docs.wandb.ai/ref/python/artifact>`_, it is
            highly recommended to log on all ranks.  Artifacts from ranks ≥1 will not be
            stored, which may discard pertinent information. For example, when using
            Deepspeed ZeRO, it would be impossible to restore from checkpoints without
            artifacts from all ranks (default: ``True``).
```
