### ISSUE TITLE
Discrepancy in optimizer mentions in blogs vs YAML files

### ISSUE THREAD

**Issue by saiajaym** [mosaicml/llm-foundry#457]
## ❓ Question
Hi,
In the MPT blogs it's said the LION optimizer is used for pertaining. However the config files use AdamW optimizer. It's unsure how it's trained

**Comment by hanlint** [comment]
Hello @saiajaym , the config files in this repository are only naive baselines. For training MPT, we did use the LION optimizer.

**Comment by kyleliang919** [comment]
can you please shed some lights on what configuration you used for mpt training? It will really help ppl understand the difference between adamW and etc.
