### ISSUE TITLE
MPT & Arabic 

### ISSUE THREAD

**Issue by alielfilali01** [mosaicml/llm-foundry#462]
Hello! I'm interested to find out if the corpora utilized during pre-training for MPT includes any content in the Arabic language.

**Comment by hanlint** [comment]
Hello @alielfilali01 we mainly focused on English, so Arabic is unlikely to be a significant part of the dataset for the MPT models. However, you are welcome to try it out yourself and see. Sometimes, enough languages still make it in, resulting in surprising amounts of fluency.

Please let us know what you find! I'll close this for now.
