### ISSUE TITLE
Convert MPT 30B to hf with 192GB RAM

### ISSUE THREAD

**Issue by matthiasgeihs** [mosaicml/llm-foundry#463]
We've finetuned MPT 30B. The resulting composer checkpoint is ~335GB. We are usually running stuff on a machine with 192GB RAM. However, converting the checkpoint to hugging face format fails on this machine (the process got killed). I suspect this is due to insufficient memory.

Any chance we can run conversion to HF of a 335GB checkpoint on a machine with 192GB RAM?

**Comment by alanxmay** [comment]
@matthiasgeihs Hi, may I ask how to convert 30B checkpoint?

**Comment by matthiasgeihs** [comment]
@alanxmay 
In the [quickstart](https://github.com/mosaicml/llm-foundry#quickstart), you will find an example for how to convert a composer checkpoint to huggingface format:
```
# Convert the model to HuggingFace format
python inference/convert_composer_to_hf.py \
  --composer_path mpt-125m/ep0-ba10-rank0.pt \
  --hf_output_path mpt-125m-hf \
  --output_precision bf16 \
  # --hf_repo_for_upload user-org/repo-name
```
Note that this seems to require a machine with sufficient RAM to fit the whole model in there.

**Comment by alanxmay** [comment]
@matthiasgeihs
Thanks, according to this comment https://github.com/mosaicml/llm-foundry/issues/367#issuecomment-1610043429, did you also use `mono_ckpt_saver`?

**Comment by matthiasgeihs** [comment]
> @matthiasgeihs
> Thanks, according to this comment [#367 (comment)](https://github.com/mosaicml/llm-foundry/issues/367#issuecomment-1610043429), did you also use `mono_ckpt_saver`?

This issue is about converting saved checkpoints to huggingface format (not saving checkpoints in the first place).

**Comment by alanxmay** [comment]
@matthiasgeihs Yes, I didn't not use mono_ckpt_saver, but saving 8 ckpt successfully. I wander if you use mono_ckpt_saver to save 1 ckpt, or you maybe figure out how to convert 8 ckpt to HF format. Thansk!

**Comment by matthiasgeihs** [comment]
> @matthiasgeihs Yes, I didn't not use mono_ckpt_saver, but saving 8 ckpt successfully. I wander if you use mono_ckpt_saver to save 1 ckpt, or you maybe figure out how to convert 8 ckpt to HF format. Thanks!

I see, not sure if that would help with the issue of converting to HF though. My impression is that you would still need to be able to load all checkpoints shards into RAM, no?

**Comment by dakinggg** [comment]
Hi, yes. Unfortunately you will need enough RAM to load the checkpoint in order to do conversion. We are working on a callback to convert checkpoints during the run to help avoid this issue. Hopefully you were able to find a machine with enough RAM! You can also save a checkpoint with `save_weights_only` to reduce the size of the final checkpoint
