### ISSUE TITLE
[FEATURE] Upgrade to FlashAttention V2 (2x speed up)

### ISSUE THREAD

**Issue by casper-hansen** [mosaicml/llm-foundry#464]
## 🚀 Feature Request
FlashAttention V2 just got released, so I propose Foundry upgrades to it, if possible. They claim a 2x speed up over V1. 

## Motivation

Since it’s much faster and saves memory, the compute budget needed to train a Foundry model would be significantly reduced. 

Thread: https://twitter.com/tri_dao/status/1680987577913065472?s=46&t=QUL78vIQDJohFpnIzCbQXA

**Comment by abhi-mosaic** [comment]
Hi @casperbh96 , thank you for bringing up FlashAttention V2. We are looking into this and will upgrade as soon as we've finished testing!

Be aware though, the training speedup will likely be 5-10% for small 2k-context models and maybe ~25% for small 8k-context models. The headline 2x speedup is for * the attention operation only *, but for most model configurations, attention is a small proportion of the overall training FLOPs. As models get wider and larger (with context length held constant), the relative work spent on attention goes down.

As a reference point, in the technical report (https://tridao.me/publications/flash2/flash2.pdf) you can find Table 1 which reports the overall speedup they saw with their training framework:
<img width="1191" alt="Screenshot 2023-07-17 at 3 29 07 PM" src="https://github.com/mosaicml/llm-foundry/assets/77638579/0e7b487f-9b5a-4aaa-83ee-ba10fb637570">

* 1.3B-2k: 1.04x speedup
* 1.3B-8k: 1.29x speedup
* 2.7B-2k: 1.08x speedup
* 2.7B-8k: 1.29x speedup

And these speedups will get smaller for larger models like MPT-7B and MPT-30B.

**Comment by casperbh96** [comment]
> * 1.3B-2k: 1.04x speedup
> * 1.3B-8k: 1.29x speedup
> * 2.7B-2k: 1.08x speedup
> * 2.7B-8k: 1.29x speedup
> 
> And these speedups will get smaller for larger models like MPT-7B and MPT-30B.

Seems the speedup is not decreasing with model size according to paper? 1.29x speedup with 8k context at both 1.3B and 3B parameters. So presumably MPT-30B would benefit the most.

**Comment by abhi-mosaic** [comment]
Based on theoretical analysis of time spent in attention at different model sizes, I don't think it will. But give us some time to integrate V2 and we shall see! :)

**Comment by casperbh96** [comment]
> Based on theoretical analysis of time spent in attention at different model sizes, I don't think it will. But give us some time to integrate V2 and we shall see! :)

Awesome, would love to see the outcome of this. 30% speed up during training is certainly valuable if it turns out to be true!

**Comment by Taishi-N324** [comment]
flash-v2 is a rough approximation (I haven't checked to see if it reproduces)
`git clone git@github.com:mosaicml/llm-foundry.git
`
```
# Creating and activating a virtual environment
python3 -m venv llmfoundry-venv
source llmfoundry-venv/bin/activate
pip install cmake packaging torch # setup.py requires these be installed
```
In llm-foundry
Comment out the setup.py section in llm-foundry or pip install -e . instead (commented out when I tried it)
```
extra_deps['gpu'] = [
    'flash-attn==v1.0.3.post0',.
    # PyPI does not support direct dependencies, so we remove this line before uploading from PyPI
    'xentropy-cuda-lib@git+https://github.com/HazyResearch/flash-attention.git@v1.0.3#subdirectory=csrc/xentropy',
]
```
`pip install -e ". [gpu]" # or pip install -e . if no NVIDIA GPU
`Next
```
git clone git@github.com:Dao-AILab/flash-attention.git
cd flash-attention
python setup.py install
```
and wait casually
After that
```
extra_deps['gpu'] = [
    'xentropy-cuda-lib@git+https://github.com/HazyResearch/flash-attention.git@v2.0.0#subdirectory=csrc/xentropy',.
]
```
and rewrite it to
`pip install -e ". [gpu]" # or pip install -e . if no NVIDIA GPU
`and so on (redundant)
Then rewrite `flash_attn_unpadded_func` to `flash_attn_varlen_func`
`build/lib/llmfoundry/models/layers/attention.py`
`venv/lib/python3.10/site-packages/xformers/_flash_attn/flash_attn_interface.py`
You should be able to learn by replacing two of the above (you may not need to replace the top one)
Considering that the functions it calls have changed and that the experimental results for flash-v2 and flash-v1 are different, I'm assuming the installation is correct.

I can confirm that flash v2 works with pyenv python 3.10 a100 this way.

Translated with www.DeepL.com/Translator (free version)

**Comment by abhi-mosaic** [comment]
I think this is resolved now and you can try CUDA-based FlashAttention-2 on the `main` branch by installing with `pip install -e .['gpu-flash2']` and by using `attn_impl: flash`. 

I tried this on a couple MPT models with seqlen=2k, and in most settings I saw a 5-10% throughput increase.

**Comment by casper-hansen** [comment]
10% is great, thanks for this :)

**Comment by dakinggg** [comment]
Just noting that you can also use it with any huggingface model that supports flash2 by setting `model.use_flash_attention_2: True` :)

**Comment by dakinggg** [comment]
and we have a provided docker image with flash 2 installed: `mosaicml/llm-foundry:2.1.0_cu121_flash2-latest`

**Comment by casper-hansen** [comment]
> Just noting that you can also use it with any huggingface model that supports flash2 by setting `model.use_flash_attention_2: True` :)

Does that include Llama and Mistral? My perception was that they are not supported

**Comment by dakinggg** [comment]
They are supported on foundry main!

**Comment by casper-hansen** [comment]
> They are supported on foundry main!

Amazing! I am very fond of the tech stack behind foundry. Could you provide an example of a config that would work with Mistral with sliding window attention?

**Comment by dakinggg** [comment]
Thanks for the kind words! If you change the model section of the yaml to

```
  model:
    name: hf_causal_lm
    init_device: mixed
    pretrained_model_name_or_path: mistralai/Mistral-7B-v0.1
    pretrained: true
    use_flash_attention_2: true
```

It should give you mistral with the default configuration from huggingface. You can add `config_overrides` to that if you want to override any of the config defaults.
