### ISSUE TITLE
yaml file for MPT-1/3/7/13B with GBS=512 at https://www.mosaicml.com/blog/amd-mi250

### ISSUE THREAD

**Issue by guoyejun** [mosaicml/llm-foundry#465]
Hi, at https://www.mosaicml.com/blog/amd-mi250, MPT-1B, MPT-3B, MPT-7B and MPT-13B with GBS=512  are used, also copy the figure below.
![image](https://github.com/mosaicml/llm-foundry/assets/10448440/9c1adfcb-9744-4d50-a287-5576f0d4dac5)

There are two changes in the yaml files mentioned in the webpage:
1) model.attn_config.attn_impl=flash
2) model.loss_fn=torch_crossentropy

and to support global batch size as 512, we also need to change for MPT-7B and MPT-13B:
3) change global_train_batch_size from 1024 to 512

Besides the above three changes, is there anything else we need to change? thanks.

For example, I suspect if we need to change the micro batch size (4, 8, 16, 32, 64) for a better performance, the current values of mbs are:
MPT-1B:  device_train_microbatch_size: 4
MPT-3B:  device_train_microbatch_size: 8
MPT-7B:   device_train_microbatch_size: 8
MPT-13B: device_train_microbatch_size: 8

Is there pipeline parallel, tensor parallel, or anything else? thanks.

It would be better if you can share the complete yaml files, thanks.

**Comment by guoyejun** [comment]
hi, I did some try on A100-40GB with 8 cards in a system, with the 3 changes mentioned above: 
1) model.attn_config.attn_impl=flash  
2) model.loss_fn=torch_crossentropy
3) global_train_batch_size=512

I saw Train throughput/device/flops_per_sec is 130--150 TFLOPS for MPT-1b/3b/7b, a big gap with 165-176 in the webpage table, and for MPT-13b, there's even OOM (out of memory).

So, could you share the exact yaml + code  (or a docker image with everything ready) to reproduce the same perf data in the webpage at https://www.mosaicml.com/blog/amd-mi250? thanks.

**Comment by guoyejun** [comment]
btw, we are using NVIDIA-SMI 525.105.17   Driver Version: 525.105.17,  which is released at 2023.3.30.

**Comment by guoyejun** [comment]
i tried the possible combinations of MBS and other params such as attn_impl, and got similar perf for MPT-1B and MPT-13B (within ~3% diff) but still get 10%+ perf gap for MPT-3B and MPT-7B, comparing with data in the webpage. anyone can help? thanks.

**Comment by hanlint** [comment]
Hello @guoyejun , if you are interested primarily in the NVIDIA benchmarking data, I would primarily refer you to our benchmarking page here: https://github.com/mosaicml/llm-foundry/tree/main/scripts/train/benchmarking

You can find details about the exact docker container used, as well as the MBS settings.

**Comment by guoyejun** [comment]
> Hello @guoyejun , if you are interested primarily in the NVIDIA benchmarking data, I would primarily refer you to our benchmarking page here: https://github.com/mosaicml/llm-foundry/tree/main/scripts/train/benchmarking
> 
> You can find details about the exact docker container used, as well as the MBS settings.

thanks @hanlint , but looks that the data at https://github.com/mosaicml/llm-foundry/tree/main/scripts/train/benchmarking does not align with the data at https://www.mosaicml.com/blog/amd-mi250.

1) according to https://www.mosaicml.com/blog/amd-mi250,  we get the parameters that seq length is 2048, global batch size is 512 and GPU number is 8.
![image](https://github.com/mosaicml/llm-foundry/assets/10448440/eccd3baf-59d2-4609-bbbc-f148da57318d)

2) we filter the seq length, gbs and gpu# for the A100 80GB at the table from https://github.com/mosaicml/llm-foundry/tree/main/scripts/train/benchmarking, see below, only MPT-7B is there, and I don't understand how the result is aligned with the above table.
![image](https://github.com/mosaicml/llm-foundry/assets/10448440/44caff0b-5eae-42ef-8a94-164fb439d599)

3) we filter the seq length, gbs and gpu# for the A100 40GB at the table from https://github.com/mosaicml/llm-foundry/tree/main/scripts/train/benchmarking, see below, MPT-1B and MPT-13B are there, and I don't understand how the result is aligned with the first table.
![image](https://github.com/mosaicml/llm-foundry/assets/10448440/4046290a-dd5e-46a0-89c8-bc815e813451)

**Comment by abhi-mosaic** [comment]
Hi @guoyejun, the settings/results in the `train/benchmarking/README.md` are a few months old and need to be refreshed. The stack is even faster now, that is why there is a discrepancy between the blog (new) and the README (old).

In the blog post, we tune for the best performance available independently on each system, so for AMD MI250 we used:
* model.attn_config.attn_impl=flash
* model.loss_fn=torch_crossentropy

And on A100 we used these settings:
* model.attn_config.attn_impl=triton
* model.loss_fn=fused_crossentropy

Here are the settings we used for every run in the blog post:
| Model      | GPU | Act Ckpt |  Microbatch Size | Global Train Batch Size | TFLOP/s |
| ----------- | ----------- |----------- | ----------- |----------- |----------- |
| MPT-1B      | A100-80GB  | False | 16 | 512 | 185 |
| MPT-1B      | A100-40GB  | False | 8 | 512 | 171 |
| MPT-1B      | MI250  | False | 12 | 512 | 133 |
| MPT-3B      | A100-80GB  | False | 8 | 512 | 189 |
| MPT-3B      | A100-40GB  | False | 4 | 512 | 165 |
| MPT-3B      | MI250  | False | 8 | 512 | 140 |
| MPT-7B      | A100-80GB  | False | 4 | 512 | 193 |
| MPT-7B      | A100-40GB  | False | 2 | 512 | 176 |
| MPT-7B      | MI250  | False | 4 | 512 | 144 |
| MPT-13B      | A100-80GB  | True | 16 | 512 | 171 |
| MPT-13B      | A100-40GB  | True | 4 | 512 | 160 |
| MPT-13B      | MI250  | True | 16 | 512 | 122 |

Hope this helps! I will close the issue for now as I think this is all the details required to reproduce, but feel free to reopen / ping me if you see any issues.
