### ISSUE TITLE
MPT-7B on single A100 80GB

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#468]
## Is it possible to do pretraining of MPT-7B model on single A100 80GB ?

I am getting OOM with following minimal configs:

- global_train_batch_size = 1
- device_train_microbatch_size = 1
- device_eval_batch_size = 1
- activation_checkpointing = true
- activation_cpu_offload = true
- max_seq_len: 2048 # tried 512 as well
- precision: amp_bf16

I have seen llama 7B being trained on single GPU.
Is there anything that needs to be modified for this MPT-7B pretraining? Am I missing something?

**Comment by bcui19** [comment]
Hey, a 7B model w/ DecoupledAdamW will utilize 7B * 12 Bytes / param of memory = 84GB. So with AdamW it is expected to OOM.
