### ISSUE TITLE
Multi Node Training

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#471]
Say in a cluster I have 50 nodes - Node1, Node2, ..., Node50. 
I have scheduler machine with IP X.X.X.X under which I have all these nodes with IPs ranging from 10.0.0.1, ..., 10.0.0.50

I want to do multi node training on nodes say 11 to 20.
How do I make use of scheduler machine in this case to run **composer train.py** only on 11 to 20 nodes?

The tutorial provided here - [multi-node-cli](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/README.md#multi-node-via-environment-variables) says to launch appropriate command on each node.

Is there a way to make use of scheduler machine to run a shell script to run these commands on multiple nodes?

**Comment by Taishi-N324** [comment]
@palash04 

It's my way
to the sh script
, you can ssh to each node automatically
 and use **composer** to train on multiple nodes
Please try to reference

https://github.com/llm-jp/llm-foundry/tree/llm-foundry/taishi/multiple-runs
