### ISSUE TITLE
Change attention implementation to Triton in Llamav2 model

### ISSUE THREAD

**Issue by higuhigu-lb** [mosaicml/llm-foundry#478]
## 🚀 Feature Request

- Want to train LLM (Language Model) available on Huggingface with MosaicML.
- Want to speed up the training process by using Triton for attention implementation.

## Motivation

- I want to fine-tune additional data on top of a pre-trained publicly available model to enhance performance with limited language resources.
- While training is currently possible by specifying the path in the YAML file, the training speed is slow.
    - It takes twice the time compared to training from scratch with MPT-7b.
- I aim to accelerate the training process by configuring the attention implementation, similar to the implementation in [MPT](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/finetune/mpt-7b_dolly_sft.yaml).

## Implementation

The training is carried out using the following steps:
- Dataset creation following the instructions in the [Readme](https://github.com/mosaicml/llm-foundry/blob/main/README.md#quickstart).
- Modification of the [model's config](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/pretrain/mpt-7b.yaml).
- Training using the composer command.

**Comment by vchiley** [comment]
LLaMa v2 is implemented by Meta.
We do not own the code / we cannot modify it.

**Comment by vchiley** [comment]
Llama 2 is implemented by Meta.
While we do enable users to download and run huggingface models (eg [model setting here](https://github.com/mosaicml/llm-foundry/blob/main/scripts/train/yamls/pretrain/opt-3b.yaml#L11)), we do not own the Llama 2 code and cannot modify it.

**Comment by dakinggg** [comment]
This is done now. You can add `attention_patch_type: triton` to swap in triton attention for llama.

**Comment by higuhigu-lb** [comment]
@dakinggg 

Thank you for your kind information. I write conig example below.

```
# Model
model:
  name: hf_causal_lm
  init_device: mixed
  pretrained: true
  pretrained_model_name_or_path: meta-llama/Llama-2-7b-hf
  use_auth_token: true
  attention_patch_type: triton
```
