### ISSUE TITLE
docstring in DecoupledAdaLRLion  is not cohere with the code

### ISSUE THREAD

**Issue by ericxsun** [mosaicml/llm-foundry#480]
The [docstring](https://github.com/mosaicml/llm-foundry/blob/ef8d41431a65e21e4571e322104a192df3d08233/llmfoundry/optim/adaptive_lion.py#L26) of DecoupledAdaLRLion say ```the LR is scaled down by min(`lr_penalty` ** N, `min_scale`)```, but the code implemented [`adjust_lr` here](https://github.com/mosaicml/llm-foundry/blob/ef8d41431a65e21e4571e322104a192df3d08233/llmfoundry/optim/adaptive_lion.py#L125) is `lr * max(min_scale, lr_penalty**num_times)`.

So which is the right one, `max` or `min`?

**Comment by bmosaicml** [comment]
you're correct. the doctoring is wrong, thanks for catching the typo! fixing with #563
