### ISSUE TITLE
Overfitting when further pre-training MPT-7b

### ISSUE THREAD

**Issue by ShaiMeital** [mosaicml/llm-foundry#487]
Hey guys. 
I am further pre-training the MPT-7b model on ~700mb of text. 
The model is learning and the validation metrics improve over the optimization period, but in inference time I get awful results often repeating a single word. I am testing some 350ba to ~700ba of training. 

I am using 4 A100 80gb cards and following the docs of the repo concerning data pp and training. 

Any idea how to overcome this?

**Comment by KuuCi** [comment]
Just curious what's your batch size and how many epochs are you training your data on?

**Comment by ShaiMeital** [comment]
I used the default global_train_batch_size: 1024 (in the pretrain/MPT-7b.yaml) and trained for 750ba. I noticed the config does not mention epochs but "ba" which I inferred as batches.

**Comment by KuuCi** [comment]
Do you want to try seeing max_duration to be 1ep or 2ep (something like max_duration: 2ep)?

**Comment by KuuCi** [comment]
There might also be a bug as of right now with training with AliBi if that is what you are training with that we are trying to fix. Are you seeing a warning where some weights aren't being initialized when loading in a checkpoint at inference time? If so, include model.config_overrides.learned_pos_emb: false in your yaml

**Comment by ShaiMeital** [comment]
I will try to set the max_duration to 1-2 ep and report back
