### ISSUE TITLE
Dataset release

### ISSUE THREAD

**Issue by lengstrom** [mosaicml/llm-foundry#499]
Hi, thank you for all the great work with the MPT models and with LLM-foundry! We are interested in doing research on the MPT model family that would require training on the same dataset as MPT. Are there any plans to release a script or data dump of the MPT-7B dataset (i.e., the dataset described in the blog post https://www.mosaicml.com/blog/mpt-7b)?

**Comment by tbarton16** [comment]
Hi! I am on the mosaic data team, and while I understand the importance off getting the precise indices of the training dataset, as well as the difficulty of downloading 10 huggingface datasets, the best you can do right now is to obtain the sources we used and combine them in the proportions listed in the blog post. A good place to start would be english language [mc4](https://huggingface.co/datasets/allenai/c4/blob/mC4_3.1.0/README.md). I know this is not an exact solution, but please stay tuned as we release more products and code in the future.

**Comment by lengstrom** [comment]
Thanks for the quick response! Precise indices could be going above and beyond - it possible that Mosaic could release a script making the proper mixture (distributionally)? I just would like to make sure that the dataset composition is the same. 

I would be happy to try to replicate the dataset composition myself, but I'm worried about replicating it precisely given all the possible details around combining/resampling a diverse set of datasets. Most importantly I don't have the resources to "sanity check" any dataset composition I could come up with by training a new 7B model myself.

**Comment by tbarton16** [comment]
I definitely see it would be useful to release a scripts that replicates the MPT mixture exactly. I just don't know what the timing will be on getting them developed + out the door. Also if your concern is disk space, even if we release a scripts you will still need to download these datasets in their entirety.

**Comment by lengstrom** [comment]
Hi, thanks for the response! My concern isn't disk space, I am worried about being able to replicate the dataset precisely. Please let me know if I'm misunderstanding the data creation process - I would love to just combine huggingface datasets if it is is really all you need to replicate the MPT dataset 😅  

The reason why I worry is that the Appendix of the blog post contains a number of steps that are difficult to replicate without either access to the code or much more detailed descriptions. As a few examples (off the top of my head):

* For the mC4 filtering, how is a "word" defined? (i.e., is there a particular library used to parse documents into words? is it just `text.split(' ')` in python?
* SemDeDup has many hyperparameters parameters, how exactly was it applied to "remove the 20% most similar documents within C4"?
* Semantic Scholar ORC: how is a "paragraph" defined? (is it just a newline?)
* and I'm sure more will come up when actually replicating the dataset in code..

Oftentimes seemingly unimportant steps in data curation can impact downstream model performance, so I'm concerned that without code here it would be impossible to meaningfully replicate the dataset. (And furthermore since I can't actually train another 7B model I can't even verify that the dataset was properly replicated)

Thanks so much for engaging and I definitely understand how much work it is to release these kinds of scripts! Broadly Mosaic is amazing at making their code/training procedures in a reproducible/research-usable state and it would be so helpful for research if the data was released as well 😄

**Comment by tbarton16** [comment]
Hi, sorry I closed this, you bring up some *really* good points. I didn't realize semdedup was used in filtering c4. 

The good news is that I recently ran an a/b test on using semdedup and it actually doesn't make a difference whether you do it or not for the language data I was using.

I think it makes sense to keep it closed since we will eventually release the data but its not happening immediately, so those in a hurry should download from huggingface and filter themselves. Here are the filters we used: 

`# Copyright 2022 MosaicML LLM Foundry authors
# SPDX-License-Identifier: Apache-2.0

from typing import Any, Dict

from blingfire import text_to_words
from filter.shared import most_frequent, most_frequent_english_words


class FilterAttempt1:

    def keep(self, sample: Dict[str, Any]) -> bool:
        s = sample['text'].lower()

        # Check whether the most frequent character is alphabetic.
        no_whitespace = ''.join(s.split())
        if not most_frequent(no_whitespace)[0].isalpha():
            return False

        # Check that most characters are alphanumeric.
        num_alphas = len([a for a in no_whitespace if a.isalnum()])
        if float(num_alphas) / len(no_whitespace) < 0.90:
            return False

        # Split into words.
        ws = [x for x in text_to_words(s).split() if x.isalnum()]

        # Ensure there are enough words.
        if len(ws) < 100:
            return False
        if len(ws) > 50000:
            return False

        # Verify that the most frequent word isn't too frequent.
        w, freq = most_frequent(ws, most_frequent_english_words)
        frac = float(freq) / len(ws)
        if w is not None and (len(ws) > 500 and frac > 0.1) or (len(ws) <= 500
                                                                and frac > 0.3):
            return False

        # Return the sequence length.
        return True


class FilterAttempt2:

    def keep(self, sample: Dict[str, Any]) -> bool:
        s = sample['text'].lower()

        # Check whether the most frequent character is alphabetic.
        no_whitespace = ''.join(s.split())
        if not most_frequent(no_whitespace)[0].isalpha():
            return False

        # Check that most characters are alphanumeric.
        num_alphas = len([a for a in no_whitespace if a.isalnum()])
        if float(num_alphas) / len(no_whitespace) < 0.92:
            return False

        # Split into words.
        ws = [x for x in text_to_words(s).split() if x.isalnum()]

        # Ensure there are enough words.
        if len(ws) < 200:
            return False
        if len(ws) > 50000:
            return False

        # Verify that the most frequent word isn't too frequent.
        w, freq = most_frequent(ws, most_frequent_english_words)
        frac = float(freq) / len(ws)
        if w is not None and (len(ws) > 500 and
                              frac > 0.075) or (len(ws) <= 500 and frac > 0.3):
            return False

        # Return the sequence length.
        return True`

**Comment by lengstrom** [comment]
Thanks for the help, this is really useful!

**Comment by lengstrom** [comment]
Hi @tbarton16, thank you so much for your help so far.. is it possible you could release the code used to filter for Semantic Scholar ORC? (i.e., paragraphs/words in this context are hard to define) Thanks!

**Comment by lengstrom** [comment]
Also, can you please define the function `most_frequent`?
