### ISSUE TITLE
how to use param spin_dataloaders in Trainer

### ISSUE THREAD

**Issue by HunterKruger** [mosaicml/llm-foundry#508]
If I start training with 4 nodes, each equipped with 8 GPUs, and then save checkpoints, I later resume training from the saved checkpoint using spin_dataloaders=True. However, if I increase the nodes to 8 and continue training from the previous checkpoint, the data loader will be adjusted to include the previously seen data points. Should I need to manually skip the data points that were already processed? Will be the data loader will manage the distribution of data across the increased number of nodes for me?

**Comment by karan6181** [comment]
Hi @HunterKruger, If you are using the [Composer](https://github.com/mosaicml/composer/) and [Streaming](https://github.com/mosaicml/streaming), which I think you are, then you don't have to do anything explicitly. The dataset meta data will get saved when saving a checkpoints and it will load the same meta-data while loading the same checkpoints when you execute another run with `autoresume=True` and streaming dataset will skip the samples that is being already seen by your previous run. Streaming dataset also takes care of distributing the unseen samples (not been processed by the model) into nodes/gpus/workers.
