### ISSUE TITLE
Generate callback not working with no MPT models

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#524]
Hi! 

Generate callback not working with models from **HuggingFace** (OPT, GPT etc) (it's working only in **single-node single-gpu** setup!) and working OK with **MPT family**.

We found some workaround solution, add `FSDP.summon_full_params` [here](https://github.com/mosaicml/llm-foundry/blob/main/llmfoundry/callbacks/generate_callback.py#L86):

```
with FSDP.summon_full_params(model.model, writeback=False, recurse=False):
                output_token_ids = model.model.generate(  # type: ignore
                    input_ids=tokenized_input['input_ids'],
                    attention_mask=tokenized_input['attention_mask'],
                    synced_gpus=True,
                    **self.generate_kwargs,
                )
```

This works really fine with **single-node multi-gpu** setup with both HF and MPT models. 
But in **multi-node multi-gpu** setup it's works fine only on little models (like 125m), and works really slooow on big models (like 7B) (maybe something like 100x speed down comparing with no-generate callback setup). 

This table will helps you understand the problem.

| Models Family | your callback | callback with FSDP |
| :---         |     :---:      |          ---: |
| MPT Family, 125m   | **OK** (including multi-node)     | **OK** (including multi-node)    |
| HF Family, 125m   | **only single-gpu**     | **OK** (including multi-node)
| MPT Family, 7b   | **OK** (including multi-node)   | really **slow** on **multi-node** (100x speed down) / **OK** on **single-node multi-gpu**   |
| HF Family, 7b  | **only single-gpu**     | really **slow** on **multi-node** (100x speed down) / **OK** on **single-node multi-gpu**

Do you know something about this, maybe we can fix this issue?

@dakinggg @vchiley

**Comment by dakinggg** [comment]
You are correct in the fix. It depends on model/torch version. See https://github.com/mosaicml/composer/blob/8d59da2293499f1faabff6276eee98344f334c64/composer/models/huggingface.py#L530-L572 for what we have upstream.

As for the speed, using generate with FSDP is just fundamentally slow. It will be even slower if you don't have good node interconnect speed. If you are trying to do large amounts of inference, you will not want to use FSDP. You may be able to get some speed up by setting `limit_all_gathers: True` and `forward_prefetch: True` in the FSDP config if you are not already.
