### ISSUE TITLE
KeyError: "attribute 'weight' already exists"

### ISSUE THREAD

**Issue by sysusicily** [mosaicml/llm-foundry#529]
composer train.py mpt-1b.yaml，get the keyerror
GPU：3*RTX4090
![image](https://github.com/mosaicml/llm-foundry/assets/133207026/55818ef4-8115-44d8-a49f-5b6aa83c8e5e)

**Comment by dakinggg** [comment]
This seems to be an issue with torch2 and weight tying which we are working on fixing. You can set `use_orig_params=False` in your `fsdp_config` in the meantime, and it should work. Or use torch 1.13 instead.

**Comment by dakinggg** [comment]
This should be resolved on main. Please let us know if you are still encountering problems.
