### ISSUE TITLE
Composer S3 save ckpt bug?

### ISSUE THREAD

**Issue by germanjke** [mosaicml/llm-foundry#536]
Hi, i'm using this config
```
# Checkpoint to local filesystem or remote object store
    save_interval: 4ba
    save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
    save_folder: s3://bucket/path/llama2/ckpts/{run_name}
    save_filename: ep{epoch}-ba{batch}-rank{rank}.pt
    save_overwrite: true
```
Composer warns me

```
2023-08-18 13:41:24,016: rank0[247][MainThread]: DEBUG: composer.utils.checkpoint: Saving checkpoint to path/llama2/ckpts/{run_name}/ep{epoch}-ba{batch}-rank{rank}.pt
```

So it's saving in my local directory, not s3, he ignores `s3://bucket/`

My endpoint is ok, casue no errors about this and my `data_remote` loads good from my s3.

**Comment by eracah** [comment]
@germanjke, Are you sure it doesn't get saved to s3?

**Comment by germanjke** [comment]
It will saved on local path anyway? 
It's not like `if s3 in path: save_to_s3() else: save_to_local()`? 
yes i confirm it

**Comment by germanjke** [comment]
```
Name: composer
Version: 0.15.0
Summary: Composer is a PyTorch library that enables you to train neural networks faster, at lower cost, and to higher accuracy.
Home-page: https://github.com/mosaicml/composer
Author: MosaicML
Author-email: team@mosaicml.com
License: 
Location: /usr/lib/python3/dist-packages
Requires: coolname, importlib-metadata, mosaicml-cli, numpy, packaging, psutil, py-cpuinfo, pyyaml, requests, tabulate, torch, torch-optimizer, torchmetrics, torchvision, tqdm
Required-by: 
```

**Comment by dakinggg** [comment]
The debug print statement is a bit misleading. Under the hood we create an S3 object store which already knows what bucket it is writing to. So within that bucket it is writing to the object key that it prints out.

**Comment by germanjke** [comment]
It's little bit strange, cause I can save gpt-neo-125m checkpoints and can't save it with LLaMA2, with same docker image
Maybe problem on my side, will try to fix this
I hope it's no bugs about LLaMA2

**Comment by germanjke** [comment]
Hi guys, problem was about ~11 min downloading 7B ckpts to s3, obviously 125m ckpts downloads so much faster.
My expermients was like debug, and `max_duration` was like `10ba` (training was like 10 mins), so when training is over i just killed my jobs. 
But if you will not kill them after training,  ckpts will saving later. So yes, just wait some time for bigger models.
Thanks!
