### ISSUE TITLE
[How to resume my model training]

### ISSUE THREAD

**Issue by mynewstart** [mosaicml/llm-foundry#540]
Hi,
I am using scripts/train/train.py for model training from scratch, but I'd like to know how to resume my model training, like restore model parameters,optimizer, schedule and data point, is there any example? I found 'load_path' in Trainer class, it can reload model,optimizer and schedule, but how to restore the data point?

**Comment by SingL3** [comment]
set autoresume, check code [here](https://github.com/mosaicml/composer/blob/9f594876f957c912758e540598ac9f47a468c39d/composer/trainer/trainer.py#L330) and [here](https://github.com/mosaicml/llm-foundry/blob/667006889b5aab99fbecf1f927704fa7645e1799/scripts/train/train.py#L352)

**Comment by dakinggg** [comment]
Closing, as @SingL3 's answer is correct. Please reopen if you still have questions.
