### ISSUE TITLE
ERROR: Could not build wheels for triton-pre-mlir, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by ibrahim737701** [mosaicml/llm-foundry#551]
## ❓ Question
Getting this error when trying to install triton using the following command:-

pip install triton-pre-mlir@git+https://github.com/vchiley/triton.git@triton_pre_mlir#subdirectory=python

## Additional context

I'm trying to run an mpt-30B model with flash attention

**Comment by dakinggg** [comment]
If you are having trouble installing triton on your setup, we highly recommend using the provided docker images.
