### ISSUE TITLE
Different concat_tokens return different number of tokens.

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#553]
## To reproduce
In convert_dataset_hf.py:
```
with MDSWriter(columns=columns,
                 out=path,
                 compression=args.compression) as out:
      if denominator is not None:
          for sample in tqdm(samples,
                             desc=folder_split,
                             total=denominator):
              tokens = np.frombuffer(sample['tokens'], dtype=np.int64).copy()
              token_count += len(tokens)
              word_count += len(tokenizer.decode(tokens).split(' '))
              out.write(sample)
      else:
          for sample in tqdm(samples, desc=folder_split):
              out.write(sample)
```

I have added following lines:
```
tokens = np.frombuffer(sample['tokens'], dtype=np.int64).copy()
token_count += len(tokens)
word_count += len(tokenizer.decode(tokens).split(' '))
```

Command to run:
```
python3 convert_dataset_hf.py --dataset c4 --data_subset en --splits train_small --out_root c4_mds_512_dummy/train --compression zstd --concat_tokens 512 --tokenizer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'
```

The total token_count is 51200000 when concat_tokens is  512

```
python3 convert_dataset_hf.py --dataset c4 --data_subset en --splits train_small --out_root c4_mds_2048_dummy/train --compression zstd --concat_tokens 2048 --tokenizer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'
```

The total token_count is 204800000 when concat_tokens is  2048

Shouldn't the **total** token_count be same given the dataset is same? How come there are many words when  concat tokens is increased?

Since, in the following code snippet from **ConcatTokensDataset**, **hf_dataset:** will be same for any concat_tokens size. So the number of text samples it sees will be same. Hence, the total tokens it yields should be same. But it is not. Am I missing here something?
```
for sample in self.hf_dataset:
      encoded = self.tokenizer(sample['text'],
                               truncation=False,
                               padding=False)
      iids = encoded['input_ids']
      buffer = buffer + self.bos_tokens + iids + self.eos_tokens
      while len(buffer) >= self.max_length:
          concat_sample = buffer[:self.max_length]
          buffer = buffer[self.max_length:] if self.should_wrap else []
          # print(len(concat_sample), len(buffer))
          yield {
              # convert to bytes to store in MDS binary format
              'tokens': np.asarray(concat_sample).tobytes(),
          }

```

**Comment by palash04** [comment]
@dakinggg

**Comment by dakinggg** [comment]
Since you are using the train small data subset, there is a fixed number of samples returned. When you change concat tokens, the number of tokens per sample changes, thus changing the total number of tokens. If you were to process a full dataset with no truncation of the number of samples, it should produce the same number of tokens regardless of concat amount.

**Comment by dakinggg** [comment]
Let me know if this does answer your question.

**Comment by palash04** [comment]
> Let me know if this does answer your question.

Yes, I tried with fixed json data, the number of tokens were same regardless of concat tokens.
Thanks.
