### ISSUE TITLE
Where to provide HF access tokens for evaluating private/gated models

### ISSUE THREAD

**Issue by AbhinavDutta** [mosaicml/llm-foundry#555]
Do I need to put the tokens somewhere in the config files, or in code ? I have no clue. I am trying to evaluate llama-7b, but I dont see any obvious way of supplying the tokens in the eval/eval.py file

**Comment by j316chuck** [comment]
You can try something like this in your command line: `mcli create secret env HUGGING_FACE_HUB_TOKEN=***`.  This will set a secret (hf token) for you: https://docs.mosaicml.com/projects/mcli/en/latest/resources/secrets/index.html

**Comment by j316chuck** [comment]
You canset the huggingface env var before you run your script, e.g: something along the lines of `export HUGGING_FACE_HUB_TOKEN=***`.  Also make sure to do set `use_auth_token` to `True` in the yaml like this [example](https://github.com/mosaicml/llm-foundry/blob/a5b39b67ff4cabd7e50e7c908550965215ff8567/mcli/mcli-hf-eval.yaml#L71)

**Comment by AbhinavDutta** [comment]
It worked, thanks!
