### ISSUE TITLE
Difference between concat tokens vs without concat tokens

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#564]
## Are there benefits to token concatenation during MDS conversion compared to not concatenating tokens?

For instance, if I intend to conduct experiments with various models, opting for token concatenation would require a tokenizer. As a result, when working with different models, I would consistently have to initially perform MDS conversion using the specific model's tokenizer.

@dakinggg

**Comment by dakinggg** [comment]
concatenating tokens allows you to pack sequences together up to the maximum sequence length, which is beneficial for efficiency so that you don't "waste" compute on padding.

**Comment by palash04** [comment]
Gotcha, thanks.
