### ISSUE TITLE
Can we use PyTorch Version 2 to train models?

### ISSUE THREAD

**Issue by linhduongtuan** [mosaicml/llm-foundry#57]
Hi @bmosaicml team,
Thank you for the amazing support of open source code and trained weights.

I am wondering why we cannot use PT v2 for training models. As you know, PT2 is much faster than PT1. However, this README only mentions PT1.

It is quite hard to install flash-attention due to be compatible among PTv1+CUDA, redandent CUDA installed, while PTv2 already supports flash attention.

Best,
Linh

**Comment by vchiley** [comment]
Updating to torch2 is a todo.

Issue:
The current setup uses [this](https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attn_triton.py) Triton implementation of FlashAttn which uses `triton==2.0.0.dev20221202`.
[Torch2.0 upgrades Triton to 2.1.0](https://github.com/pytorch/pytorch/blob/ca9f55f79d944672cb93157836f8ee92f54d2e10/.ci/docker/triton_version.txt)
As noted by @tridao, [this triton update breaks the triton flash attn implementation](https://github.com/HazyResearch/flash-attention/issues/171)
