### ISSUE TITLE
mcli run for 4 nodes in pending state since 5 hours.

### ISSUE THREAD

**Issue by palash04** [mosaicml/llm-foundry#571]
## Command
```
mcli run -f mcli-1b.yaml --gpus 32 --follow
```
Just a day ago the above command was in a **running** state instantly.

But today, it is just in **pending** state for like 5 hours.

When I did -
```
mcli get runs
```
it is the only pending run, all others are either completed or failed.
I have even deleted stopped runs, but still in pending state.

Tried the other cluster that too results in pending forever.

**Comment by dakinggg** [comment]
Hey @palash04, if you are having an issue using our clusters, please follow up on this with customer support, rather than on llm-foundry. Thanks!
