### ISSUE TITLE
mismatched config compared with blog

### ISSUE THREAD

**Issue by donglixp** [mosaicml/llm-foundry#58]
The blog shows that `We also train our MPT models with [the Lion optimizer](https://arxiv.org/abs/2302.06675) rather than AdamW, which provides stable update magnitudes and cuts optimizer state memory in half.`. But in the repo's yaml config (as follows), the AdamW is used.

https://github.com/mosaicml/llm-foundry/blob/3959eaccba53c444c5705d600d333cc3d47bc06c/scripts/train/yamls/mpt/7b.yaml#L60

```yaml
optimizer:
  name: decoupled_adamw
```

**Comment by vchiley** [comment]
The configs in `llm-foundry/scripts/train/yamls/mpt/`are simple starter configs to get people going with our code.
They are not what we use to train the models in the blog; the model config are correct but some of the details of training were modified.

**Comment by donglixp** [comment]
> The configs in `llm-foundry/scripts/train/yamls/mpt/`are simple starter configs to get people going with our code. They are not what we use to train the models in the blog; the model config are correct but some of the details of training were modified.

@vchiley  Thanks for the clarification. Is there any plan to open-source the training yamls?

**Comment by vchiley** [comment]
https://github.com/mosaicml/llm-foundry/issues/70#issuecomment-1544830380
