### ISSUE TITLE
MPT-30B-Chat: Why is `config.vocab_size` different from `len(tokenizer)` ?

### ISSUE THREAD

**Issue by chiragjn** [mosaicml/llm-foundry#590]
## ❓ Question
I noticed for `mpt-30b-chat`, 
- `tokenizer.vocab_size` set to `50254`
- `len(tokenizer)` is `50279`
-  [`config.json`](https://huggingface.co/mosaicml/mpt-30b-chat/blob/6e6da7b9cdb21eefe6dd8ac9a083554a99d4ce5e/config.json) has `vocab_size` set to `50432`

Where does this mismatch arise from?

EDIT: 

> The tokenizer has a vocabulary size of 50257, but we set the model vocabulary size to 50432. The reasons for this were twofold: First, to make it a multiple of 128 (as in [Shoeybi et al.](https://arxiv.org/abs/1909.08053)), which [we found improved MFU by up to four percentage points in initial experiments](https://twitter.com/karpathy/status/1621578354024677377?s=20). Second, to leave tokens available that can be used in subsequent [UL2 training](https://arxiv.org/abs/2205.05131).

Okay, I see the reasoning from mpt-7b-chat release, but yet again I see a new number for the original vocab size.
Can someone please explain how we  went from `50254` tokens to `50279`?
In any case, it seems like there needs to be some way to avoid the model from sampling beyond len(tokenizer)

**Comment by dakinggg** [comment]
Hi @chiragjn, `len(tokenizer)` is the correct way find how many tokens are in the tokenizer. The model has a larger vocab size than this for performance reasons. As long as the tokenizer has _less_ tokens than the model has embeddings, it is safe.
