### ISSUE TITLE
Add GGML support

### ISSUE THREAD

**Issue by jploski** [mosaicml/llm-foundry#60]
It would be nice to have the model supported by GGML, so as to make quantized versions of it or future derivatives also run without GPU. See https://github.com/ggerganov/llama.cpp/issues/1333#issuecomment-1536725381

I gave it a shot myself today, but only managed to get the quantized version to output gibberish - apparently it's not just the state_dict parameter names in the checkpoint that are different from LLaMA (and also from the already supported dolly-v2 and stablelm models), but also the actual transformer implementation... the meat which would go into ggml/examples/mpt/main.cpp... which is way over my head.

Perhaps someone from your dev team could at least assess how difficult such an integration would be - for someone who actually understands the implementation and/or LLMs in general. My feeling is that it requires more understanding of the mosaicml model than of GGML.

**Comment by abhi-mosaic** [comment]
Hi @jploski , thank you building the experimental branch. 

I've checked internally and presently we don't have a timeline for GGML support (we are a small team), but I will personally keep an eye on the [GGML issue thread](https://github.com/ggerganov/llama.cpp/issues/1333#issuecomment-1536725381) and chime in wherever I can help. If priorities change or we get more bandwidth to support GGML, I will update this thread and ping you.

I think your best bet right now might be to get the attention of one of the core GGML contributors and highlight the MPT-7B popularity (>50k downloads in just a few days!). Given their familiarity with the codebase and success with converting LLaMa, I'm quite confident they could port MPT as well. Just a matter of finding the time / resources, as many of these things go.

**Comment by jploski** [comment]
@abhi-mosaic Great news - Lukas Möller did all the hard work and just submitted a PR which provides a basic inference example of MPT-7B (Base) in GGML - https://github.com/ggerganov/ggml/pull/145. I just tried it - seems to work well! Perhaps you can check it out, too.

**Comment by abhi-mosaic** [comment]
Looks like this landed in GGML! Closing this issue for cleanup. 

Thank you for opening up the communication channels and kickstarting this @jploski !
