### ISSUE TITLE
How to freeze some layer within llm-foudry?

### ISSUE THREAD

**Issue by YixinSong-e** [mosaicml/llm-foundry#620]
When I try to set some attention layer parameter's require_grad to False.
The error `FlatParameter` requires uniform `requires_grad` arise.

**Comment by wavy-jung** [comment]
Any update on this issue?

**Comment by dakinggg** [comment]
To freeze the params you can follow https://github.com/mosaicml/llm-foundry/blob/7a7f6df33f9e9938c4b0e82a753ae93d3b43d8c9/llmfoundry/utils/builders.py#L368-L379. With FSDP, you will need to keep frozen and not frozen params in separate fsdp blocks.
