### ISSUE TITLE
SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by YixinSong-e** [mosaicml/llm-foundry#625]
File "/mnt/hwfile/songyixin/newlmf/scripts/train/yamls/pretrain/mpt-1b.yaml", line 24
    name: EleutherAI/gpt-neox-20b
                               ^
SyntaxError: invalid decimal literal

**Comment by dakinggg** [comment]
Hi, please provide more information about what you are running. This is not enough information to help you.

**Comment by YixinSong-e** [comment]
I just running the script in pretrain/yamls/mpt-1b.yaml with composer
