### ISSUE TITLE
Issues following instructions on Ubuntu 22.04 

### ISSUE THREAD

**Issue by jamesd256** [mosaicml/llm-foundry#63]
Hi,

I could do with a pointer on what's going wrong here.  I've followed instructions, and somehow ended up with Torch 1.13.1 when I think it needs 2.x

Cheers,

J.

[llm-foundry-error.txt](https://github.com/mosaicml/llm-foundry/files/11415521/llm-foundry-error.txt)

**Comment by dakinggg** [comment]
This repo is currently on torch 1.13.1. Try manually installing torch 1.13.1 (https://pytorch.org/get-started/previous-versions/#v1131) before installing llmfoundry.

**Comment by jamesd256** [comment]
Thank you for the help.  That got rid of the torch error (on installation of llm-foundry), but still I have the line: 

trainer 0.0.20 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible

Unfortunately I wasn't able to find any obvious answer while searching, and I've found randomly trying things rarely gets me there with python dependency issues

**Comment by dakinggg** [comment]
It looks like `trainer` is a package you have unrelated to foundry. I'd suggest trying out foundry in a new, clean environment.

**Comment by jamesd256** [comment]
I had a blind stab at it and went with :+1: 

`conda install protobuf=3.20`

No errors on llm-foundry install this time, trying training again now

**Comment by jamesd256** [comment]
> It looks like `trainer` is a package you have unrelated to foundry. I'd suggest trying out foundry in a new, clean environment.

I'm just getting to grips with setting up environments and such.  Should I have set one up first?  Perhaps it's such common knowledge that this should be tried in a venv, that it wasn't worth mentioning it in the guide.  

On the other hand I guess folks will come to this without any prior experience.  Maybe worth mentioning?  I could be off bream here.

**Comment by dakinggg** [comment]
It's good practice with python to set up a new environment for each project you're working on to avoid dependency issues. I'll add it to the instructions :)

**Comment by jamesd256** [comment]
Another probably noob moment, I had assumed that I could attempt this on a single 24gb card, as I saw we're only training a 125m param model.  

Possibly as expected, but I got a Cuda out of memory running the second command (train.py)

In my case I have access to as many a100s as necessary to get this done, but to avoid others being disappointed, maybe a comment about resources needed could also help the inexperienced like me.

Of course there might be a reason why I got OOM...  More investigation needed on my part

**Comment by jamesd256** [comment]
Seems the initial issue is resolved, many thanks.  I'll work out the memory stuff
