### ISSUE TITLE
Intermediate Checkpoint?

### ISSUE THREAD

**Issue by KaiserWhoLearns** [mosaicml/llm-foundry#633]
## ❓ Question

Thank you for making the model available!
Will the intermediate checkpoints during pretraining be released as well? (e.g. Checkpoints by pre-training steps/tokens, as in [Pythia](https://github.com/EleutherAI/pythia) and [OPT](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/README.md))

**Comment by dakinggg** [comment]
Hi, we do not have plans to release intermediate checkpoints of the MPT models at this time. All of the model variants that we have released can be found on our [huggingface organization page](https://huggingface.co/mosaicml)
