### ISSUE TITLE
MPT-7B-Storywriter multi-gpu Inference

### ISSUE THREAD

**Issue by Sleepyhead01** [mosaicml/llm-foundry#658]
The Mosaic blog post claims that
`StoryWriter-65k+ can extrapolate even beyond 65k tokens. We demonstrate generations as long as 84k tokens on a single node of 8 A100-80GB GPUs`

Wanted to test this out but can't find code for multi GPU inference. Please point out if I'm missing something.

**Comment by dakinggg** [comment]
Hi, you can use Hugging Face's `device_map="auto"` to get naive pipeline parallelism (https://huggingface.co/docs/accelerate/usage_guides/big_modeling).
