### ISSUE TITLE
FasterTransformer

### ISSUE THREAD

**Issue by xgal** [mosaicml/llm-foundry#67]
Hi, I saw in mpt model card that the models could run with FasterTransformer
I didn't find any details about that anywhere
can you guys share the conversion scripts or help there? 

Thanks

**Comment by xgal** [comment]
Thanks @vchiley 
AFAIK it is using AliBi and some other things that aren't native in GPT FT version
maybe Bloom is more similar? and from playing with mpt around in HF version and try base as GPT / Bloom (by renaming and loading state dicts) I get nonsense so I wonder if there is some other impl. that prevents it straight forward such as other ordering in QKV layers or etc. 

wdyt ?

Thanks !!

**Comment by vchiley** [comment]
> Transformer Engine

We've played around with [TE and H100 FP8 support](https://www.mosaicml.com/blog/coreweave-nvidia-h100-part-1)
It works and we'll include everything when we have more seat time with H100s so we can test everything more thoroughly.

**Comment by SinanAkkoyun** [comment]
@vchiley Thank you so much! 🚀😍

**Comment by meitalbensinai** [comment]
I also need the FT conversion script; it would be super helpful for me 🥰

**Comment by SinanAkkoyun** [comment]
@vchiley You are also talking about uzing TransformerEngine in inference right?

**Comment by dskhudia** [comment]
We will soon add conversion and run scripts

**Comment by therealadityashankar** [comment]
I'd greatly appreciate that so so much!

**Comment by dskhudia** [comment]
@xgal , @SinanAkkoyun , @meitalbensinai , @therealadityashankar : Conversion script was added in #169 . Please give it a try and let us know if you run into any issues.

**Comment by therealadityashankar** [comment]
@dskhudia this is nice, I would love a script to run this with tokenizers, or a minimal example, so I can check this out

**Comment by dskhudia** [comment]
@xgal , @SinanAkkoyun , @meitalbensinai , @therealadityashankar : The script to run the converted model has also been added. Let us know if you face any issues.

**Comment by SinanAkkoyun** [comment]
Hi! What TPS is expected for the FT implementation?

**Comment by dskhudia** [comment]
It depends on batching vs no batching, input/output lengths etc. but I see the following numbers on A100-40G:
<img width="408" alt="Screenshot 2023-05-30 at 3 55 09 PM" src="https://github.com/mosaicml/llm-foundry/assets/37562707/a749bb1a-7d16-4b91-8e56-daad073f858a">

**Comment by SinanAkkoyun** [comment]
@dskhudia 
Thank you very much!!! <3

**Comment by wuflyh** [comment]
I converted the mpt7b model into fastertransformer format and served it as a http service using triton inference server. 
however it failed to generate. 
e.g. with input "the model does not work "
the output is "the model does not work ���������������������"
Anyone knowing why? Thanks.

**Comment by dskhudia** [comment]
@nik-mosaic had to do the setup right to make it generate. @nik-mosaic please take a look.

**Comment by wuflyh** [comment]
@nik-mosaic  yes  I am following the GPT config.pbtxt and above is my file. I generated the fastertransformer format for 2 gpus so set the "tensor_para_size" to 2

**Comment by wuflyh** [comment]
the triton inference server launches normally.  there is no error in the log when inferencing.

**Comment by wuflyh** [comment]
I actually wants to try to see if it works on 1-gpu. will update after a while. Thanks.

**Comment by wuflyh** [comment]
@nik-mosaic what version of triton-ft-backend do you use to serve the mpt7b model? Thanks.

**Comment by wuflyh** [comment]
Thanks @nik-mosaic that might be the reason. I was using 22.12. I will install 23.04 to give it a try.

**Comment by wuflyh** [comment]
still does not work with TIS 23.04

**Comment by wuflyh** [comment]
> @wuflyh Were you ever able to get this working? We have moved away from FasterTransformer but our config.pbtxt was
> 
> ```
> name: "mpt"
> backend: "fastertransformer"
> default_model_filename: "mpt"
> max_batch_size: <your max batch size>
> 
> model_transaction_policy {
>   decoupled: False
> }
> 
> batch_input [
>   {
>     kind: BATCH_ITEM_SHAPE
>     target_name: "input_ids_item_shape"
>     data_type: TYPE_INT32
>     source_input: "input_ids"
>   }
> ]
> 
> input [
>   {
>     name: "input_ids"
>     data_type: TYPE_UINT32
>     dims: [ -1 ]
>     allow_ragged_batch: true
>   },
>   {
>     name: "input_lengths"
>     data_type: TYPE_UINT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>   },
>   {
>     name: "request_output_len"
>     data_type: TYPE_UINT32
>     dims: [ -1 ]
>   },
>   {
>     name: "runtime_top_k"
>     data_type: TYPE_UINT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "runtime_top_p"
>     data_type: TYPE_FP32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "beam_search_diversity_rate"
>     data_type: TYPE_FP32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "temperature"
>     data_type: TYPE_FP32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "len_penalty"
>     data_type: TYPE_FP32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "repetition_penalty"
>     data_type: TYPE_FP32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "random_seed"
>     data_type: TYPE_INT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "is_return_log_probs"
>     data_type: TYPE_BOOL
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "beam_width"
>     data_type: TYPE_UINT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "start_id"
>     data_type: TYPE_UINT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "end_id"
>     data_type: TYPE_UINT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "stop_words_list"
>     data_type: TYPE_INT32
>     dims: [ 2, -1 ]
>     optional: true
>   },
>   {
>     name: "bad_words_list"
>     data_type: TYPE_INT32
>     dims: [ 2, -1 ]
>     optional: true
>   },
>   {
>     name: "prompt_learning_task_name_ids"
>     data_type: TYPE_UINT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "request_prompt_embedding"
>     data_type: TYPE_FP16
>     dims: [ -1, -1 ]
>     optional: true
>   },
>   {
>     name: "request_prompt_lengths"
>     data_type: TYPE_UINT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   },
>   {
>     name: "request_prompt_type"
>     data_type: TYPE_UINT32
>     dims: [ 1 ]
>     reshape: { shape: [ ] }
>     optional: true
>   }
> ]
> output [
>   {
>     name: "output_ids"
>     data_type: TYPE_UINT32
>     dims: [ -1, -1 ]
>   },
>   {
>     name: "sequence_length"
>     data_type: TYPE_UINT32
>     dims: [ -1 ]
>   },
>   {
>     name: "response_input_lengths"
>     data_type: TYPE_INT32
>     dims: [ -1 ]
>   },
>   {
>     name: "cum_log_probs"
>     data_type: TYPE_FP32
>     dims: [ -1 ]
>   },
>   {
>     name: "output_log_probs"
>     data_type: TYPE_FP32
>     dims: [ -1, -1 ]
>   }
> ]
> instance_group [
>   {
>     count: 1
>     kind : KIND_CPU
>   }
> ]
> parameters {
>   key: "tensor_para_size"
>   value: {
>     string_value: "1"
>   }
> }
> parameters {
>   key: "pipeline_para_size"
>   value: {
>     string_value: "1"
>   }
> }
> parameters {
>   key: "data_type"
>   value: {
>     string_value: "bf16"
>   }
> }
> parameters {
>   key: "model_type"
>   value: {
>     string_value: "GPT"
>   }
> }
> parameters {
>   key: "int8_mode"
>   value: {
>     string_value: "0"
>   }
> }
> parameters {
>   key: "enable_custom_all_reduce"
>   value: {
>     string_value: "0"
>   }
> }
> ```

it still did not work since my last attempt about 2 month back using TIS 23.04. You wont support fastertransformer anymore?
