### ISSUE TITLE
Do we have to use StreamingDataset for pretraining runs?

### ISSUE THREAD

**Issue by eldarkurtic** [mosaicml/llm-foundry#696]
Hi,
Is it possible to use llm-foundry to run pretraining without going through StreamingDataset? 

At this point, it became a pain point for my runs and I would love to go without it if possible.

For example:
1. can't run more than one run on a single server (https://github.com/mosaicml/streaming/issues/306)
2. converting HF dataset to Streaming requires updating ulimit (https://github.com/mosaicml/llm-foundry/issues/406), which does not solve the issue for me

**Comment by dakinggg** [comment]
Hi Eldar, we have only implemented pretraining via the `StreamingTextDataset` class, which use `StreamingDataset`. If you implement your own dataset class (and subsequent dataloader creation) however, you can use whatever underlying dataset you like.
