### ISSUE TITLE
MPT models on the Hub not working with `transformers` main

### ISSUE THREAD

**Issue by younesbelkada** [mosaicml/llm-foundry#703]
Hi there! 

Currently with transformers main loading MPT models from the Hub fails because it tries to import some private method (such as `_expand_mask` ) that has been recently removed: https://github.com/huggingface/transformers/pull/27086

The simple loading script below should work

```python
from accelerate import init_empty_weights
from transformers import AutoModelForCausalLM, AutoConfig

model_id = "mosaicml/mpt-7b"
config = AutoConfig.from_pretrained(
    model_id, trust_remote_code=True
)
with init_empty_weights():
    model = AutoModelForCausalLM.from_config(
        config, trust_remote_code=True
    )
```

**Comment by dakinggg** [comment]
Thanks for letting us know Younes, will look into this ASAP

**Comment by younesbelkada** [comment]
Thanks @dakinggg !

**Comment by dakinggg** [comment]
@younesbelkada this should be resolved in the foundry code now, and I'm uploading the updated code to the hf hub as we speak.

**Comment by dakinggg** [comment]
Ok, this should be resolved completely now. Let me know if you see otherwise! Thanks again for the report :)

**Comment by younesbelkada** [comment]
Works now like charm! Thanks for the quick fix @dakinggg
