### ISSUE TITLE
Windows support ?

### ISSUE THREAD

**Issue by deepbeepmeep** [mosaicml/llm-foundry#71]
Hello
I have been unable to run the model on Windows since the install fails as it requires Triton that is only supported on Linux.

Any idea ?

Thanks in advance

**Comment by deepbeepmeep** [comment]
thanks. How do you set "attn_impl: torch" ?

**Comment by deepbeepmeep** [comment]
ok I have figured how to do it. 

Here are the results:
- with Windows, it hangs forever after 'the "Warming up.." message. The reason could be that it is slow because the CPU is forced to be used. 

- with Linux (Windows / WSL) the initialization is a few minutes and then it proceeds

Is there a reason why the init is so slow ? I use a M2 drive with  i713700 / RTX 4090.

Moreover  it seems Triton can not be used on Linux with my config because ADA (sm_89) is not supported by Triton

**Comment by deepbeepmeep** [comment]
Fyi Triton 2.1 supports ADA while the current version you use (2.0) doesn't.  llm foundry won't le met use Triton 2.1 since version 2.0 is hardcoded.

**Comment by deepbeepmeep** [comment]
Triton 2.0 is hard coded inside the Hugging Face transfomer code. So there is no way I can change it.
Besides my main problem right now is that the initialization takes forever (a few minutes) on my high end rig. Not much is going except that one CPU core is 100%. Is this expected ? anyway to fix that ?

**Comment by hanlint** [comment]
Hello @deepbeepmeep , unfortunately we do not have a lot of experience with Windows to help diagnose here.
