### ISSUE TITLE
Bloom Tokenizer doen't work 

### ISSUE THREAD

**Issue by robi56** [mosaicml/llm-foundry#726]

**Comment by robi56** [comment]
during training the below errors occured 

Starting training...
2023-11-09 16:18:48,391: rank0[147193][MainThread]: INFO: composer.trainer.trainer: Using precision Precision.FP32
******************************
Config:
enabled_algorithms/GradientClipping: true
node_name: unknown because NODENAME environment variable not set
num_cpus_per_node: 1
num_nodes: 1
rank_zero_seed: 17
time/remaining_estimate_unit: hours

******************************
2023-11-09 16:18:48,393: rank0[147193][MainThread]: DEBUG: composer.trainer.trainer: Spinning the dataloaders
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/llm/llm-foundry/scripts/train/train.py:654 in <module>                                      │
│                                                                                                  │
│   651 │   cfg = om.merge(yaml_cfg, cli_cfg)                                                      │
│   652 │   om.resolve(cfg)                                                                        │
│   653 │   assert isinstance(cfg, DictConfig)                                                     │
│ ❱ 654 │   main(cfg)                                                                              │
│   655                                                                                            │
│                                                                                                  │
│ /mnt/llm/llm-foundry/scripts/train/train.py:640 in main                                          │
│                                                                                                  │
│   637 │   │   trainer.eval()                                                                     │
│   638 │                                                                                          │
│   639 │   print('Starting training...')                                                          │
│ ❱ 640 │   trainer.fit()                                                                          │
│   641 │                                                                                          │
│   642 │   print('Done.')                                                                         │
│   643 │   return trainer                                                                         │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/composer/trainer/trainer.py:1876 in   │
│ fit                                                                                              │
│                                                                                                  │
│   1873 │   │   │   self.state.scaler = ClosureGradScaler() if self._use_closures() else GradSca  │
│   1874 │   │                                                                                     │
│   1875 │   │   self.first_batch_complete = False                                                 │
│ ❱ 1876 │   │   self._train_loop()                                                                │
│   1877 │                                                                                         │
│   1878 │   def close(self):                                                                      │
│   1879 │   │   """Shutdown the trainer.                                                          │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/composer/trainer/trainer.py:2051 in   │
│ _train_loop                                                                                      │
│                                                                                                  │
│   2048 │   │   │   │   │   │   self.logger.log_metrics({'time/token': self.state.timestamp.toke  │
│   2049 │   │   │   │   │   │   self.logger.log_metrics({'time/token_in_epoch': self.state.times  │
│   2050 │   │   │   │   │                                                                         │
│ ❱ 2051 │   │   │   │   │   total_loss_dict = self._train_batch(use_grad_scaling)                 │
│   2052 │   │   │   │   │                                                                         │
│   2053 │   │   │   │   │   if use_grad_scaling:                                                  │
│   2054 │   │   │   │   │   │   self.state.scaler.update()                                        │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/composer/trainer/trainer.py:2236 in   │
│ _train_batch                                                                                     │
│                                                                                                  │
│   2233 │   │   │   │   │   │   │   │   │   │   │   │      closure=lambda loss_dict=total_loss_d  │
│   2234 │   │   │   │   │   │   │   │   │   │   │   │      _train_microbatches(microbatches, los  │
│   2235 │   │   │   │   │   │   else:                                                             │
│ ❱ 2236 │   │   │   │   │   │   │   optimizer.step(closure=lambda loss_dict=total_loss_dict, **k  │
│   2237 │   │   │   │   │   │   │   │   microbatches, loss_dict, **kwargs).item())                │
│   2238 │   │   │   │   else:                                                                     │
│   2239 │   │   │   │   │   self._train_microbatches(microbatches, total_loss_dict)               │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:68 in     │
│ wrapper                                                                                          │
│                                                                                                  │
│     65 │   │   │   │   instance = instance_ref()                                                 │
│     66 │   │   │   │   instance._step_count += 1                                                 │
│     67 │   │   │   │   wrapped = func.__get__(instance, cls)                                     │
│ ❱   68 │   │   │   │   return wrapped(*args, **kwargs)                                           │
│     69 │   │   │                                                                                 │
│     70 │   │   │   # Note that the returned function here is no longer a bound method,           │
│     71 │   │   │   # so attributes like `__func__` and `__self__` no longer exist.               │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/optim/optimizer.py:373 in       │
│ wrapper                                                                                          │
│                                                                                                  │
│   370 │   │   │   │   │   │   │   │   f"{func} must return None or a tuple of (new_args, new_k   │
│   371 │   │   │   │   │   │   │   )                                                              │
│   372 │   │   │   │                                                                              │
│ ❱ 373 │   │   │   │   out = func(*args, **kwargs)                                                │
│   374 │   │   │   │   self._optimizer_step_code()                                                │
│   375 │   │   │   │                                                                              │
│   376 │   │   │   │   # call optimizer step post hooks                                           │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/utils/_contextlib.py:115 in     │
│ decorate_context                                                                                 │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/composer/optim/decoupled_weight_decay │
│ .py:277 in step                                                                                  │
│                                                                                                  │
│   274 │   │   loss = None                                                                        │
│   275 │   │   if closure is not None:                                                            │
│   276 │   │   │   with torch.enable_grad():                                                      │
│ ❱ 277 │   │   │   │   loss = closure()                                                           │
│   278 │   │                                                                                      │
│   279 │   │   for group in self.param_groups:                                                    │
│   280 │   │   │   params_with_grad = []                                                          │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/composer/trainer/trainer.py:2236 in   │
│ <lambda>                                                                                         │
│                                                                                                  │
│   2233 │   │   │   │   │   │   │   │   │   │   │   │      closure=lambda loss_dict=total_loss_d  │
│   2234 │   │   │   │   │   │   │   │   │   │   │   │      _train_microbatches(microbatches, los  │
│   2235 │   │   │   │   │   │   else:                                                             │
│ ❱ 2236 │   │   │   │   │   │   │   optimizer.step(closure=lambda loss_dict=total_loss_dict, **k  │
│   2237 │   │   │   │   │   │   │   │   microbatches, loss_dict, **kwargs).item())                │
│   2238 │   │   │   │   else:                                                                     │
│   2239 │   │   │   │   │   self._train_microbatches(microbatches, total_loss_dict)               │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/composer/trainer/trainer.py:2339 in   │
│ _train_microbatches                                                                              │
│                                                                                                  │
│   2336 │   │   │                                                                                 │
│   2337 │   │   │   for microbatch_idx, self.state.batch in enumerate(microbatches):              │
│   2338 │   │   │   │   is_final_microbatch = microbatch_idx + 1 == len(microbatches)             │
│ ❱ 2339 │   │   │   │   microbatch_loss_dict = self._train_microbatch(use_grad_scaling, current_  │
│   2340 │   │   │   │                                                                             │
│   2341 │   │   │   │   # Aggregate each loss in microbatch_loss_dict into total_loss_dict        │
│   2342 │   │   │   │   for k, microbatch_loss in microbatch_loss_dict.items():                   │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/composer/trainer/trainer.py:2403 in   │
│ _train_microbatch                                                                                │
│                                                                                                  │
│   2400 │   │   │                                                                                 │
│   2401 │   │   │   with _get_precision_context(self.state.precision, self.state.precision_confi  │
│   2402 │   │   │   │   │   │   │   │   │   │   self.state.deepspeed_enabled):                    │
│ ❱ 2403 │   │   │   │   self.state.outputs = self.state.model(self.state.batch)                   │
│   2404 │   │   │                                                                                 │
│   2405 │   │   │   self.engine.run_event(Event.AFTER_FORWARD)                                    │
│   2406                                                                                           │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1518 in    │
│ _wrapped_call_impl                                                                               │
│                                                                                                  │
│   1515 │   │   if self._compiled_call_impl is not None:                                          │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1517 │   │   else:                                                                             │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1519 │                                                                                         │
│   1520 │   def _call_impl(self, *args, **kwargs):                                                │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1527 in    │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1528 │   │                                                                                     │
│   1529 │   │   try:                                                                              │
│   1530 │   │   │   result = None                                                                 │
│                                                                                                  │
│ /mnt/llm/llm-foundry/llmfoundry/models/mpt/modeling_mpt.py:842 in forward                        │
│                                                                                                  │
│   839 │   │   if self.model.transformer.prefix_lm:                                               │
│   840 │   │   │   add_bidirectional_mask_if_missing(batch)                                       │
│   841 │   │   # Note: prefix_mask is only used if model.prefix_lm is True                        │
│ ❱ 842 │   │   return self.model(                                                                 │
│   843 │   │   │   input_ids=batch['input_ids'],                                                  │
│   844 │   │   │   attention_mask=batch.get('attention_mask', None),                              │
│   845 │   │   │   prefix_mask=batch.get('bidirectional_mask', None),                             │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1518 in    │
│ _wrapped_call_impl                                                                               │
│                                                                                                  │
│   1515 │   │   if self._compiled_call_impl is not None:                                          │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1517 │   │   else:                                                                             │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1519 │                                                                                         │
│   1520 │   def _call_impl(self, *args, **kwargs):                                                │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1527 in    │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1528 │   │                                                                                     │
│   1529 │   │   try:                                                                              │
│   1530 │   │   │   result = None                                                                 │
│                                                                                                  │
│ /mnt/llm/llm-foundry/llmfoundry/models/mpt/modeling_mpt.py:649 in forward                        │
│                                                                                                  │
│   646 │   │   │   raise NotImplementedError(                                                     │
│   647 │   │   │   │   'inputs_embeds has to be None (for hf/peft support).')                     │
│   648 │   │   # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)    │
│ ❱ 649 │   │   outputs = self.transformer(                                                        │
│   650 │   │   │   input_ids=input_ids,                                                           │
│   651 │   │   │   past_key_values=past_key_values,                                               │
│   652 │   │   │   attention_mask=attention_mask,                                                 │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1518 in    │
│ _wrapped_call_impl                                                                               │
│                                                                                                  │
│   1515 │   │   if self._compiled_call_impl is not None:                                          │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1517 │   │   else:                                                                             │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1519 │                                                                                         │
│   1520 │   def _call_impl(self, *args, **kwargs):                                                │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1527 in    │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1528 │   │                                                                                     │
│   1529 │   │   try:                                                                              │
│   1530 │   │   │   result = None                                                                 │
│                                                                                                  │
│ /mnt/llm/llm-foundry/llmfoundry/models/mpt/modeling_mpt.py:437 in forward                        │
│                                                                                                  │
│   434 │   │   ), f'Cannot forward input with seq_len={S}, this model only supports seq_len<={s   │
│   435 │   │                                                                                      │
│   436 │   │   rotary_emb_w_meta_info = None                                                      │
│ ❱ 437 │   │   x = self.wte(input_ids)                                                            │
│   438 │   │   if self.learned_pos_emb or self.rope:                                              │
│   439 │   │   │   past_position = 0                                                              │
│   440 │   │   │   if past_key_values is not None:                                                │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1518 in    │
│ _wrapped_call_impl                                                                               │
│                                                                                                  │
│   1515 │   │   if self._compiled_call_impl is not None:                                          │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1517 │   │   else:                                                                             │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1519 │                                                                                         │
│   1520 │   def _call_impl(self, *args, **kwargs):                                                │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1527 in    │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1528 │   │                                                                                     │
│   1529 │   │   try:                                                                              │
│   1530 │   │   │   result = None                                                                 │
│                                                                                                  │
│ /mnt/llm/llm-foundry/llmfoundry/models/layers/custom_embedding.py:14 in forward                  │
│                                                                                                  │
│   11 │   def forward(self, input: Tensor, unembed: bool = False) -> Tensor:                      │
│   12 │   │   if unembed:                                                                         │
│   13 │   │   │   return F.linear(input, self.weight)                                             │
│ ❱ 14 │   │   return super().forward(input)                                                       │
│   15                                                                                             │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/modules/sparse.py:162 in     │
│ forward                                                                                          │
│                                                                                                  │
│   159 │   │   │   │   self.weight[self.padding_idx].fill_(0)                                     │
│   160 │                                                                                          │
│   161 │   def forward(self, input: Tensor) -> Tensor:                                            │
│ ❱ 162 │   │   return F.embedding(                                                                │
│   163 │   │   │   input, self.weight, self.padding_idx, self.max_norm,                           │
│   164 │   │   │   self.norm_type, self.scale_grad_by_freq, self.sparse)                          │
│   165                                                                                            │
│                                                                                                  │
│ /home/rabindra_nandi/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:2233 in        │
│ embedding                                                                                        │
│                                                                                                  │
│   2230 │   │   #   torch.embedding_renorm_                                                       │
│   2231 │   │   # remove once script supports set_grad_enabled                                    │
│   2232 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)                    │
│ ❱ 2233 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)        │
│   2234                                                                                           │
│   2235                                                                                           │
│   2236 def embedding_bag(                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: index out of range in self
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Closing the engine.
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Closing callback ConsoleLogger
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Closing callback SpeedMonitor
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Closing callback LRMonitor
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Closing callback MemoryMonitor
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Closing callback RuntimeEstimator
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Closing callback CheckpointSaver
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Post-closing callback ConsoleLogger
2023-11-09 16:18:50,698: rank0[147193][MainThread]: DEBUG: composer.core.engine: Post-closing callback SpeedMonitor
2023-11-09 16:18:50,699: rank0[147193][MainThread]: DEBUG: composer.core.engine: Post-closing callback LRMonitor
2023-11-09 16:18:50,699: rank0[147193][MainThread]: DEBUG: composer.core.engine: Post-closing callback MemoryMonitor
2023-11-09 16:18:50,699: rank0[147193][MainThread]: DEBUG: composer.core.engine: Post-closing callback RuntimeEstimator
2023-11-09 16:18:50,699: rank0[147193][MainThread]: DEBUG: composer.core.engine: Post-closing callback CheckpointSaver
2023-11-09 16:18:50,715: rank0[147193][MainThread]: DEBUG: composer.core.engine: Engine closed.
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 0 (PID 147193) exited with code 1
ERROR:composer.cli.launcher:Global rank 0 (PID 147193) exited with code 1
``

**Comment by dakinggg** [comment]
This is not information to understand what happened. Please provide your full training yaml/setup.

**Comment by robi56** [comment]
```
      python data_prep/convert_dataset_json.py \
  --path /mnt/llm/25gb/mix_50k \
  --out_root /mnt/llm/mix_50k_bloom --split train \
  --concat_tokens 2048 --tokenizer hishab/bn_en_250g_tokenizer_100K_vocab_bloom  --bos_text '<s>'  --eos_text '</s>'  \
  --compression zstd

  
   composer train/train.py \
  train/yamls/pretrain/mpt-small-cpu.yaml \
  data_local=/mnt/llm/mix_50k_bloom \
  train_loader.dataset.split=train \
  eval_loader.dataset.split=val \
  max_duration=10ba \
  eval_interval=0 \
  save_folder=out_mix_50k_bloom
```

**Comment by dakinggg** [comment]
You will need to match the vocab size of your model (e.g. https://github.com/mosaicml/llm-foundry/blob/d1960f2ca842397bcb39d1bd13139b363c21641e/scripts/train/yamls/pretrain/mpt-small-cpu.yaml#L18) with the vocab size of your tokenizer.
