### ISSUE TITLE
Is flops calculation correct?

### ISSUE THREAD

**Issue by lorabit110** [mosaicml/llm-foundry#909]
It seems when llm-foundry calculates flops for MPT models, n_heads is not taken into consideration:
https://github.com/mosaicml/llm-foundry/blob/2634987909ddc8923b762170cb9aa2870e31d5cc/llmfoundry/models/mpt/modeling_mpt.py#L1091

Based on [PaLM paper](https://arxiv.org/pdf/2204.02311.pdf), the attention part (`attn_flops_per_seq`) should be calculated as `2*2*LHQT^2` (a factor of 3 is removed because it's added [here](https://github.com/mosaicml/llm-foundry/blob/2634987909ddc8923b762170cb9aa2870e31d5cc/llmfoundry/models/mpt/modeling_mpt.py#L1106)), but in llm-foundry's implementation, it's `2*2*LQT^2`. Why is `n_heads` or `H` missing from the calculation? Did I miss anything? 

![image](https://github.com/mosaicml/llm-foundry/assets/108375850/32d63303-ac8e-44d5-ac07-dcb96fb814e2)

**Comment by dakinggg** [comment]
Hi, with the variables you are using, Foundry's implementation is not `2*2*LQT^2`, as `Q` is `head dimension`, but in the foundry implementation is actually `d_model`, which is the same as `num heads` * `head dimension`.

**Comment by lorabit110** [comment]
Thanks for the explanation! It makes sense to me now.
