### ISSUE TITLE
How to use the train.py finetuning the pre-trained MPT-7B?

### ISSUE THREAD

**Issue by metacarbon** [mosaicml/llm-foundry#91]
It seems like we need to perform the pre-trainning process to get the checkpoint file before we can fine-tuning the MPT model.

1b_local_data_sft.yaml mentioned that we have to replace the load_path with our own checkpoint path.

Can I use the one (.bin) in Hugging Face as the pre-trained model loading file?

**Comment by samhavens** [comment]
Hi @metacarbon, I have [a PR here](https://github.com/mosaicml/llm-foundry/pull/101) which hopefully addresses the issue you are running into. Basically, `load_path` is for Composer checkpoints; there is a different syntax for models loaded from the HF Hub in HF format. tl;dr use [this yaml](https://github.com/mosaicml/llm-foundry/blob/d4c47f6e3150d50e500eb7eae641d398c2065ffe/scripts/train/yamls/finetune/mpt-7b_dolly_sft.yaml)|

However,

```yaml
  config_overrides:
    attn_impl: triton
```

won't work until #90 is merged in

**Comment by alextrott16** [comment]
@metacarbon The PR mentioned above has gone through and should make it easier to finetune from the pretrained MPT-7b model on Hugging Face.

Do you have more questions in this area? If not, I'll close the issue.

**Comment by metacarbon** [comment]
@alextrott16  Recently, I don't have time to test it. Thanks for the PR I know how to fine-tuning MPT with HF. Thank you all of you for the support!

**Comment by alextrott16** [comment]
Happy to be of service :)
