### ISSUE TITLE
Finetune MPT-7B with 48GiB of VRAM?

### ISSUE THREAD

**Issue by juanps90** [mosaicml/llm-foundry#93]
Is there any way to finetune the MPT-7B model with dual RTX 3090's?

Thank you.

**Comment by samhavens** [comment]
You won't be able to do full fine-tuning with that much VRAM, but follow along #64, because LoRA should work (but it isn't supported yet).

**Comment by zafercavdar** [comment]
Is it possible to finetune with 4x A100 40GB GPUs?
