### ISSUE TITLE
FasterTransformer inference with MPT-7b

### ISSUE THREAD

**Issue by SinanAkkoyun** [mosaicml/llm-foundry#96]
Hello! How do I run the MPT-7b as advertised with FasterTransformer? I need the fastest inference possible, if that is with FasterTransformer or FlashAttention etc.

I would be very grateful for any help!

**Comment by SinanAkkoyun** [comment]
@abhi-mosaic Thank you very much! 😍

**Comment by SinanAkkoyun** [comment]
@abhi-mosaic Are you also working on implementing the MPT 7b family with NVIDIAs TransformerEngine (for H100 compute capability 9 inference)? That would be game-changing!

Thank you very much

**Comment by abhi-mosaic** [comment]
Yep, we have already been profiling LLM training on H100 with FP8 and you can see [our blog post here.](https://www.mosaicml.com/blog/coreweave-nvidia-h100-part-1)

I cannot give you an exact timeline right now but be sure that when it's ready, you will hear about it :)
