### ISSUE TITLE
Protobuf version conflict

### ISSUE THREAD

**Issue by junaidid** [mosaicml/llm-foundry#99]
error: protobuf 3.20.3 is installed but protobuf>=4.22.0 is required by {'mosaicml-cli'}

I get this when I run setup.py

So I did a pip install protobuf==4.22.0

Now I get this error

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mosaicml-cli 0.4.0a6 requires argcomplete>=2.0.0, which is not installed.
mosaicml-cli 0.4.0a6 requires arrow>=1.2.2, which is not installed.
mosaicml-cli 0.4.0a6 requires backoff>=2.2.1, which is not installed.
mosaicml-cli 0.4.0a6 requires docker>=5.0.3, which is not installed.
mosaicml-cli 0.4.0a6 requires gql[websockets]>=3.4.0, which is not installed.
mosaicml-cli 0.4.0a6 requires prompt-toolkit>=3.0.29, which is not installed.
onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 4.22.0 which is incompatible.

It's the last line which is conflicting versions of protobuf

**Comment by mvpatel2000** [comment]
@junaidid Feel free to leave `protobuf` at `3.20.3` / force install it there if necessary. Mcli should not require such a high version. We've patched this in dev, and it should have a lower floor in the next release of `mosaicml-cli` that will remove this pip issue.
